### ISSUE TITLE
`opam switch link ...` creates a broken switch when linking a local switch based on a system switch

### ISSUE THREAD

**Issue by hcarty** [ocaml/opam#3838] opened 2019-05-08 22:29 UTC
I have a `default` global switch using `ocaml-base-compiler.4.07.1`.  I have a local switch under `$HOME/project` which uses `default` as a "system" switch.  Both of these switches work as expected.

If I create a switch linked to `$HOME/project`, the switch will be missing the OCaml compiler (no `ocamlc` and friends).

```bash
mkdir $HOME/project-clone
cd $HOME/project-clone
opam switch link ../project
which ocamlc # Oh no, it's gone!
```

**Comment by rjbou** [comment] 2019-05-09 14:55
How did you setup the `$HOME/project` switch? I tied to reproduce using modification in `PATH` to force use of a switch compiler as system one, and the `project-clone` switch get well linked.

```bash
$ opam config var sys-ocaml-version -vv
+ /usr/bin/ocamlc "-vnum"
- 4.02.3
4.02.3

$ export PATH=.opam/default/bin:$PATH
$ opam config var sys-ocaml-version -vv
+ .opam/default/bin/ocamlc "-vnum"
- 4.07.1
4.07.1

$ mkdir project && cd project
$ opam switch create .
<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
∗ installed base-bigarray.base
∗ installed base-threads.base
∗ installed base-unix.base
∗ installed ocaml-system.4.07.1
∗ installed ocaml-config.1
∗ installed ocaml.4.07.1
Done.
$ opam config var sys-ocaml-version -vv
+ .opam/default/bin/ocamlc "-vnum"
- 4.07.1
4.07.1

$ cd ../ && mkdir project-clone && cd project-clone
$ opam sw link ../project
Directory /tmp/project-clone set to use switch /tmp/project.
Just remove /tmp/project-clone/_opam to unlink.
$ opam config var sys-ocaml-version -vv
+ .opam/default/bin/ocamlc "-vnum"
- 4.07.1
4.07.1
$ which ocamlc
.opam/rjbou/bin/ocamlc

```

**Comment by AltGr** [comment] 2019-05-20 13:29
>  I have a local switch under $HOME/project which uses default as a "system" switch.

This is a bad idea. It's not supported and I am afraid it will probably bring you a lot of other problems down the pipe. I am actually curious how opam let you do it, normally its own switches should be excluded from system compiler detection. You might have got there through a bug ?

In any case, I understand that the underlying issue is the lack of sharing of compilation artifacts from switches, and the time needed for every switch creation. We are investigating solutions to that.

There is also something to investigate with the linked switch, because it's actually expected to be resolved as the same switch as `.../project`, so it's strange that there is a difference.

**Comment by hcarty** [comment] 2019-05-20 16:56
@AltGr @rjbou I'm not sure what lead to opam using one of its own switches as a system switch - it wasn't something that I tried to configure, but it happens when I create a new switch and don't explicitly specify a compiler.

Since that switch environment is error prone, it may be masquerading as this linked switch issue.  It'll probably be a few days before I can, but I'll try to wipe my opam environment and start fresh to see if that helps.  Before I wipe out my current opam setup, is there anything I can capture from my environment which might be useful for you?

@AltGr Using an opam switch as a system switch was a happy accident from my perspective because it of the time it saves when setting up a new switch.  Thank you for clarifying that it isn't expected/intended behavior!

**Comment by dra27** [comment] 2021-07-13 15:35
Closing this, just as it's been lingering for two years - please re-open if it's still an issue / there's further feedback.

**Closed by dra27** 2021-07-13 15:35 UTC
