### ISSUE TITLE
Inaccurate dependencies solving

### ISSUE THREAD

**Issue by jpdeplaix** [ocaml/opam#2108] opened 2015-04-11 16:26 UTC
I recently updated opam from 1.2.0 to 1.2.1 (maybe it's unrelated but we never know) and I noticed a strange behavior when trying to get a package that is incompatible with another on already installed.
In my case I had llvm.3.6 installed and I wanted to upgrade my ctypes version to the newest on (0.4.1). But llvm.3.6 is not compatible with ctypes >= 0.4.
But the behavior of the solver is a bit strange. When I try to install it I got this:
```
$ opam install ctypes.0.4.1
The following actions will be performed:
  - downgrade llvm   3.6 to 3.2    
  - upgrade   ctypes 0.3.4 to 0.4.1
===== 1 to upgrade | 1 to downgrade =====
Do you want to continue ? [Y/n] n
```
It wants to downgrade llvm to 3.2 but this is not the greatest version available. The 3.5 is.

I've the latest version of aspcud installed (1.9.0).

**Comment by AltGr** [comment] 2015-04-13 03:37
That's a known quirk in the solver: it has criteria optimising the number of packages at their latest version, but there is no notion of _distance_ to this latest version: once the package can't be at its latest version, all versions have equal weight. It's actually non-obvious how to define such a distance when there are several packages involved (number of intermediate releases ? Age ?) -- but any metric would be helpful in your case, with a single package involved.

I believe there is research work being done on Cudf to improve on this -- cc @rdicosmo, @abate ;
Incidentally, it seems to me, experimentally, that the bias of aspcud, all things otherwise equal, is to the lowest version. I understand they may not want to implement an artificial bias -- the criteria are supposed to fill that role -- yet latest would be way better than oldest in general

Closing as duplicate of #1897

**Closed by AltGr** 2015-04-13 03:37 UTC

**Comment by AltGr** [comment] 2015-04-15 06:10
@rdicosmo's way seems to work, hurray!
```
% opam install ctypes.0.4.1 --show 
The following actions would be performed:
  ↘  downgrade llvm   3.6 to 3.5    
  ↗  upgrade   ctypes 0.3.4 to 0.4.1
===== ↗  1   ↘  1 =====
```

**Comment by rdicosmo** [comment] 2015-04-15 06:12
Great!

2015-04-15 8:10 GMT+02:00 Louis Gesbert <notifications@github.com>:

> @rdicosmo <https://github.com/rdicosmo>'s way seems to work, hurray!
>
> % opam install ctypes.0.4.1 --show
> The following actions would be performed:
>   ↘  downgrade llvm   3.6 to 3.5
>   ↗  upgrade   ctypes 0.3.4 to 0.4.1
> ===== ↗  1   ↘  1 =====
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ocaml/opam/issues/2108#issuecomment-93212756>.
>



-- 
Roberto Di Cosmo

------------------------------------------------------------------
Professeur               En delegation a l'INRIA
PPS                      E-mail: roberto@dicosmo.org
Universite Paris Diderot WWW  : http://www.dicosmo.org
Case 7014                Tel  : ++33-(0)1-57 27 92 20
5, Rue Thomas Mann
F-75205 Paris Cedex 13   Identica: http://identi.ca/rdicosmo
FRANCE.                  Twitter: http://twitter.com/rdicosmo
------------------------------------------------------------------
Attachments:
MIME accepted, Word deprecated
      http://www.gnu.org/philosophy/no-word-attachments.html
------------------------------------------------------------------
Office location:

Bureau 320 (3rd floor)
Batiment Sophie Germain
Avenue de France
Metro Bibliotheque Francois Mitterrand, ligne 14/RER C
-----------------------------------------------------------------
GPG fingerprint 2931 20CE 3A5A 5390 98EC 8BFC FCCA C3BE 39CB 12D3

**Comment by AltGr** [comment] 2015-04-15 06:13
(btw, I was wrong with the "lowest" bit, must be my pessimistic nature, it's really any version in the range)
