### ISSUE TITLE
Source bash completions

### ISSUE THREAD

**Issue by smimram** [ocaml/opam#3981] opened 2019-09-11 12:31 UTC
It would be nice if bash completion scripts installed under `/home/smimram/.opam/4.08.0/share/bash-completion/completions/` (or whichever current OCaml switch) could be sourced by the default shell script (`opam-init/init.sh`) so that we get completion for binaries installed with opam. If you want to test, I think that why3 has a completion file for instance, but it is not installed by the current opam script (the next release of Liquidsoap will also feature such a script).

**Comment by rjbou** [comment] 2019-11-14 14:36
It would be a nice feature to have, but the problem is that sourcing generated or included scripts is not so harmless.
Plus, to have the completion according the current switch, we should add it in the env hook, which is a quite heavy overloading, and needs a redesign of the hook/opam env.

**Comment by dra27** [comment] 2021-07-13 15:10
I'm not sure this is something we're likely to change, so I'm going to close this (please do re-open if you disagree!).

Merlin is a similar example with its `post-messages` instructions for configuring Vim and Emacs (see [merlin.4.2-412 in opam-repository](https://github.com/ocaml/opam-repository/blob/master/packages/merlin/merlin.4.2-412/opam#L29-L73) - although I don't know if that's overkill for the `why3` package.

**Closed by dra27** 2021-07-13 15:10 UTC
