### ISSUE TITLE
opam config env appears to blow away MANPATH

### ISSUE THREAD

**Issue by pmetzger** [ocaml/opam#3319] opened 2018-04-28 21:16 UTC
`opam config env` appears to completely replace the contents of the existing `MANPATH` variable instead of prepending the appropriate `.opam/something/man` directory. If the variable is already set, it should only prepend rather than throwing away the existing contents. Also, if the variable is empty, it should not place a `:` into the `MANPATH`.

**Comment by dra27** [comment] 2018-04-29 08:02
Which version of opam, please? Is this is a duplicate of #2870?

**Comment by pmetzger** [comment] 2018-04-29 14:39
```
$ opam --version
1.2.2
```

**Comment by AltGr** [comment] 2018-05-02 14:06
Looks indeed like #2870 ;

> Also, if the variable is empty, it should not place a `:` into the `MANPATH`.

precisely, on some (most?) systems, it should. On Debian systems, `man manpath` shows:

> If  $MANPATH  is set, manpath displays its value rather than determining it on the fly.  If $MANPATH is prefixed by a colon, then the value of the variable is appended to the list determined from the content of the configuration files.  If the colon comes at the end of the value in the variable, then the determined list is appended to the content of the variable.  If the value of the variable contains a double colon  (::),  then  the  determined list is inserted in the middle of the value, between the two colons.

But indeed, the same page on OSX reads:

> If MANPATH is set, man uses it as the path to search for manual page files.  It overrides the configuration file and the automatic search path, but is overridden by the -M invocation  option.

which seems consistent with the results we are seeing. In the latter case, however, the `manpath` command uses clever heuristics to find the correct manpages for utilities in the `PATH`, so no update from opam is needed!

Unfortunately, we don't have an operator "prepend/append only if variable is already set", and that would be a bit tedious to add right now (needs extending the parser, etc.), so the simpler solution seems to be not to set `MANPATH` on any BSD-likes. Still wonder about the original case for #2870, which was on Debian, though.

**Comment by pmetzger** [comment] 2018-05-02 14:34
Ah, I now understand the purpose of the `:` (which isn't the case on all systems, how irritating.) Regardless, it is probably the case that the command should not blow away an existing setting.

**Closed** 2018-05-02 15:15 UTC

**Comment by pmetzger** [comment] 2018-05-02 15:56
Is this being closed because it duplicates #2870?

**Comment by dra27** [comment] 2018-05-02 16:17
No - it's been fixed! Follow the link from the commit

**Comment by pmetzger** [comment] 2018-05-03 11:11
Ah, excellent!

**Comment by pmetzger** [comment] 2018-05-03 11:12
Hrm. Has it really been fixed? Yes, it will work for me on MacOS now, but on Linux what will it do?
