### ISSUE TITLE
Seemingly incorrect build dependency report

### ISSUE THREAD

**Issue by fxfactorial** [ocaml/opam#2492] opened 2016-03-29 16:35 UTC
opam doesn't seem to give the correct build dependency report as shown in this thread: https://github.com/diml/utop/issues/163

TL:DR opam is blaming utop for camlp4 when its really type_conv, especially odd since utop says that camlp4 is an optional dependency.

**Comment by AltGr** [comment] 2016-04-02 05:34
Added for context:

> ```
opam install starterkit
The following actions will be performed:
  ∗  install conf-m4             1             [required by ocamlfind]
  ∗  install conf-ncurses        1+system      [required by ocamlfind]
  ∗  install ocamlbuild          0             [required by starterkit]
  ∗  install conf-which          1             [required by camlp4, biniou]
  ∗  install ocamlfind           1.6.2         [required by starterkit]
  ∗  install cmdliner            0.9.8         [required by ocp-indent, ocp-index]
  ∗  install camlp4              4.02+7        [required by utop]
  ∗  install react               1.2.0         [required by lambda-term, utop]
  ∗  install ocamlmod            0.0.8         [required by oasis]
  ∗  install ocamlify            0.0.1         [required by oasis]
  ∗  install easy-format         1.2.0         [required by yojson]
  ∗  install cppo                1.3.1         [required by utop]
  ∗  install camomile            0.8.5         [required by zed]
  ∗  install base-bytes          base          [required by stringext]
  ∗  install type_conv           113.00.02     [required by ocaml-data-notation]
  ∗  install ocp-build           1.99.14-beta  [required by ocp-indent, ocp-index]
  ∗  install lwt                 2.4.5         [required by lambda-term, utop]
  ∗  install biniou              1.0.9         [required by yojson]
  ∗  install zed                 1.4           [required by lambda-term]
  ∗  install stringext           1.4.1         [required by starterkit]
  ∗  install re                  1.5.0         [required by ocp-index]
  ∗  install ocaml-data-notation 0.0.11        [required by oasis]
  ∗  install ocp-indent          1.5.2         [required by starterkit]
  ∗  install yojson              1.3.2         [required by merlin]
  ∗  install lambda-term         1.9           [required by starterkit]
  ∗  install oasis               0.4.5         [required by starterkit]
  ∗  install merlin              2.3.1         [required by starterkit]
  ∗  install utop                1.18.2        [required by starterkit]
  ∗  install ocp-index           1.1.4         [required by starterkit]
  ∗  install starterkit          1.0.0       
===== ∗  30 =====
```
> `  ∗  install camlp4              4.02+7        [required by utop]` is shown while utop _optionally_ depends on camlp4

Hm, indeed. The reasons in this list are indeed obtained through a heuristics, since the solver is actually a black-box. When there are several reasons available, opam only prints the one with the shortest path to what you asked for, in order not to be to verbose. The trouble, in this case, is that the heuristics is based on the graphs of the actions to be performed (since that's what we want printing to begin with), and that graph includes all optional dependencies, which are necessary for ordering the actions. On the other hand, the graph the solver uses ignores those.

This is fine for printing the reasons for `reinstall` actions; but in your case it is actually a bit misleading indeed. For better results, we would need to add a distinction for optional dependencies in the action graph, which would add quite some code complexity. Note that this would also be needed if we want to take different decision on failure based on that information, as proposed in #2450.

**Comment by AltGr** [comment] 2016-12-21 17:16
Duplicate of #1814

**Closed by AltGr** 2016-12-21 17:16 UTC
