### ISSUE TITLE
Intermittent failures in building ppx_monadic via opam in a fresh switch.

### ISSUE THREAD

**Issue by ilitzroth** [ocaml/opam#2802] opened 2016-12-29 12:55 UTC
```
12:36:50 #=== ERROR while installing ppx_monadic.1.0.4 =================================#
12:36:50 # opam-version         1.2.2
12:36:50 # os                   linux
12:36:50 # command              ocaml setup.ml -build
12:36:50 # path                 /home/jenkins/.opam/4.03.0+fp+flambda/build/ppx_monadic.1.0.4
12:36:50 # compiler             4.03.0+fp+flambda
12:36:50 # exit-code            1
12:36:50 # env-file             /home/jenkins/.opam/4.03.0+fp+flambda/build/ppx_monadic.1.0.4/ppx_monadic-2245-dcc6c5.env
12:36:50 # stdout-file          /home/jenkins/.opam/4.03.0+fp+flambda/build/ppx_monadic.1.0.4/ppx_monadic-2245-dcc6c5.out
12:36:50 # stderr-file          /home/jenkins/.opam/4.03.0+fp+flambda/build/ppx_monadic.1.0.4/ppx_monadic-2245-dcc6c5.err
12:36:50 ### stdout ###
12:36:50 # [...]
12:36:50 # - build ppx ppx_monadic.cmx
12:36:50 # + ocamlfind ocamlc -annot -bin-annot -package compiler-libs.common,ppx_tools.metaquot,ppxx -g -w A-3-4-9-40-42-44-45-48 -warn-error a -g -I . -c ppx_monadic.ml
12:36:50 # - build ppx ppx_monadic.cmx
12:36:50 # + ocamlfind ocamlopt -annot -bin-annot -package compiler-libs.common,ppx_tools.metaquot,ppxx -g -w A-3-4-9-40-42-44-45-48 -warn-error a -I . -c ppx_monadic.ml
12:36:50 # - build ppx ppx_monadic.run
12:36:50 # + ocamlfind ocamlc -package compiler-libs.common,ppx_tools.metaquot,ppxx -g -g -I . -o ppx_monadic.run monadic.cmo do_.cmo pattern_guard.cmo comprehension.cmo ppx_monadic.cmo -linkpkg
12:36:50 # - build ppx ppx_monadic.opt
12:36:50 # + ocamlfind ocamlopt -package compiler-libs.common,ppx_tools.metaquot,ppxx -g -I . -o ppx_monadic.opt monadic.cmx do_.cmx pattern_guard.cmx comprehension.cmx ppx_monadic.cmx -linkpkg
12:36:50 # *** omake: 57/85 targets are up to date
12:36:50 # *** omake: failed (1.16 sec, 6/6 scans, 9/22 rules, 41/77 digests)
12:36:50 ### stderr ###
12:36:50 # [...]
12:36:50 # findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /home/jenkins/.opam/4.03.0+fp+flambda/lib/ocaml, /home/jenkins/.opam/4.03.0+fp+flambda/lib/ocaml/compiler-libs
12:36:50 # findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /home/jenkins/.opam/4.03.0+fp+flambda/lib/ocaml, /home/jenkins/.opam/4.03.0+fp+flambda/lib/ocaml/compiler-libs
12:36:50 # File "_none_", line 1:
12:36:50 # Error: Files monadic.cmo
12:36:50 #        and /home/jenkins/.opam/4.03.0+fp+flambda/lib/ppxx/ppxx.cmo
12:36:50 #        make inconsistent assumptions over interface Ppxx
12:36:50 # *** omake: targets were not rebuilt because of errors:
12:36:50 #    ppx/ppx_monadic.run
12:36:50 #       depends on: ppx
12:36:50 # E: Failure("Command 'sh -c \"cp OMakeroot.in OMakeroot; omake PREFIX=/home/jenkins/.opam/4.03.0+fp+flambda\"' terminated with error code 2")
12:36:50 
```
This happens in a new switch with initially only findlib installed. Then the buildsystem tries
to install all the necessary packages for building the software (log attached). I see intermittent
build failures.
[faulty-build.txt](https://github.com/ocaml/opam/files/677097/faulty-build.txt)
[successfull-build.txt](https://github.com/ocaml/opam/files/677098/successfull-build.txt)

**Comment by AltGr** [comment] 2017-01-04 14:57
Probably a packaging error rather than an opam issue.

I first thought that could be a race condition due to a missing dependency, but the deps appear to be there, and in both logs, `ppx_tools` and `ppxx` are properly installed before the `ppx_monadic` build is started.

It would be interesting to see how a manual build fares on the switch state after the faulty build, to see if the problem is with a dependency or with the build of `ppx_monadic` itself.

**Comment by ilitzroth** [comment] 2017-01-04 22:51
That's a little tricky 'cause this is happening in a docker image. I'll see what I can do.

**Comment by avsm** [comment] 2017-01-19 11:47
@ilitzroth Could you post the Dockerfile?

**Comment by AltGr** [comment] 2017-09-25 14:13
Closing without further reports for 6 months. Please reopen if you have further information.

**Closed by AltGr** 2017-09-25 14:13 UTC
Labels: KIND: BUG, STATE: CAN'T REPRODUCE, STATE: NEED INVESTIGATION
