### ISSUE TITLE
Error on unmet dependencies is confusing

### ISSUE THREAD

**Issue by RalfJung** [ocaml/opam#3400] opened 2018-06-08 11:34 UTC
>   If your issue concerns a package not building, please report to
>   https://github.com/ocaml/opam-repository/issues or to the package maintainer
>   unless you are confident it is an issue in the opam tool itself.

I have an opam file with the following dependencies
```
depends: [
  "coq" { (>= "8.7.1" & < "8.9~") | (= "dev") }
  "coq-stdpp" { (= "2018-06-07.0.d070e44a") | (= "dev") }
]
```
Now I install that file. That will fail because neither of the two versions of `coq-stdpp` is available (there is a typo in there), so I get the following error:
```
The following dependencies couldn't be met:
  - coq-iris-builddep → coq-stdpp (= 2018-06-07.0.d070e44a & = dev)
      no matching version
```
This is really confusing, because it looks like the constraint `coq-stdpp (= 2018-06-07.0.d070e44a & = dev)` needs to be satisfied -- as in, `coq-stdpp` must have both versions at once! What actually happens is that for some reason, opam prints the `|` as `&`. Seems like a bug to me.

```
# opam config report
# opam-version      2.0.0~rc # but really rc2
# self-upgrade      no
# system            arch=x86_64 os=linux os-distribution=debian os-version=testing
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              8
# repositories      4 (http), 5 (local), 1 (version-controlled) (default repo at 61536b7f)
# pinned            1 (git), 1 (rsync)
# current-switch    /home/r/Dokumente/Unisachen/iris/coq
```

**Comment by AltGr** [comment] 2018-06-08 14:29
Duplicate of #2229. Unfortunately, this is very hard to fix :/
Thanks for reporting, closing as duplicate (#2229 obviously remains open and will have a link to here).

**Closed by AltGr** 2018-06-08 14:29 UTC

**Comment by AltGr** [comment] 2018-06-08 14:30
(maybe we could just pu commas in there, since in fact we don't really know the original logical connector at that point... at least that wouldn't be plain wrong...)
