### ISSUE TITLE
Override gcc path?

### ISSUE THREAD

**Issue by louisabraham** [ocaml/opam#3157] opened 2018-01-06 11:18 UTC
Hi,

I had the same problem like a lot of people here while compiling lablgtk on OSX:

    ld: '/System/Library/Frameworks//AudioToolbox.framework/Versions/A/AudioToolbox.tbd', unexpected token: !tapi-tbd-v2

The problem was that gcc does not support the tbd files (I think), and I used the real gcc installed by MacPorts.

I also found the solution by adding `PATH=/usr/bin:$PATH` before the opam command, thus reverting to the default /usr/bin/gcc that is in fact clang on OSX.

Is there a clean way to do so? (i.e. not `alias opam="PATH=/usr/bin:$PATH opam"`)

**Comment by AltGr** [comment] 2018-01-11 05:37
Not sure how opam could help with this in a generic (i.e. not package or OS specific) way ; it would probably be worth investigating lablgtk's build system ?

**Comment by AltGr** [comment] 2018-01-11 06:09
Closing as duplicate of #3017

**Closed by AltGr** 2018-01-11 06:09 UTC
