### ISSUE TITLE
error compiling opam 2.0.0-beta6

### ISSUE THREAD

**Issue by abate** [ocaml/opam#3180] opened 2018-01-18 14:51 UTC
while compiling opam 2.0.0-beta6

> make -j -C src_ext lib-ext

fails with the following error .

```
1.7.1.tar.gz has the expected MD5.
mkdir -p tmp-re
cd tmp-re && gunzip -c ../1.7.1.tar.gz | tar xf -
rm -rf re
patching file lib/re.ml
patching file lib/re_pcre.ml
patching file lib/re_str.ml
MD5 for 08050696fb701dafcd1372aadfaa800a50bc01ca.tar.gz differ:
  expected: 53b65232ebb5fd319acf90922342615d
    actual: e9a0844f767518a5358a8917531d983d
1.1+4.tar.gz has the expected MD5.
mkdir -p tmp-mccs
cd tmp-mccs && gunzip -c ../1.1+4.tar.gz | tar xf -
rm -rf mccs
MD5 for 08050696fb701dafcd1372aadfaa800a50bc01ca.tar.gz differ:
  expected: 53b65232ebb5fd319acf90922342615d
    actual: f48a70649b86c40ebb4c86ff0ce8a070
make[1]: Leaving directory '/home/opam/opam/src_ext'
make[1]: *** [Makefile:106: jbuilder.download] Error 1
make: *** [Makefile:47: lib-ext] Error 2
```

**Comment by dra27** [comment] 2018-01-18 14:59
I imagine that's been caused by the tarball being rebuilt owing the move from janestreet/jbuilder to ocaml/dune. Jbuilder beta17 is due out very soon...

**Comment by AltGr** [comment] 2018-01-19 15:17
Should be fixed. Thanks for reporting

**Closed by AltGr** 2018-01-19 15:17 UTC

**Comment by abate** [comment] 2018-01-20 15:03
I hope there is a new beta coming up soon including this patch . thanks !
