### ISSUE TITLE
ability to pin version ranges rather than strict versions

### ISSUE THREAD

**Issue by gasche** [ocaml/opam#1960] opened 2015-01-24 11:37 UTC
Would it be possible to `pin` the fact that, in a given switch, `coq` must remain in version `8.4.x` (that is `{>= "8.4"} {< "8.5"}`)?

**Comment by dsheets** [comment] 2015-01-27 17:03
Create a virtual package with those constraints and pin/add it?

**Comment by AltGr** [comment] 2015-01-28 00:55
Duplicate of #1351

Yes, that's how you could work-around it ;  pinning concerns a precise instance of a package so that would be difficult to support. On the other hand, there could be a way for advanced users to enforce a global formula on the installed packages ; need to find a correct interface for this (that wouldn't cause confusion when you forget about it) and would need some wiring, but wouldn't be too difficult and there might be a few uses for this. Something like a "root formula", saying in this case `[coq {>= "8.4 & < "8.5"}]`.

On the shorter term, creating a virtual empty package is still a bit too heavy. Allowing pinning packages without upstream could be interesting, in that case you'd write something like `opam pin add coq-version-constraint --no-upstream` and then set your constraint in the opam file that will be edited.

Note, however, that with the new handling of "base" packages defined in `.comp` files, you can define such a constraint there, and any coq version in this range will be chosen at switch creation time. Then the package won't change in the switch, unless you explicitely pin it.

**Comment by gasche** [comment] 2015-01-28 08:18
Thanks for your answer; an interesting question is whether upgrade works gracefully if/when we update the pin constraint. It looks like the direct pinning implementation may not be able to handle that very well, but most of your workaround would. At least pinning a virtual package would, iirc; what about `.comp` files handling of changes in the compiler description?

**Closed** 2016-02-12 05:21 UTC
Labels: duplicate, Feature Wish
