### ISSUE TITLE
opam2: fails to recompile package due to "not removing files that changed since"

### ISSUE THREAD

**Issue by ygrek** [ocaml/opam#3079] opened 2017-10-20 21:35 UTC
I don't have small repro at hand currently, here are the excerpts from the build log, maybe that rings a bell immediately : 
```
[#] opam upgrade
The following actions will be performed:
  - upgrade   pcre       7.3.0 to 7.3.3
  - recompile ocamlnet   4.1.4          [uses pcre]
...

[WARNING] While removing ocamlnet.4.1.4: not removing files that changed since:
            - lib/netstring-pcre/netstring_pcre.mli
            - lib/netstring-pcre/netstring_pcre.cmi
            - lib/netstring-pcre/netstring-pcre.p.cmxa
            - lib/netstring-pcre/netstring-pcre.p.a
            - lib/netstring-pcre/netstring-pcre.cmxa
            - lib/netstring-pcre/netstring-pcre.cma
            - lib/netstring-pcre/netstring-pcre.a
            - lib/netstring-pcre/META
 
[NOTE] While removing ocamlnet.4.1.4: not removing non-empty directories:
         - lib/netstring-pcre
 
-> removed   ocamlnet.4.1.4
-> removed   pcre.7.3.0
-> installed pcre.7.3.3
[ERROR] The installation of ocamlnet failed at "make install".
Processing 12/18: [ocamlnet: ocamlfind remove]
#=== ERROR while installing ocamlnet.4.1.4 ====================================#
# context      2.0.0~beta4 | linux/x86_64 | ocaml-base-compiler.4.05.0 | https://opam.ocaml.org/2.0#2017-10-20 20:08
# path         ~/.opam/4.05.0/.opam-switch/build/ocamlnet.4.1.4
# command      make install
# exit-code    2
# env-file     ~/.opam/log/ocamlnet-7470-57f057.env
# output-file  ~/.opam/log/ocamlnet-7470-57f057.out
### output ###
# [...]
# files=`../../tools/collect_files *.mli *.cmi *.cma *.cmxa *.a dll* META ` && \
# ocamlfind install netstring-pcre $files
# ocamlfind: Package netstring-pcre is already installed
#  - (file /home/user/.opam/4.05.0/lib/netstring-pcre/META already exists)
# ../../Makefile.rules:163: recipe for target 'install-findlib' failed
# make[2]: *** [install-findlib] Error 2
# make[2]: Leaving directory '/home/user/.opam/4.05.0/.opam-switch/build/ocamlnet.4.1.4/src/netstring-pcre'
# ../../Makefile.rules:148: recipe for target 'install' failed
# make[1]: *** [install] Error 2
# make[1]: Leaving directory '/home/user/.opam/4.05.0/.opam-switch/build/ocamlnet.4.1.4/src/netstring-pcre'
# Makefile:58: recipe for target 'install' failed
# make: *** [install] Error 2
```

**Comment by AltGr** [comment] 2017-11-20 13:56
Hmm, weird, I thought I had answered to this already. Nevermind, sorry for the lag!

opam's message means that the files have been updated since `ocamlnet` was installed: this might be due to a manual install, another package that modified the file, or clock or file timestamp issues. In any case, this step happens last, after all other `removal` operations (the same that opam 1.2 did) have taken place, so it's unlikely to be the cause of the error. I wish `ocamlfind` wouldn't fail because of "already installed" errors. In any case, you can:
- try `opam remove ocamlnet --force`, to re-run the uninstall script, and check if it's the part that is incomplete (in this case, this should be reported to be fixed in the upstream package definition)
- remove the directory `$(opam var prefix)/lib/netstring-pcre` by hand and retry

**Comment by ygrek** [comment] 2017-11-20 14:21
This happens in our CI, so I am almost sure there is no manual install and I am hoping no other package installs netstring-pcre. Also this happened for some other package, not only ocamlnet, since then. I will try to verify timestamps next time it happens, suspicious.

**Comment by AltGr** [comment] 2017-11-20 15:45
I think I could reproduce the cause (after disabling my binary cache) with
```
opam install pcre ocamlnet
opam reinstall pcre -vv
```

The removal does:
```
λ  compiled  pcre.7.2.3
+ /home/lg/.opam/4.03.0/bin/ocamlfind "remove" "equeue"
- Removed /home/lg/.opam/4.03.0/lib/equeue/META
- Removed /home/lg/.opam/4.03.0/lib/equeue
+ /home/lg/.opam/4.03.0/bin/ocamlfind "remove" "equeue-gtk2"
- Removed /home/lg/.opam/4.03.0/lib/equeue-gtk2/META
- Removed /home/lg/.opam/4.03.0/lib/equeue-gtk2
+ /home/lg/.opam/4.03.0/bin/ocamlfind "remove" "netcamlbox"
- Removed /home/lg/.opam/4.03.0/lib/netcamlbox/META
- Removed /home/lg/.opam/4.03.0/lib/netcamlbox
+ /home/lg/.opam/4.03.0/bin/ocamlfind "remove" "netcgi2"
- Removed /home/lg/.opam/4.03.0/lib/netcgi2/META
- Removed /home/lg/.opam/4.03.0/lib/netcgi2
+ /home/lg/.opam/4.03.0/bin/ocamlfind "remove" "netcgi2-plex"
- Removed /home/lg/.opam/4.03.0/lib/netcgi2-plex/META
- Removed /home/lg/.opam/4.03.0/lib/netcgi2-plex
+ /home/lg/.opam/4.03.0/bin/ocamlfind "remove" "netclient"
- Removed /home/lg/.opam/4.03.0/lib/netclient/META
- Removed /home/lg/.opam/4.03.0/lib/netclient
+ /home/lg/.opam/4.03.0/bin/ocamlfind "remove" "nethttpd"
- Removed /home/lg/.opam/4.03.0/lib/nethttpd/META
- Removed /home/lg/.opam/4.03.0/lib/nethttpd
+ /home/lg/.opam/4.03.0/bin/ocamlfind "remove" "netmulticore"
- Removed /home/lg/.opam/4.03.0/lib/netmulticore/META
- Removed /home/lg/.opam/4.03.0/lib/netmulticore
+ /home/lg/.opam/4.03.0/bin/ocamlfind "remove" "netplex"
- Removed /home/lg/.opam/4.03.0/lib/netplex/META
- Removed /home/lg/.opam/4.03.0/lib/netplex
+ /home/lg/.opam/4.03.0/bin/ocamlfind "remove" "netshm"
- Removed /home/lg/.opam/4.03.0/lib/netshm/META
- Removed /home/lg/.opam/4.03.0/lib/netshm
+ /home/lg/.opam/4.03.0/bin/ocamlfind "remove" "netstring"
- Removed /home/lg/.opam/4.03.0/lib/netstring/META
- Removed /home/lg/.opam/4.03.0/lib/stublibs/dllnetaccel_c.so
- Removed /home/lg/.opam/4.03.0/lib/stublibs/dllnetaccel_c.so.owner
- Removed /home/lg/.opam/4.03.0/lib/netstring
+ /home/lg/.opam/4.03.0/bin/ocamlfind "remove" "netsys"
- Removed /home/lg/.opam/4.03.0/lib/netsys/META
- Removed /home/lg/.opam/4.03.0/lib/stublibs/dllnetsys.so
- Removed /home/lg/.opam/4.03.0/lib/stublibs/dllnetsys.so.owner
- Removed /home/lg/.opam/4.03.0/lib/netsys
+ /home/lg/.opam/4.03.0/bin/ocamlfind "remove" "netunidata"
- Removed /home/lg/.opam/4.03.0/lib/netunidata/META
- Removed /home/lg/.opam/4.03.0/lib/netunidata
+ /home/lg/.opam/4.03.0/bin/ocamlfind "remove" "netzip"
- Removed /home/lg/.opam/4.03.0/lib/netzip/META
- Removed /home/lg/.opam/4.03.0/lib/netzip
+ /home/lg/.opam/4.03.0/bin/ocamlfind "remove" "pop"
- ocamlfind: [WARNING] No such file: /home/lg/.opam/4.03.0/lib/pop/META
+ /home/lg/.opam/4.03.0/bin/ocamlfind "remove" "rpc"
- Removed /home/lg/.opam/4.03.0/lib/rpc/META
- Removed /home/lg/.opam/4.03.0/lib/rpc
+ /home/lg/.opam/4.03.0/bin/ocamlfind "remove" "rpc-auth-local"
- Removed /home/lg/.opam/4.03.0/lib/rpc-auth-local/META
- Removed /home/lg/.opam/4.03.0/lib/stublibs/dllrpc_auth_local.so.owner
- Removed /home/lg/.opam/4.03.0/lib/stublibs/dllrpc_auth_local.so
- Removed /home/lg/.opam/4.03.0/lib/rpc-auth-local
+ /home/lg/.opam/4.03.0/bin/ocamlfind "remove" "rpc-generator"
- Removed /home/lg/.opam/4.03.0/lib/rpc-generator/META
- Removed /home/lg/.opam/4.03.0/lib/rpc-generator
+ /home/lg/.opam/4.03.0/bin/ocamlfind "remove" "shell"
- Removed /home/lg/.opam/4.03.0/lib/shell/META
- Removed /home/lg/.opam/4.03.0/lib/shell
+ /home/lg/.opam/4.03.0/bin/ocamlfind "remove" "smtp"
- ocamlfind: [WARNING] No such file: /home/lg/.opam/4.03.0/lib/smtp/META
```

I don't get the `not removing files that changed since:`, but as mentionned above, this isn't the cause (file tracking has my back by removing the remaining `netstring-pcre` files, and avoids the failure, though).

Notice that, in the above log, `netstring-pcre` isn't removed. `ocamlnet` has:
```
remove: [
  ...
  ["ocamlfind" "remove" "netstring"]
  ["ocamlfind" "remove" "netstring-pcre"] {"%{pcre:installed}%"}
  ...
]
```
it's a little weird to constrain the removals during the removal phase like this, but as long as `ocamlnet` has a dependency on `pcre`, opam guarantees that `pcre` remains unchanged as long as `ocamlnet` is installed (the order of actions confirms this invariant is respected). So the `remove netstring-pcre` should definitely be executed, while it seems it is not. This might be a bug in the variables defined during the evaluation of the `remove:` filters, I'll investigate further in that direction.

**Closed** 2017-11-23 08:21 UTC
