### ISSUE TITLE
Could not resolve host: ygrek.org.ua

### ISSUE THREAD

**Issue by kid-with-phone** [ocaml/opam#6156] opened 2024-08-14 20:11 UTC
I'm trying to install OCaml on Android; the command `~ $ opam init --comp=4.06.1+termux` fails with this error:

```
Could not resolve host: ygrek.org.ua

Fatal error:
# opam-version 1.2.2 (b62f698e8b7be3dba4f20bc95d377ddc403aee90)
# os           linux
# command      curl --write-out %{http_code}\n --insecure --retry 3 --retry-delay 2 -OL http://ygrek.org.ua/files/ocaml-4.06.1+termux.patch
# path         /data/data/com.termux/files/usr/tmp/opam-19593-c55002
# exit-code    6
# env-file     /data/data/com.termux/files/home/.opam/log/log-19593-b76d0e.env
# stdout-file  /data/data/com.termux/files/home/.opam/log/log-19593-b76d0e.out
# stderr-file  /data/data/com.termux/files/home/.opam/log/log-19593-b76d0e.err
```
It seems they moved from http://ygrek.org.ua to https://ygrek.org

```
# OPAM config report
# opam-version    1.2.2 (b62f698e8b7be3dba4f20bc95d377ddc403aee90)
# self-upgrade    no
# os              linux
# read-state      # opam-version    1.2.2 (b62f698e8b7be3dba4f20bc95d377ddc403aee90)
# os              linux
File /data/data/com.termux/files/home/.opam/config does not exist
```

**Comment by kit-ty-kate** [comment] 2024-08-15 11:05
You're using opam 1.2.2 from 2015 and which has been deprecated since 2018. The [repository](https://github.com/ocaml/opam-repository) (which is the cause of the error) is no longer updated for such an old version.
To install newer versions of opam please refer to https://opam.ocaml.org/doc/Install.html

If you have problems installing opam >= 2.0 (the latest version is 2.2.0) using the methods provided please feel free to open a new ticket and we'll do our best to help.

Closing this ticket as we can't do anything about it.

**Closed by kit-ty-kate** 2024-08-15 11:05 UTC

**Comment by kid-with-phone** [comment] 2024-08-15 11:27
Thank you, the opam installation failed when I tried that command before, but it does when I download it manually
