### ISSUE TITLE
Handle missing cwd during reinstallation

### ISSUE THREAD

**Issue by dsheets** [ocaml/opam#2435] opened 2016-02-15 14:43 UTC
In the build directory for `lwt` during the reinstallation:

```
lwt.2.5.1 dsheets$ opam reinstall lwt --keep-build-dir
The following actions will be performed:
  ↻  recompile lwt         2.5.1
  ↻  recompile redis       0.2.3              [uses lwt]
  ↻  recompile lambda-term 1.9                [uses lwt]
  ↻  recompile cstruct     1.8.0              [uses lwt]
  ↻  recompile camltc      0.9.2              [uses lwt]
  ↻  recompile conduit     0.10.0             [uses lwt]
  ↻  recompile cohttp      0.19.3             [uses lwt]
  ↻  recompile github      1.0.0              [uses lwt]
===== ↻  8 =====
Do you want to continue ? [Y/n] y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
⊘  removed   camltc.0.9.2
⊘  removed   redis.0.2.3
⊘  removed   github.1.0.0
⊘  removed   cohttp.0.19.3
⊘  removed   lambda-term.1.9
⊘  removed   conduit.0.10.0
⊘  removed   cstruct.1.8.0
⊘  removed   lwt.2.5.1
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory

#=== ERROR while installing lwt.2.5.1 =========================================#
Sys_error("No such file or directory")
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory


=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
The following actions were aborted
  ∗  install camltc      0.9.2
  ∗  install cohttp      0.19.3
  ∗  install conduit     0.10.0
  ∗  install cstruct     1.8.0
  ∗  install github      1.0.0
  ∗  install lambda-term 1.9
  ∗  install redis       0.2.3
The following actions failed
  ∗  install lwt 2.5.1
The following changes have been performed
  ⊘  remove camltc      0.9.2
  ⊘  remove cohttp      0.19.3
  ⊘  remove conduit     0.10.0
  ⊘  remove cstruct     1.8.0
  ⊘  remove github      1.0.0
  ⊘  remove lambda-term 1.9
  ⊘  remove lwt         2.5.1
  ⊘  remove redis       0.2.3

The former state can be restored with:
    opam switch import "~/.opam/system/backup/state-20160115143753.export"
```

At the least, I'd expect the command to fail early without mutating my opam state.

**Comment by OCamlPro-Henry** [comment] 2016-02-22 14:57
Which version of `opam` are you using ? I'm not able to reproduce with `master`, nor `branch-1.2`.

**Comment by dsheets** [comment] 2016-02-22 15:50
I can reproduce this in master. Is your cwd the build directory when you ask for a reinstall?

**Comment by dsheets** [comment] 2016-02-22 16:06
Even when not reinstalling but with a non-existent cwd:

```
~ $ mkdir foo
~ $ cd foo
~/foo $ rmdir ~/foo
ash: getcwd: No such file or directory
(unknown) $ opam switch
Fatal error:
Sys_error("No such file or directory")
ash: getcwd: No such file or directory
```

**Comment by OCamlPro-Henry** [comment] 2016-02-22 16:10
Yes, I was also able to produce the last one. For some reasons, I was mixing the two bugs. I'm now investigating.

**Comment by AltGr** [comment] 2016-08-31 11:35
Now fixed. Thanks!

**Closed by AltGr** 2016-08-31 11:35 UTC
Labels: KIND: BUG
