### ISSUE TITLE
opam 2 gets into a state where num is installed but not found by ocamlfind

### ISSUE THREAD

**Issue by RalfJung** [ocaml/opam#3355] opened 2018-05-15 20:01 UTC
This log kind of says it all:
```
$ opam reinstall num -vv
+ /usr/bin/ocamlc "-vnum"
- 4.05.0
The following actions will be performed:
  ↻  recompile num 0 

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
⊘  removed   num.0
∗  installed num.0
Done.
$ ocamlfind query num
ocamlfind: Package `num' not found
```
This has already happened with another switch some time ago, at which point I just deleted that switch and created a new one. But now that a second switch is affected, I figured I should report this somewhere. No idea whether this is a problem in opam or the repository.

This is in a system switch.
```
# opam config report
# opam-version      2.0.0~rc 
# self-upgrade      no
# system            arch=x86_64 os=linux os-distribution=debian os-version=testing
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              8
# repositories      4 (http), 5 (local), 1 (version-controlled) (default repo at 0ff199b1)
# pinned            1 (git), 3 (rsync), 1 (version)
# current-switch    coq-rust
```

**Comment by dra27** [comment] 2018-05-15 21:12
This is really [opam-repository](https://github.com/ocaml/opam-repository) issue, rather than an opam one. Which version of the ocamlfind package is installed?

I think you're seeing this https://github.com/ocaml/opam-repository/issues/10925 and I thought that the fix was the `ocamlfind-1.7.3-1` package.

**Comment by RalfJung** [comment] 2018-05-16 07:32
List of installed packages:
```
# Packages matching: installed
# Name        # Installed # Synopsis
base-bigarray base        Bigarray library distributed with the OCaml compiler
base-num      base        Num library distributed with the OCaml compiler
base-threads  base        Threads library distributed with the OCaml compiler
base-unix     base        Unix library distributed with the OCaml compiler
camlp5        7.05        Preprocessor-pretty-printer of OCaml
conf-m4       1           Virtual package relying on m4
num           0           The Num library for arbitrary-precision integer and rational arithmetic
ocaml         4.05.0      The OCaml compiler (virtual package)
ocaml-system  4.05.0      The OCaml compiler (system version, from outside of opam)
ocamlfind     1.8.0       A library manager for OCaml
```

I can re.report this over at opam-repository if you want. However, the strange fact is that re-installing all the same versions of the same packages in a new switch fixes the issue.

**Comment by RalfJung** [comment] 2018-05-16 07:43
Still, looking at that issue I tried `opam install ocamlfind.1.7.3` and that fixed the problem. So this seems to be a regression in ocamlfind 1.8.0? However, I have other switches (with the same system compiler) where ocamlfind 1.8.0 works just fine.

**Comment by dra27** [comment] 2018-05-16 08:47
ocamlfind's version can be determined from `ocamlfind query findlib -format '%v'` (or just looking for findlib in the output of `ocamlfind list`).

I'm just trying to reproduce this locally...

**Comment by dra27** [comment] 2018-05-16 09:10
OK, I think I've diagnosed the problem: if I install `num` in a switch with ocaml-base-compiler >= 4.06.0 and then switch back to a system switch **but don't run eval $(opam env)`** and then reinstall ocamlfind then ocamlfind doesn't install its num package.

I'm not able to trigger this based on `num.0`, which doesn't surprise me, because that package doesn't do anything.

Does that sound right to you?

**Comment by dra27** [comment] 2018-05-16 09:10
Once in this broken state, all I seemed to need to do was ensure I'd run `eval $(opam env)` and then run `opam reinstall ocamlfind`

**Comment by dra27** [comment] 2018-05-16 09:31
Oh no, this has nothing to do with two switches. It's entirely to do with reinstalling ocamlfind.

```
dra@bionic:~$ opam switch create demo ocaml-system

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
∗ installed base-bigarray.base
∗ installed base-threads.base
∗ installed base-unix.base
∗ installed ocaml-system.4.05.0
∗ installed ocaml.4.05.0
Done.
# Run eval $(opam env) to update the current shell environment
dra@bionic:~$ eval $(opam env)
dra@bionic:~$ opam install ocamlfind --yes
The following actions will be performed:
  ∗ install conf-m4   1     [required by ocamlfind]
  ∗ install ocamlfind 1.8.0 
===== ∗ 2 =====

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ocamlfind.1.8.0] found in cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
∗ installed conf-m4.1
∗ installed ocamlfind.1.8.0
Done.
dra@bionic:~$ ocamlfind query num
/home/dra/.opam/demo/lib/num
dra@bionic:~$ opam reinstall ocamlfind
The following actions will be performed:
  ↻ recompile ocamlfind 1.8.0 

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ocamlfind.1.8.0] found in cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
⊘ removed   ocamlfind.1.8.0
∗ installed ocamlfind.1.8.0
Done.
dra@bionic:~$ ocamlfind query num
ocamlfind: Package `num' not found
dra@bionic:~$ opam reinstall ocamlfind
The following actions will be performed:
  ↻ recompile ocamlfind 1.8.0 

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ocamlfind.1.8.0] found in cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
⊘ removed   ocamlfind.1.8.0
∗ installed ocamlfind.1.8.0
Done.
dra@bionic:~$ ocamlfind query num
/home/dra/.opam/demo/lib/num
```

Switching this to opam-repository, as this is definitely a packaging problem - this issue can be closed.

**Comment by AltGr** [comment] 2018-05-16 09:36
Transferred to https://github.com/ocaml/opam-repository/issues/10925
Basically, I think `make install; make clean; ./configure; make; make install` from `ocamlfind` is broken because its own installation affects the results of `./configure`. Untested, though.

**Closed by AltGr** 2018-05-16 09:36 UTC
