### ISSUE TITLE
solver error when running `opam upgrade <package>`

### ISSUE THREAD

**Issue by c-cube** [ocaml/opam#2967] opened 2017-06-15 13:06 UTC
On arch with aspcud 1.9.1-1, opam 1.2.2, switch 4.04.0+flambda, when I try to `opam upg qcheck`  (which is pinned to a local git repo), I get the following error.

```
$ opam upg qcheck --verbose
=-=- Synchronising pinned packages =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[qcheck] /home/simon/workspace/qcheck#HEAD already up-to-date
[WARNING] External solver failed with inconsistent return value. Request saved to "/home/simon/.opam/log/solver-error-8801-1.cudf"
[ERROR] External solver failure, please fix your installation and check /home/simon/.opam/config and variable $OPAMEXTERNALSOLVER.
        You may also retry with option --use-internal-solver
```

[compressed error message](https://github.com/ocaml/opam/files/1077690/err.zip)

**Comment by AltGr** [comment] 2017-06-15 15:01
Seems to be a duplicate of #2203; not much we can do about it, but see the fix there, or try a [different solver](http://opam.ocaml.org/doc/Install.html#ExternalSolvers)

**Closed by AltGr** 2017-06-15 15:01 UTC
Labels: STATE: DUPLICATE

**Comment by oblitum** [comment] 2017-08-25 20:33
I had to install `pacman -S gringo` to have a working solver, otherwise I'd get:

```
### stderr ###
# error: executing gringo failed (No such file or directory)
# error: gringo returned with non-zero exit status

[ERROR] External solver failure, please fix your installation and check
        /home/francisco/.opam/config and variable $OPAMEXTERNALSOLVER.
        You may also retry with option --use-internal-solver
```

I've just removed `~/.opam`, installed `gringo` besides `opam`, and all the rest.
