### ISSUE TITLE
Windows, URL paths and Filename

### ISSUE THREAD

**Issue by thranur** [ocaml/opam#2293] opened 2015-08-19 12:52 UTC
Feature request: in case "native" Windows support (using MinGW instead of Cygwin) is still a future target, I'd like to suggest taking a look at the code which generates URLs for the `curl` command.

That code seems to reuse `Filename` operations such as `concat` and `dir_sep` to create URLs, which leads to a command trying to download `https://opam.ocaml.org\urls.txt` (note the backslash before "urls.txt") when running `opam init`.

From a quick glance at the code, I couldn't determine if there is a simple fix, or if there is a systematic reuse of such code which would require more extensive rewriting. In any case, fixing it would be useful if Windows will be supported in the future. Otherwise, not worth bothering.

**Comment by thranur** [comment] 2015-08-20 15:21
Well, I managed to patch the `OpamFilename.download_as` function in a extremely hackish way to convert `\` to `/`, but then curl failed with another error message.

Any way, following the large Windows-related thread, I went to the wg-windows archives and tried to get some information about what's going on, but they are much less pleasant to read (and Google) than a Github thread.

Could you please just quickly sum up whether Windows issues are still relevant to be reported here, and if so, should they be Cygwin-specific (as in, only for an OCaml with `Sys.os_type = "Cygwin"`), Win32-specific, or both?

**Comment by dbuenzli** [comment] 2015-08-20 15:35
Duplicate of #2188

**Closed** 2015-08-20 15:50 UTC
