### ISSUE TITLE
Show error message if necessary env variables aren't set

### ISSUE THREAD

**Issue by nikgraf** [ocaml/opam#3440] opened 2018-07-07 08:17 UTC
I was struggling with my first time experience with OPAM yesterday (https://github.com/ocaml/dune/issues/961). I'm curious if you would be interested in an addition to check for the existence of required env variables when when running OPAM. In case they are not present a nice error message could be printed hinting to run `opam env`

I'm happy to contribute a PR if we can agree on a feature spec.

**Comment by nikgraf** [comment] 2018-07-07 14:21
@dra27 I'm a complete beginner with OPAM and I yet didn't even got to a point where I would use `opam switch`.

I was following the website instructions and my story was the following:

```
brew install opam
opam init
opam install cmdliner # <- fails
opam install opium # <- fails
```

I understand that OPAM is not too much concerned with these env variables. Happy to open an issue in Dune/Jbuilder if it makes more sense there.

Makes sense that it doesn't matter too much to OPAM. Personally I care about the overall beginner experience. I'm thinking of something like this:

If the env variables `OPAM_SWITCH_PREFIX`, `CAML_LD_LIBRARY_PATH`, `OCAML_TOPLEVEL_PATH` are not set show a warning on the command `opam install <something>`. The warning could look like this:
```
[WARNING] The required environment variables are not set.
    Please run this command to set them: eval $(opam env)
```

Does it make sense for OPAM to add it here or is it better to open an issue in Dune/Jbuilder?

**Comment by dra27** [comment] 2018-07-07 14:36
No, the issue is definitely fine here with opam, I just meant that it’s not opam itself which is meant to need those set, it’s simply helping set them up for your shell. My example shows that when if you’ve left the shell set up for 4.01.0 switch, you can install successfully to a 4.06.1 switch, even though the environment’s wrong. 

There is a warning displayed at the end of `opam install` in opam 2 (see above - I’m struggling to copy it from my phone).

I definitely hear you where the first time experience is concerned - that’s part of what I was trying to look into, as my transcripts don’t seem to reproduce the failure you saw. I’ll try next week when I have access to a Mac.

**Comment by nikgraf** [comment] 2018-07-07 15:09
Great, let me know in case you can't reproduce it. Happy to make a recording.

**Comment by avsm** [comment] 2018-07-07 17:57
I wonder if the bug that @nikgraf saw was actually the [OCaml 4.05/opam 1.2.2 execvpe issue](https://discuss.ocaml.org/t/jbuilder-fails-to-build/802/18).  That would have caused the `opam install` to fail.

**Comment by dra27** [comment] 2018-07-07 21:11
Is it possible to tell from brew which version of OCaml compiled the opam “bottle” (as I assume opam isn’t built from source?)

**Comment by rjbou** [comment] 2019-06-27 14:42
Closing this issues, feel free to reopen it if needed.
Thanks!

**Closed by rjbou** 2019-06-27 14:42 UTC
