### ISSUE TITLE
When there is a package conflict, state where the dependencies come from

### ISSUE THREAD

**Issue by RalfJung** [ocaml/opam#5243] opened 2022-08-12 19:31 UTC
I am trying to figure out why opam fails saying
```
[ERROR] Package conflict!
  * Missing dependency:
    - coq-stdpp (>= 2022-08-12.3.d6c6e66a & < dev.2017-11-12.2)
    no matching version
```
Sadly this is on CI, so I have no way to directly interact with that state. And the message makes no sense, no package involved should have a constraint that says `< dev.2017-11-12.2`. It would help enormously if opam could say why it thinks that there is a `< dev.2017-11-12.2` constraint; as-is, these error messages are not very useful.

```
# opam config report
# opam-version         2.1.1 
# self-upgrade         no
# system               arch=x86_64 os=linux os-distribution=debian os-version=10
# solver               builtin-mccs+glpk
# install-criteria     -removed,-count[avoid-version,changed],-count[version-lag,request],-count[version-lag,changed],-count[missing-depexts,changed],-changed
# upgrade-criteria     -removed,-count[avoid-version,changed],-count[version-lag,solution],-count[missing-depexts,changed],-new
# jobs                 20
# repositories         2 (http), 1 (version-controlled) (default repo at 3927b22a)
# pinned               4 (rsync), 2 (version)
# current-switch       default
# ocaml:native         true
# ocaml:native-tools   true
# ocaml:native-dynlink true
# ocaml:stubsdir       /builds/iris/iris/_opam/default/lib/ocaml/stublibs:/builds/iris/iris/_opam/default/lib/ocaml
# ocaml:preinstalled   false
# ocaml:compiler       4.07.1
<><> Repository configuration for switch default ><><><><><><><><><><><><><><><>
[NOTE] These are the repositories in use by the current switch. Use '--all' to see all configured repositories.
 1 iris-dev     git+https://gitlab.mpi-sws.org/iris/opam.git
 2 coq-released https://coq.inria.fr/opam/released
 3 default      https://opam.ocaml.org/
```

**Comment by RalfJung** [comment] 2022-08-12 19:46
In this case it turns out the issue was a `= 2022-08-12.3.d6c6e66a` should have been `= dev.2022-08-12.3.d6c6e66a`. That still does not satisfy the `< dev.2017-11-12.2` constraint, but that constraint does not really exist, so then things went fine.

**Comment by kit-ty-kate** [comment] 2022-08-12 22:42
This is a duplicate of #4373. Could you add your comment there with:
* the available repositories hashes
* the switch invariant
* the list of pinned packages
* the current system
* the command showing the conflict message

and close this issue?

**Comment by RalfJung** [comment] 2022-08-13 18:10
Uh, no idea how to get all that information, sorry.

- The available repositories are listed above.
- The switch invariant is whatever you get from creating a switch with `ocaml-variants.4.14.0+options ocaml-option-flambda`
- "current system", no idea what you mean by that, I gave the `opam config report` above
- the command is [this line in our CI scripts](https://gitlab.mpi-sws.org/iris/ci/-/blob/d0c65f83e532b3d85e58ee9a142781a70828c90c/prepare-opam.sh#L113)

You can see the full CI logs [here](https://gitlab.mpi-sws.org/iris/iris/-/jobs/203233).

I also now remember that `&` in these messages often means "or" (completely defying the meaning of that symbol basically everywhere else, including in opam's own syntax), so that is probably part of the problem here.

**Closed** 2024-11-18 13:49 UTC
Labels: CONSIDER CLOSING
