### ISSUE TITLE
[ERROR] Could not update repository "default": OpamDownload.Download_fail Curl failed

### ISSUE THREAD

**Issue by winds365** [ocaml/opam#6162] opened 2024-08-18 06:28 UTC
<><> Fetching repository information ><><><><><><><><><><><><><><><><><><><>  🐫
02:44.937  PARALLEL               Iterate over 1 task(s) with 3 process(es)
02:44.937  PARALLEL               Starting job 0 (worker 1/3): 0
02:44.937  REPOSITORY             update default from https://opam.ocaml.org
02:44.937  CURL                   pull-repo-update
02:44.938  SYSTEM                 mkdir C:\Users\winds\AppData\Local\opam\repo\default.new
02:44.939  SYSTEM                 mkdir C:\Users\winds\AppData\Local\Temp\opam-15492-bb96f1
02:44.940  PARALLEL               Next task in job 0: C:\WINDOWS\system32\curl.exe --write-out %{http_code}\n --retry 3 --retry-delay 2 --user-agent opam/2.2.0 -L -o C:\Users\winds\AppData\Local\Temp\opam-15492-bb96f1\index.tar.gz.part -- https://opam.ocaml.org/index.tar.gz
Processing  1/1: [default: http]
+ C:\WINDOWS\system32\curl.exe "--write-out" "%{http_code}\\n" "--retry" "3" "--retry-delay" "2" "--user-agent" "opam/2.2.0" "-L" "-o" "C:\\Users\\winds\\AppData\\Local\\Temp\\opam-15492-bb96f1\\index.tar.gz.part" "--" "https://opam.ocaml.org/index.tar.gz"
- 000
-   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
-                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
- curl: (43) A libcurl function was given a bad argument
02:45.529  PARALLEL               Collected task for job 0 (ret:43)
02:45.529  SYSTEM                 rm C:\Users\winds\AppData\Local\Temp\opam-winds-15492\dl-15492-be8644
02:45.529  CURL                   Could not download file at https://opam.ocaml.org/index.tar.gz.
02:45.529  SYSTEM                 rmdir C:\Users\winds\AppData\Local\Temp\opam-15492-bb96f1
02:45.530  SYSTEM                 rmdir C:\Users\winds\AppData\Local\opam\repo\default.new
[ERROR] Could not update repository "default": OpamDownload.Download_fail(_, "Curl failed:
        \"C:\\\\WINDOWS\\\\system32\\\\curl.exe --write-out %{http_code}\\\\n --retry 3 --retry-delay 2 --user-agent
        opam/2.2.0 -L -o C:\\\\Users\\\\winds\\\\AppData\\\\Local\\\\Temp\\\\opam-15492-bb96f1\\\\index.tar.gz.part --
        https://opam.ocaml.org/index.tar.gz\" exited with code 43")
02:45.530  PARALLEL               Job 0 finished
02:45.530  SYSTEM                 rmdir C:\Users\winds\AppData\Local\opam
[ERROR] Initial download of repository failed.
'opam init -vvv --debug-level=3' failed.

C:\Users\winds>curl -V
curl 8.8.0 (Windows) libcurl/8.8.0 Schannel zlib/1.3 WinIDN
Release-Date: 2024-05-22
Protocols: dict file ftp ftps http https imap imaps ipfs ipns mqtt pop3 pop3s smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS HSTS HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM SPNEGO SSL SSPI threadsafe Unicode UnixSockets

**Comment by winds365** [comment] 2024-08-18 06:30
Windows version 22631.4037

**Comment by elazarg** [comment] 2024-08-18 16:51
See #6120

**Comment by kit-ty-kate** [comment] 2024-08-19 11:20
As mentioned in https://github.com/ocaml/opam/pull/6142#issuecomment-2274404820 the issue is that Windows 11 currently ships with a broken curl binary and doesn't work for opam at all. You can fix that by either installing a newer version of curl (8.9.0 fixes the issue) manually or removing your opam root and calling:
```
opam init --cygwin-internal-install --cygwin-extra-packages=curl
```

I'll close this since it's a duplicate of https://github.com/ocaml/opam/issues/6120 but if you still have issues with those fixes feel free to add a comment on that issue. Thanks for the report!

**Closed by kit-ty-kate** 2024-08-19 11:20 UTC
