### ISSUE TITLE
got a `Not_found` under certain conditions

### ISSUE THREAD

**Issue by c-cube** [ocaml/opam#3153] opened 2018-01-03 10:24 UTC
```
% opam --version
2.0.0~beta6

% OCAMLRUNPARAM=b opam upg 
Fatal error:
Not_found
Backtrace:
  Raised at file "string.ml", line 118, characters 19-34
  Called from file "src/core/opamStd.ml", line 400, characters
  16-32
  Re-raised at file "src/state/opamSwitchState.ml", line 796,
  characters 4-11
  Called from file "src/state/opamRepositoryState.ml", line
  265, characters 14-18
  Re-raised at file "src/state/opamRepositoryState.ml", line
  266, characters 32-39
  Called from file "src/state/opamGlobalState.ml", line 149,
  characters 14-18
  Re-raised at file "src/state/opamGlobalState.ml", line 150,
  characters 32-39
  Called from file "src_ext/cmdliner/src/cmdliner_term.ml",
  line 27, characters 19-24
  Called from file "src_ext/cmdliner/src/cmdliner.ml", line
  27, characters 27-34
  Called from file "src_ext/cmdliner/src/cmdliner.ml", line
  106, characters 32-39
  Called from file "src_ext/cmdliner/src/cmdliner.ml", line
  136, characters 18-36
  Called from file "src_ext/cmdliner/src/cmdliner.ml", line
  251, characters 22-48
  Called from file "src/client/opamMain.ml" (inlined), line
  145, characters 8-66
  Called from file "src/client/opamMain.ml", line 147,
  characters 10-17
```

**Comment by AltGr** [comment] 2018-01-09 08:39
Thanks for reporting, but... well "certain conditions" is pretty vague :D

Unfortunately, the backtraces we can get at the moment are useless because opam's tidying up wrappers destroy them. We finally do have the `Printexc.reraise_raw_backtrace` that I had been begging for for some time in 4.05.0, so I could improve on the situation though (with the added burden of a compatibility layer)

In the meantime, the hack that I use is to set `OPAMKEEPLOGS=1`, which will skip the wrappers so that we get usable backtraces. Could you try that if you can still reproduce ?

**Comment by c-cube** [comment] 2018-01-09 12:26
Next time it happens (I can't predict when) I will send the logs. Sorry about the vague conditions but I don't know either, it comes and goes with updates.

**Comment by AltGr** [comment] 2018-01-11 07:28
Thanks!

**Comment by AltGr** [comment] 2018-03-28 09:16
Closing for now, but please reopen as soon as you have something. Hopefully it has since been fixed.

**Closed by AltGr** 2018-03-28 09:16 UTC
