### ISSUE TITLE
filter to list the packages in a repository

### ISSUE THREAD

**Issue by samoht** [ocaml/opam#2094] opened 2015-04-01 17:03 UTC
Would be nice to have something like `opam list --repository=<name>`

**Comment by AltGr** [comment] 2015-04-02 00:29
Indeed! Would it list:
- the packages that are currently available from the given repository (i.e. non overriden by another, higher-priority repo) -- that should be fairly straight-forward ?
- all the packages from that repository -- that would by a bit more expensive in the current setting ?

Not sure which of the two makes most sense

**Comment by dbuenzli** [comment] 2015-04-02 00:47
It seems to me that the most consistent with current's `list` behaviour would be: 

> the packages that are currently available from the given repository (i.e. non overriden by another, higher-priority repo) -- that should be fairly straight-forward ?

```opam list --repo=REPO```

> all the packages from that repository -- that would by a bit more expensive in the current setting ?

```opam list --repo=REPO --all```

**Comment by AltGr** [comment] 2015-04-02 01:02
Hm, makes sense, but the `--all` argument is already taken to mean "all available packages" (the default -- without package argument -- is to list installed packages).

**Comment by dbuenzli** [comment] 2015-04-02 01:08
> Hm, makes sense, but the --all argument is already taken to mean "all available packages" (the default -- without package argument -- is to list installed packages).

Ah I'm missing something (available vs something else). The only thing I say is that `list` with `--repo=NAME` should act like `list` except that only packages that come from repository `NAME` should be mentioned in the output.

**Comment by dbuenzli** [comment] 2015-04-02 01:10
Also, ```--repo``` should be a [repeatable](http://erratique.ch/software/cmdliner/doc/Cmdliner.Arg.html#VALopt_all) argument.

**Comment by AltGr** [comment] 2015-04-02 02:14
Duplicate of #1312 (thanks @drup for pointing this out!)

**Comment by Drup** [comment] 2015-04-02 02:15
For some reasons, it feels much older than one year old. :D

**Comment by AltGr** [comment] 2016-12-20 08:43
This has been implemented

**Closed by AltGr** 2016-12-20 08:43 UTC
Labels: AREA: UI, KIND: FEATURE WISH
