### ISSUE TITLE
Next: opam compiler-conf doesn't work anymore

### ISSUE THREAD

**Issue by Drup** [ocaml/opam#2531] opened 2016-04-25 18:33 UTC
[opam-compiler-conf](https://github.com/gasche/opam-compiler-conf) works by creating a compiler in `~/.opam/compilers/`. It doesn't work with opam 2.0, since compilers are packages now. My initial tentative was to put the compiler in `~/.opam/packages/ocaml/`, like in the `next` branch of opam-repository, but it doesn't work either. What should I do ?

cc @gasche

**Comment by Drup** [comment] 2016-04-25 19:01
My current version of the script is here: https://github.com/gasche/opam-compiler-conf/pull/9

**Comment by Drup** [comment] 2016-04-25 19:26
For some reason, I didn't think of actually using the new awesomeness of opam 2.0

```
% eval `opam config env --switch 4.03.0+trunk`
% opam pin add ocaml source/ocaml
```

It works, I feel like I did some magic. :D 
However, it doesn't completely replace the use case of `compiler-conf`, since it will force me to recompile the compiler a bit too much. `compiler-conf` covers that better.

**Comment by gasche** [comment] 2016-04-25 21:00
The essential part of `compiler-conf`, I think, is avoiding rebuilding the compiler when you want opam to install it. This is done by generating a description whose building step is only `install`; before 2.0 it was a switch description, with compiler-as-packages it should just be a package description. I think your pull request draft is going the right way.

**Comment by Drup** [comment] 2016-04-25 21:35
@gasche I agree. I'll wait for @AltGr to provides more insight, as it still doesn't work when emitting a package, and I don't really understand why.

**Comment by AltGr** [comment] 2016-05-04 04:15
I confirm that this seems right. Pinning, however, will overwrite the `url` field, so you could actually remove it from the `opam` file, and run
```
% opam switch ocaml-mydev --empty
% opam pin add file://$PWD
```

Not sure, but maybe even doing this without `compiler-conf`, but with `--edit` on the second step and then just clearing the `build:` field might do the trick.
The other option would be to add the package def to a local repo (with the url definition), e.g. ocaml.4.03.0+local, and then install it, but why bother anymore ? ;)

@gasche newer opam makes sure not to do any tricks to guess the kind of a pinning url when it's from a file (as opposed to when it comes from the command line)

**Comment by gasche** [comment] 2016-05-04 12:01
The ocaml compiler still needs to know at build-time where it will be installed, so I think having a `compiler-script` around the (substantially simplified) installation procedure make sense: guess the switch name from source-control information, guess the install path from the switch name, and run `./configure` accordingly.

Of course we should have information widely available on how to do these things without the script, now that they are simpler and that experts that may want different workflows can do it easily.

@Drup, are you still on board for adapting `compiler-conf` to the new style?

(I wonder whether the script should condition itself on the opam version at runtime, or whether we should instead play with dependency information. I rather like the fact that so far just copying the `.sh` somewhere and running it works, so if we can keep several-versions-logic in the same script that would be nice.)

**Comment by Drup** [comment] 2016-05-04 23:20
@gasche Yes, when time allows. Even if the instructions are very simple, (and indeed, @AltGr's instructions are the one I ended up doing myself), having a script to do them is useful. I really don't think I'll try to make the script portable across opam versions, though.

**Comment by Drup** [comment] 2016-05-06 16:31
> Not sure, but maybe even doing this without compiler-conf, but with --edit on the second step and then just clearing the build: field might do the trick.

It doesn't, because opam can't find the `ocaml.config.in` file anymore. 
Also, now that I know a bit more about the new format of `.opam/`, adding the compiler to `.opam/compilers` is clearly not going to work. If I understand correctly, it should be added to `.opam/repo/..`, and with `.opam/repo/compiler-index` updated. This is a bit frightening, since it's touching things that are defined in the real repositories.  
Alternatively, we assume that a switch is available (or we forcefully create it) and we put our stuff in `.opam/<switch>/.opam-switch/packages`. Is that better ?

**Comment by gasche** [comment] 2016-05-06 18:06
It seems much better to do switch-local changes indeed, as the current script does.

**Comment by AltGr** [comment] 2016-05-09 02:23
> It doesn't, because opam can't find the ocaml.config.in file anymore. 

Ah, that likely was added to `files/` ?

What you can do is add an `opam` _directory_ to the source, and in there have a `files/` subdirectory and an `opam` file — those should be picked up by `opam pin add`.

> Also, now that I know a bit more about the new format of .opam/, adding the compiler to .opam/compilers is clearly not going to work.

Yes, that doesn't exist anymore; and `.opam/packages/` neither, the caches are now per-switch.

> If I understand correctly, it should be added to .opam/repo/.., and with .opam/repo/compiler-index updated. This is a bit frightening, since it's touching things that are defined in the real repositories.

The `compiler-index` and `packages-index` have _also_ been removed¹, the package from all the repositories are now cached as a (repo -> package -> definition) map of maps, in the marshalled `repo/state.cache` file. The actual map of packages to their definition is now computed on switch load by union of the top map, with a given list of _active_ repositories and a priority order (with the intent that this list can become switch-specific, which is not yet the case).

So changing the repo would be acrobatic to say the least, and would break on any `opam update` anyway. I am not sure of the interface it could have, but support for a local repository built-in ~/.opam by default could be useful though, that may be an idea worth exploring (for some points in #2532 for example). It wouldn't have an upstream and could store local definitions that are not switch specific, a little like (but not exactly) pins not specific to a switch.

But in your case, I think a pin is fine.

¹ but it seems the upgrade doesn't clean them up, so thanks for reminding me :)

**Comment by Drup** [comment] 2016-07-26 19:26
So, current situation on `2.0+alpha2`

```
opam switch install --no-switch --empty my_little_ocaml
eval $(opam config env --switch my_little_ocaml)
cd /to/my/ocaml
./configure --prefix $(opam config var prefix)
make -j world.opt
opam pin add ocaml-variants.4.03.0+mycompiler -k path .
```

And the opam file look like that:
```
opam-version: "2.0"
name: "ocaml-variants"
version: "4.03.0+mycompiler"
descr: """
4.03 with my little patches
"""
depends: ["base-unix" "base-bigarray" "base-threads"]
flags: compiler
setenv: CAML_LD_LIBRARY_PATH = "%{lib}%/stublibs"
install: [make "install"]
url {
  src: "file:///to/my/ocaml"
}
```

And then everything works absolutely fine. :)
When I want to reinstall the compiler, `opam reinstall ocaml-variants` if I want to recompile everything, `make install` if I don't.

**Comment by gasche** [comment] 2016-07-26 19:38
That's very nice (nitpick: I don't understand the name `ocaml-variants`). I still think that a scripting layer (that is, `compiler-conf`) is useful to infer the `version` variable from the compiler's version plus the DCVS branch name (I'm pretty sure you would forget to update your opam file when you checkout to a new branch), similarly to generate the switch name, and to provide the safety-checking of making sure that branch did not change under your feet -- a fairly common mistake when playing between branches in git.

Also, the `install` rule you use (without `build` rule) are suitable for the development workflow, but not for user-destined packaging, and it breaks the opam conventions. I would expect people cloning the git repository to expect `opam pin add ocaml .` to just work -- which means that there should probably be a message clarifying this if you want to include it upstream.

**Comment by Drup** [comment] 2016-07-26 19:50
About `ocaml-variants`, I'll let @AltGr write the full documentation when the times comes, it's part of the opam-repository encoding of ocaml versions.

I completely agree with your various remarks. The checking and convenience of `compiler-conf` should probably stay the same. Mainly, the "switch creation" part is going to be just a set of opam command.

Note that pinning is also going to work just fine for experimental branches:
```
opam switch install --no-switch --empty experimental_camel
eval $(opam config env --switch experimental_camel)
opam pin add ocaml-variants.4.03.0+experimental_camel https+git://url/to/git/repo
```

And it will update if asked to (iirc, it will not be automatic).

**Comment by gasche** [comment] 2016-07-26 20:16
Do I understand correctly that for this `pin` workflow to work well, you need the pointed-to `git` repo to have an `opam` file at its root with `make world.opt` in a `build/install` rule, unlike the one you propose above? 

Now that I think of it, an `opam` file with `make world.opt` included could work just as well if there is a way to rebuild the pinned package from the development repository instead, or at least reuse the previous build artifacts as suggested in #2596.

**Comment by Drup** [comment] 2016-07-26 20:18
> Do I understand correctly that for this pin workflow to work well, you need the pointed-to git repo to have an opam file at its root with make world.opt in a build/install rule, unlike the one you propose above?

Yes.

**Closed** 2017-12-15 15:43 UTC

**Comment by gasche** [comment] 2017-12-15 15:45
(For the record, I plan to install opam2 soon and may start looking at this directly myself.)

**Comment by AltGr** [comment] 2017-12-15 17:23
@gasche, feel free to reach out for any advice :)

**Comment by Drup** [comment] 2017-12-15 17:30
Given the quality of the current compiler-as-packages/switch implementation, barely anything is needed. The workflow I presented above works very well, and it's even simpler if you don't really care about rebuild (then, you just pin).

One thing that would help make things even smoother would for `./configure` to retarget the compiler that are already built. In this case, we would have the exact same opam file for both path and git pins.

**Comment by gasche** [comment] 2018-04-07 20:12
So I have tried a few days ago to make `opam-compiler-conf` work on opam2 (I switched to opam2-rc recently). The scheme that I tried to setup was the following.

Imagine that I am running the script from a git checkout of `trunk` or a branch from it (so my code can infer that the base OCaml version is 4.07.0), that I have already run `opam compiler-conf configure` in the repository, and then `make world.opt`.

Then the script would (1) use a local switch (a new opam2 feature) and (2) generate an `opam` file for use with `opam pin`, with a special `build` rule that only runs `make install`, as we have already built. The detailed steps are as follows:

```shell
# install the compiler in a local switch
opam switch create . --empty

# generate a pinning-friendly opam file with a "build" rule that just installs
# (as before, we assume the developer did a build already before installing)
opam compiler-conf-2.sh get-conf > opam

opam pin --no-action add ocaml-variants.4.07.0+local-git-trunk file://.

opam install --inplace-build ocaml-variants.4.07.0+local-git-trunk
```

Unfortunately, the performance of this approach is very disappointing. On my machine:
- the initial `opam switch create . --empty` takes 5s! (This include calling the solver twice with an empty universe and no package to install, and each call takes 0.5s; it would be nice to not call the solver at all in this special case.)
- `opam pin --no-action` takes 20s! This comes from the fact that the source of the pinned program are copied within the switch, which means that not only the source is copied, but also all the source artifacts (we are working from a repository which has already been built). Copying all these files just takes a lot of time (`rsync` is used). It could help to have an option `--no-copy` to disable this copy of the switch source (of course in general it's good to have by default for reproducibility).
- `opam install --inplace-build` takes 43! Out of these, 23s are consumed by what looks like (again) a copy of the complete directory, this time with `cp -PRp`. The install script itself is not fast, it takes 13s in this setting (it seems slower on the just-copied files than from the build directory, which may be a cache/filesystem effect). The remaining 7s are mostly spent in useless calls to the CUDF solver and repeated loading of the CUDF universe.

In total we are well above a minute for something that should not, conceptually, take more than the time required to run "make install" from the build directory, which is around 5s on my machine.

@AltGr, who you accept a PR to add an option to disable the copying done implicitly when doing path-pinning? I would like `opam pin --no-action` to be really fast, and then `opam install --inplace-build` to really work in the pin directory.

Note: I didn't start with `opam pin --no-action`, I did an `opam pin add . --inplace-build`, for which it was clear to me that the semantics would be to run the `build` rule of the pinned package from the build directory. In practice `--inplace-build` does not influence the `pin` part at all, only the subsequent build (and I cannot tell if it is really effective in saving time), and splitting the two helped me investigate the costs separately.

**Comment by gasche** [comment] 2018-04-07 20:14
(One aspect I haven't discussed above is the fact that I'm not too happy with having a switch at `.`, because I would like the same git repository to be able to have several switches for several branches -- it is common to switch from one branch to another, and we expect to be able to use their compiler-conf switches concurrently. I think this can be done by using a local switch with the branch name in it; my initial attempts in this way didn't work as I wanted, but I would like to fix the performance problem first before looking at this generalization.)

**Comment by gasche** [comment] 2018-04-07 20:24
Note: the recipe proposed by @Drup in https://github.com/ocaml/opam/issues/2531#issuecomment-235377458 takes around the same time, with the final `opam pin` step taking 1m5s on my machine.

**Comment by dra27** [comment] 2018-04-07 23:32
One small bit - I know that on Friday, @AltGr was doing optimisations to sort out the unnecessary calls to the solver and multiple loadings of package universes, so that slow part is definitely in hand already.

**Comment by dra27** [comment] 2018-04-07 23:33
The other brief thought is whether this is still the best approach - given that opam 2 can detect when a system compiler has been updated and rebuild packages accordingly, wouldn't a workflow which persuades opam that your ocaml working tree is in fact a system compiler be better?

**Comment by gasche** [comment] 2018-04-08 07:33
It's actually a bit tricky to make a system-switch approach work, because opam seems to assume that system switches are in the user's PATH. To create system switches, I would configure the ocaml distribution to install with a prefix `/opt/ocaml-$VERSION-$BRANCH` or (to avoid root needs) `$(pwd)/.local/ocaml-$VERSION-$BRANCH`, but then I need to tell users to add $PREFIX/bin to their PATH for the whole thing to work, because `opam config env ...` will not do it by itself. (I did think of setting the PREFIX to be the switch's prefix itself, but then that means that the opam switch directories contain files not installed by opam, which is wrong and bound to create issues later.)

(On the positive side, this manual setting of the PATH does correspond to what people had been doing to test ocaml compilers before OPAM, so it's not foreign to old users. But having to set the PATH and the opam environment independently is a bit of a hassle, which I was happy to avoid with `opam-compiler-conf`.)

**Comment by dra27** [comment] 2018-04-08 10:38
I haven't tried it, but I don't think anything prevents a package updating `PATH`

**Comment by Drup** [comment] 2018-04-08 11:09
I'm not sure why you are using a local switch for this. This seems like a mostly orthogonal decision.

I must admit that the perf cost, while not insignificant, are completely dwarfted by the cost of just building the compiler. The only repeated cost is `opam install --inplace-build`. All the other costs are one-time setup costs. 
In my version, `opam pin` is still done only once. Afterwards, you only do `opam reinstall` or `make install`, which are unnavoidable costs anyway.

@dra27 As a compiler developer, I do not necessarily want to rebuild the universe after changing the compiler. Sometimes I know I didn't changed the object format and just want to test a small new thing at the end of the dependency chain. opam forcing me to rebuild everything because it detected a change would just annoy me. That's why in my version of the workflow, I had two reinstall method.

**Comment by dra27** [comment] 2018-04-08 12:04
@Drup - well, it could either be done with a version of the package which is *not* tied to the checksum of the external tool or, potentially, there could be an advanced option to tell opam to update the checksum but not rebuild the package universe.

**Comment by gasche** [comment] 2018-04-08 18:10
> I must admit that the perf cost, while not insignificant, are completely dwarfed by the cost of just building the compiler.

That's not actually true, re-compiling after a small bugfix has been applied (or after the addition of a debug print somewhere) can be fairly fast. I just tried, changing a string literal in `driver/main.ml` results in a 22s recompilation on my machine.

> The only repeated cost is `opam install --inplace-build`. All the other costs are one-time setup costs.

First, that is the most costly step, so it's not much of a consolation. Second, the separation between "one-time" and "repeated" cost is not meaningful for all workflows (consider a bugfix branch, it typically has only one or two installations). Finally, I suppose that quite a few of the "one-time" cost are re-paid on "reinstall" actions.

**Comment by Drup** [comment] 2018-04-08 19:41
I guess it comes down to the type of work then. I mostly have long-lived forks that I reinstall often. I don't setup new forks very often. The solver is pretty fast once you `opam sw --set-base` on your pinned compiler.

Let's hope that @AltGr's optimization work will make that discussion irrelevant. :)

**Comment by AltGr** [comment] 2018-04-09 08:08
Thanks for the feedback!

>   * the initial opam switch create . --empty takes 5s! (This include calling the solver twice with an empty universe and no package to install, and each call takes 0.5s; it would be nice to not call the solver at all in this special case.)

I fixed this already a while ago, will be in RC2 :)

>   * opam pin --no-action takes 20s! This comes from the fact that the source of the pinned program are copied within the switch, which means that not only the source is copied, but also all the source artifacts (we are working from a repository which has already been built). Copying all these files just takes a lot of time (rsync is used). It could help to have an option --no-copy to disable this copy of the switch source (of course in general it's good to have by default for reproducibility).
>   * opam install --inplace-build takes 43s! Out of these, 23s are consumed by what looks like (again) a copy of the complete directory, this time with cp -PRp.

Indeed, found a copy to the build_dir that should have been skipped in case of `--inplace`. Fix pending, thanks!

> The install script itself is not fast, it takes 13s in this setting (it seems slower on the just-copied files than from the build directory, which may be a cache/filesystem effect). The remaining 7s are mostly spent in useless calls to the CUDF solver and repeated loading of the CUDF universe.

Note that you can also do the two using `opam install . --inplace`. That won't help with the copy, though, but without it, how could opam detect wether the source has been changed or not ? It's indeed not been planned that source directories could be so big. As @Drup pointed out, you should need to pin only the first time, and using `(re)install DIR` directly should handle repeated runs better. 
I've been working on the cudf universe load times, and the solver really shouldn't take much time on such a trivial request (but there are still conversions to do back-and-forth, which I am checking for unoptimised parts).

I'll try to find some time to review the `install --inplace` workflow, which is clearly unoptimised in some parts. Another part that could cost is the removal, make sure you don't have things like `remove: "make uninstall"`, that should no longer be necessary and will have opam copy the whole source to a temp directory again.

**Comment by gasche** [comment] 2018-04-09 08:46
Thanks for the good news. I will be happy to reproduce the experiment with RC2 (or an experimental branch of opam if that helps) and report back.

> That won't help with the copy, though, but without it, how could opam detect wether the source has been changed or not ?

Hashing is a lot faster than copying on my machine. Hashing the whole directory recursively (`tar -c -O . | sha256sum`) takes 3s. Hashing only the source files (as one would when pinning a clean git directory), which I approximate with `git ls-files | xargs tar -c -O | sha256sum`, takes 0.1s. (And `sha1` is about twice faster than `sha256` in both cases.)

(On the other hand, hashing the whole directory would obviously not work well for this particular workflow given that I create an `_opam` file in the current directory (and we don't want to be hashing it). In general I suppose that people may want to work from a pinned subdirectory and not have a "change" noticed every time a single bit changes? I don't know what the current copying logic is.)

Would it make sense to give the pinning user's control over the file-change logic, for example with a `opam pin --use-file-depends` option that would use the `file-depends:` fields in the `.config` file instead of whole-source comparison? (Pinning would work in absence of `.config` file at pin-time, but the install would fail if there is no `.config` file at install-time.)

**Comment by gasche** [comment] 2018-06-07 08:05
I re-ran my measurements and the new results are much better. I think that the performance of opam is now adequate for this use-case.

Below is the workflow (adjusted to use a switch *outside* the current directory), with rc1 and rc2 timings:

```
SW=$(pwd)/..
opam switch create $SW --empty
# rc1: 5s
# rc2: 0.3s

eval $(opam env --switch=$SW --set-switch)

# create config
OPAMDIR=$SW/_opam bash opam2-compiler-conf.sh get-conf > opam

make clean
# the "pin" below is slower if build artifacts are found in the pinned directory
# we are going to run 'configure' anyway, which will force a full rebuild

time opam pin --no-action add ocaml-variants.4.07.0+local-git-trunk file://.
# rc1 or rc2, without the clean before: 20s
# with the clean before: 10s
# if the switch is in a tmpfs (eg. /tmp): 5s

OPAMDIR=$SW/_opam bash opam2-compiler-conf.sh configure
# 5s

time make world.opt -j5
# 2m20s

time opam install -y --inplace-build ocaml-variants.4.07.0+local-git-trunk
# rc1: 43s
# rc2: 5s
```

(I have run into minor issues with sandboxing, which I will report separately.)

I believe that ~rc2 has all I need for an `opam-compiler-script` conf that matches the convenience of the opam1 version, and I will report here once it is finished.

**Comment by gasche** [comment] 2018-06-11 20:17
In fact it looks like it's too hard to assume that `make clean` is run before the pin is added (it makes the interface less intuitive and more surprising), and `opam install` seems to re-pay the cost of copying the files anyway, so I think I will relax this assumption, which on my machine incurs an additional ~10s overhead.

In particular, I would still be interested in a feature that would prevent `pin` from copying the working directory of path-based pins (when setting up the pin, or when re-installing them). Maybe `opam pin add --inplace-build` could have this effect, maybe a separate option could be provided.
As far as I can tell, the only thing we lose if we do this is the ability to ask: "what was the state of this package when I ran the last pin installation command?", which doesn't seem that common -- in fact I don't know how to ask this using the opam command-line.
