### ISSUE TITLE
Uninformative error message

### ISSUE THREAD

**Issue by mmalter** [ocaml/opam#5172] opened 2022-07-04 06:48 UTC
Hello

Here is what I get when I try to install the dependencies on my project.

┌─────( michael@herrschreinerei pts/6 20083 8:46:42 )─( ~/github/ordo )
└─> opam install . --deps-only                                                                                                                                                                                      [INSERT] U S - main - ordo
Sorry, no solution found: there seems to be a problem with your request.

No solution found, exiting
┌─────( michael@herrschreinerei pts/6 20084 8:46:52 )─( ~/github/ordo )
└─> opam install --debug . --deps-only                                                                                                                                                                              [INSERT] U S - main - ordo
00:00.002  GSTATE                 LOAD-GLOBAL-STATE @ /home/michael/.opam
00:00.003  RSTATE                 LOAD-REPOSITORY-STATE @ /home/michael/.opam
00:00.060  RSTATE                 Loaded /home/michael/.opam/repo/state.cache in 0.054s
00:00.251  RSTATE                 Cache found
00:00.251  STATE                  LOAD-SWITCH-STATE @ default
00:00.331  STATE                  Detected changed packages (marked for reinstall): {}
00:00.344  STATE                  Switch state loaded in 0.093s
00:00.344  FILE(switch-state)     Wrote /home/michael/.opam/default/.opam-switch/backup/state-20220704064718.export in 0.000s
00:00.353  AUXCMD                 autopin: { ordo => git+file:///home/michael/github/ordo#main }
00:00.353  UPDATE                 update-dev-packages
00:00.353  PARALLEL               Iterate over 0 task(s) with 3 process(es)
00:00.353  SWACT                  add-to-reinstall unpinned_only:false packages:{}
00:00.465  CLIENT                 INSTALL ordo
00:00.703  SYSTEM                 [log-94776-ccabea] (in 0.025s) lsb_release -s -r
00:00.716  SYSTEM                 [log-94776-9b8556] (in 0.009s) ocamlc -vnum
00:00.856  CLIENT                 Orphans: (changes: { ordo.0.1.0 }, transitive: false) -> full {}, versions {}
00:01.133  SOLVER                 resolve request=install:(ordo) remove:() upgrade:()
00:02.163  SOLVER                 Load cudf universe (depopts:false, build:true, post:true)
00:02.275  CUDF                   resolve request=install:(ordo) remove:() upgrade:()
00:02.275  SOLVER                 Calling solver builtin-mccs+glpk with criteria -removed,-count[version-lag,request],-count[version-lag,changed],-changed
00:03.386  CUDF                   Solver call done in 1.111
00:04.247  CLIENT                 conflict!
Sorry, no solution found: there seems to be a problem with your request.

No solution found, exiting
00:04.249  SYSTEM                 rm /home/michael/.opam/default/.opam-switch/backup/state-20220704064718.export

**Comment by kit-ty-kate** [comment] 2022-07-04 16:54
This is a duplicate of #4373.

Could you try with opam `master` to see if https://github.com/ocaml/opam/pull/4982 fixed it or not.
If it didn’t could you provide the opam file or repository so we can try to reproduce your issue?

**Closed by kit-ty-kate** 2022-07-04 16:54 UTC
