### ISSUE TITLE
make cold gives ./configure output recommending make lib-exts, but that needs ocaml

### ISSUE THREAD

**Issue by Gurkenglas** [ocaml/opam#3307] opened 2018-04-21 17:21 UTC

**Comment by dra27** [comment] 2018-04-21 17:41
`make cold` builds a compiler in `bootstrap` - earlier in the output from `configure` you should see a message about a bootstrap compiler being detected and activated?

**Comment by Gurkenglas** [comment] 2018-04-21 18:00
make cold > githubreport.log
+ V=ocaml-4.02.1
+ URL=http://caml.inria.fr/pub/distrib/ocaml-4.02/ocaml-4.02.1.tar.gz
+ mkdir -p bootstrap
+ cd bootstrap
+ '[' '!' -e ocaml-4.02.1.tar.gz ']'
+ tar -zxvf ocaml-4.02.1.tar.gz
+ cd ocaml-4.02.1
++ pwd
+ ./configure -prefix /vol/fob-vol3/mi12/roseniki/Coq/opam-1.2.2/bootstrap/ocaml-4.02.1/../ocaml
+ make world opt
execv.c: In function ‘unix_execv’:
execv.c:23:3: warning: call to function ‘cstringvect’ without a real prototype [-Wunprototyped-calls]
   argv = cstringvect(args);
   ^
execv.c:18:16: note: ‘cstringvect’ was declared here
 extern char ** cstringvect();
                ^
execve.c: In function ‘unix_execve’:
execve.c:24:3: warning: call to function ‘cstringvect’ without a real prototype [-Wunprototyped-calls]
   argv = cstringvect(args);
   ^
execve.c:18:16: note: ‘cstringvect’ was declared here
 extern char ** cstringvect();
                ^
execve.c:25:3: warning: call to function ‘cstringvect’ without a real prototype [-Wunprototyped-calls]
   envp = cstringvect(env);
   ^
execve.c:18:16: note: ‘cstringvect’ was declared here
 extern char ** cstringvect();
                ^
execvp.c: In function ‘unix_execvp’:
execvp.c:26:3: warning: call to function ‘cstringvect’ without a real prototype [-Wunprototyped-calls]
   argv = cstringvect(args);
   ^
execvp.c:18:16: note: ‘cstringvect’ was declared here
 extern char ** cstringvect();
                ^
execvp.c: In function ‘unix_execvpe’:
execvp.c:38:3: warning: call to function ‘cstringvect’ without a real prototype [-Wunprototyped-calls]
   argv = cstringvect(args);
   ^
execvp.c:18:16: note: ‘cstringvect’ was declared here
 extern char ** cstringvect();
                ^
execvp.c:40:3: warning: call to function ‘cstringvect’ without a real prototype [-Wunprototyped-calls]
   environ = cstringvect(env);
   ^
execvp.c:18:16: note: ‘cstringvect’ was declared here
 extern char ** cstringvect();
                ^
+ make install
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1586  100  1586    0     0  22584      0 --:--:-- --:--:-- --:--:-- 22985
MD5 for extlib-1.5.3.tar.gz differ:
  expected: 3de5f4e0a95fda7b2f3819c4a655b17c
    actual: a0830b6fd2439ba2e924e08ba9e82a79
tar (child): ../extlib-1.5.3.tar.gz: Funktion open fehlgeschlagen: Datei oder Verzeichnis nicht gefunden
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
make[2]: *** [extlib.stamp] Error 2
make[1]: *** [lib-ext] Error 2
make: *** [cold] Error 2


githubreport.log: http://lpaste.net/6481782527919915008

**Comment by Gurkenglas** [comment] 2018-04-21 18:14
dra27, nowhere in the output does Ctrl-F find "detected" or "activated" in a relevant fashion.

**Comment by Gurkenglas** [comment] 2018-04-21 18:56
I am told the error line "tar (child): ../extlib-1.5.3.tar.gz: Funktion open fehlgeschlagen: Datei oder Verzeichnis nicht gefunden" is highly relevant.

**Comment by dra27** [comment] 2018-04-21 20:03
Please don't edit comments to remove the useful information! At least I can get the original information from the emailed GitHub notification...

So, you're building 1.2.2, which is why you wouldn't see anything about the bootstrap compiler being automatically detected, because that's part of 2.0. The actual error message is indeed to do with the message above, which has nothing to do with configure's request to run `make lib-ext` (please do read [this](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html#symptoms))

The problem is that the Google Code URLs no longer work - if you're forced to build 1.2.2 from sources, you'll need to change `URL_extlib` in `src_ext/Makefile` to `http://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/ocaml-extlib/extlib-1.5.3.tar.gz`. That should unblock the error - quickest, in terms of commands of tweaking, will be to run `make distclean` followed by `make cold` again having made that change, unless you're happy to tweak `PATH` and so forth by hand.

**Comment by Gurkenglas** [comment] 2018-04-21 23:29
Sorry, there was potentially identifying information. Good to know there's a way to privately contact you though :P!

**Comment by Gurkenglas** [comment] 2018-04-22 09:25
make cold, like make lib-ext, complains that `/extlib/extString.ml:127:            sub s i (j-i)` is string, not bytes. I'll try 2.0 now.

**Comment by dra27** [comment] 2018-04-26 09:31
Answering an earlier edit of your previous comment which, for the benefit of any confused reader, was:

> Sorry, there was potentially identifying information. Good to know there's a way to privately contact you though :P!

Do realise that from a security standpoint, editing the comment is largely meaningless - GitHub is very actively trawled. See, for example, [this story](https://www.bram.us/2015/01/04/the-2375-amazon-aws-mistake/) from a few years ago.

Coming back to the `make cold` point - by "complaining", I hope you mean that it emits a warning, not an error? It's a vendored library - we don't care about warnings in third party code (well, we do care, but we don't patch it here!).

**Comment by rjbou** [comment] 2019-06-27 13:46
Closing this issue. Feel free to reopen it if needed.

**Closed by rjbou** 2019-06-27 13:46 UTC
