### ISSUE TITLE
Opam config nuked after running out of disk space

### ISSUE THREAD

**Issue by sim642** [ocaml/opam#5440] opened 2023-02-09 08:38 UTC
This is a rather obscure scenario, but I happened to run out of disk space in the middle of some `opam upgrade`. Some arbitrary package build then failed with `Sys_error("No space left on device")`.

I didn't expect this to be much of an issue, but after freeing up disk space and rerunning opam, nothing works because `~/.opam/config` is now completely empty (which I suppose it shouldn't be). I guess opam tried to rewrite the file but couldn't due to disk space and was thus left in such broken state.

```
# opam config report
# opam-version         2.1.2 
# self-upgrade         no
# system               arch=x86_64 os=linux os-distribution=ubuntu os-version=22.04
# read-state           In /home/simmo/.opam/config:
unsupported or missing file format version; should be 2.0 or older
```

Not sure if much could be done about such corner case. Maybe writing the new file before removing the old one and renaming?

**Comment by sim642** [comment] 2023-02-09 08:42
`opam init --reinit` nor `opam init --bare` don't seem to fix anything either.

**Comment by kit-ty-kate** [comment] 2023-02-09 10:45
to avoid this to happen for other people we should enforce writes to be atomic on our end. For config files it shoudn’t be too hard, I’ll look into it.

**Comment by dra27** [comment] 2023-02-09 13:35
Note that there's a commit already for atomic writes in https://github.com/ocaml/opam/pull/5417/commits/bb0d675dba3c6c128470d7fc41160837bf757a78 - that could possibly be extracted early?

**Comment by rjbou** [comment] 2023-03-10 09:56
Closing as duplicate of #2715.

**Closed by rjbou** 2023-03-10 09:56 UTC
