### ISSUE TITLE
Dependencies not installed with "build & test"

### ISSUE THREAD

**Issue by Chris00** [ocaml/opam#2771] opened 2016-12-08 23:29 UTC
When the dependency `"ocamlmod" {build & test}`, oasis did not build because `ocamlmod` was not installed.  Upon [changing it to  `"ocamlmod" {build}`](https://github.com/ocaml/opam-repository/pull/8040#issuecomment-265724296), the package build correctly.

**Comment by AltGr** [comment] 2016-12-09 14:45
`{build & test}` means that the dependency only holds if you specified `--test` (and, in opam 2.0, listed the package name on the command-line).
What behaviour did you expect ?

**Comment by Chris00** [comment] 2016-12-09 14:54
On 2016-12-09, Louis Gesbert wrote:
> 
> {build & test} means that the dependency only holds if you specified 
> --test (and, in opam 2.0, listed the package name on the 
> command-line).
> What behaviour did you expect ?

I was thinking that it would be triggered BOTH for build and for tests. 
If I want a dependency to be triggered for "build", "test", and "doc", 
should I add 3 separate lines?

**Comment by AltGr** [comment] 2016-12-09 15:21
Ah, then you mean `{build | test}`. It's not allowed yet in opam 1.2.2 though.

That said, currently, a build dependency is strictly stronger than a test dependency. So you are fine with just `{build}`.

**Comment by Chris00** [comment] 2016-12-09 15:49
On 2016-12-09, Louis Gesbert wrote:
>
> Ah, then you mean {build | test}. It's not allowed yet in opam 1.2.2 
> though.

Ah, OK — I tried it but it was refused so I imagined that '&' was used.

> That said, currently, a build dependency is strictly stronger than a 
> test dependency. So you are fine with just {build}.

You mean "build ⊃ test", so as predicates "test ⇒ build" and thus "build 
∧ test ≡ test" and "build ∨ test ≡ build".

What about "doc" versus "build" and versus "test"?

**Comment by Chris00** [comment] 2016-12-10 12:01
BTW, it would be also good to clarify [the manual](https://opam.ocaml.org/doc/Manual.html#opamfield-depends) on this matter.

**Comment by AltGr** [comment] 2016-12-14 09:12
> You mean "build ⊃ test", so as predicates "test ⇒ build" and thus "build ∧ test ≡ test" and "build ∨ test ≡ build".

Yes, that's what I meant. But actually, it's not entirely true, _e.g._ a test dependency can trigger rebuilds that a pure build dependency wouldn't have.

> BTW, it would be also good to clarify the manual on this matter.

Probably not much better on this front, but please also check the 2.0 version of the man: https://opam.ocaml.org/doc/2.0/Manual.html#opamfield-depends

**Comment by Chris00** [comment] 2016-12-14 23:11
So, in opam 2.0, the same behavior (test ⇒ build) takes place?

**Comment by AltGr** [comment] 2016-12-20 15:11
Note: duplicate of #2227

**Comment by AltGr** [comment] 2017-01-19 11:54
Closing as 2.0 solves this by allowing `{build | test}`, and in the meantime it's safe to use just`{build}`. Thanks for reporting!

**Closed by AltGr** 2017-01-19 11:54 UTC

**Comment by Chris00** [comment] 2017-01-21 16:28
Thanks for fixing it! 👍
