### ISSUE TITLE
ocaml-version >= "4.02.3" not satisfied by ocaml 4.06.1 on old switch after upgrade to opam 2

### ISSUE THREAD

**Issue by Blaisorblade** [ocaml/opam#3600] opened 2018-10-11 17:10 UTC
This is a followup on #3594 (which might be the same or a different issue) /cc @rjbou.

TLDR:
```
$ opam install coq
[ERROR] coq = 8.8.0 unmet availability conditions: ocaml-version >= "4.02.3"
```
Currently running `opam reinstall -y ocaml-base-compiler` in case that helps.

```
pgiarrusso@SilenceOfTheLambdas:~/git/Coq/dot-calculus$ opam list
# Packages matching: installed
# Name              # Installed       # Synopsis
base-bigarray       base
base-threads        base
base-unix           base
camlp5              7.06.10-g84ce6cc4 Preprocessor-pretty-printer of OCaml
conf-m4             1                 Virtual package relying on m4
num                 1.1               The legacy Num library for arbitrary-precision integer and rational arithmetic
ocaml               4.06.1            The OCaml compiler (virtual package)
ocaml-base-compiler 4.06.1            Official 4.06.1 release
ocamlfind           1.8.0             A library manager for OCaml
ott                 0.28              Ott is a tool for writing definitions of programming languages and calculi
pgiarrusso@SilenceOfTheLambdas:~/git/Coq/dot-calculus$ opam install coq-equations
The following dependencies couldn't be met:
  - coq-equations → coq >= 8.8
      unmet availability conditions, e.g. ocaml-version >= "4.02.3"

No solution found, exiting
$ opam install coq
[ERROR] coq = 8.8.0 unmet availability conditions: ocaml-version >= "4.02.3"
```

```
pgiarrusso@SilenceOfTheLambdas:~/git/Coq/minidot/ecoop17$ opam switch
#  switch                   compiler                    description
   4.05.0                   ocaml-base-compiler.4.05.0
→  coq-8.8.0                ocaml-base-compiler.4.06.1  base-bigarray.base base-threads.base base-unix.base ocaml-base-compiler.4.06.1
   coq-8.8.1                ocaml-base-compiler.4.06.1  base-bigarray.base base-threads.base base-unix.base ocaml-base-compiler.4.06.1
   coq-8.8.1-equations-1.0  ocaml-base-compiler.4.06.1
   coq-8.8.2                ocaml-base-compiler.4.07.0  coq-8.8.2
(reverse-i-search)`env': opam ^Cv
pgiarrusso@SilenceOfTheLambdas:~/git/Coq/minidot/ecoop17$ opam show ocaml -f setenv:
[CAML_LD_LIBRARY_PATH = "%{_:stubsdir}%"]
[CAML_LD_LIBRARY_PATH += "%{lib}%/stublibs"]
[OCAML_TOPLEVEL_PATH = "%{toplevel}%"]
pgiarrusso@SilenceOfTheLambdas:~/git/Coq/minidot/ecoop17$ opam config report
# opam config report
# opam-version      2.0.0
# self-upgrade      no
# system            arch=x86_64 os=macos os-distribution=homebrew os-version=10.13.6
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              4
# repositories      2 (http), 1 (version-controlled) (default repo at 353f5fa6)
# pinned            1 (http), 1 (version)
# current-switch    coq-8.8.0
```

**Comment by Blaisorblade** [comment] 2018-10-12 20:48
@rjbou Looking at #3515, I think it's the same bug even tho I'm not *exactly* in the scenario you describe: the package was pinned *and installed* in opam 1.2.x, which is but I had to install it anyway (after https://github.com/ocaml/opam/issues/3594#issuecomment-429039070).

Anyway, given the amount of bugs of this sort of format, I'll probably stop trying and just remove the old switches. The only reason I haven't done that is in case these bug reports are useful.

Would it be helpful to send you somehow a copy of my old `.opam`, or parts of it (say, the config files)?

**Comment by rjbou** [comment] 2018-10-15 16:30
> The package was pinned and installed in opam 1.2.x

Pinned and installed packages are updated during format upgrade. I'll relaunch tests with `coq.8.8.0` to check if there is a special case here.

> in case these bug reports are useful.

They are! As all project, it help us to find some corner case. But in some cases, if we can't reproduce or detect exactly the issue origin, it's not easy to update the project.

> Would it be helpful to send you somehow a copy of my old .opam, or parts of it (say, the config files)?

It can. As the upgrade process didn't upgrade everything, it is more the process than the final state that can help us target the bug if any. But having the internals can give a good hint to find what _went wrong_.

**Comment by rjbou** [comment] 2019-02-04 14:39
Fix merged, thanks for the report.

**Closed by rjbou** 2019-02-04 14:39 UTC
