### ISSUE TITLE
Don't remove existing entries in the $PATH unless they were added by opam

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [ocaml/opam#3512] opened 2018-08-23 19:51 UTC
So, I manually keep my *default* switch's binary-dir in my system `$PATH`; and I use that to install a lot of fairly-switch-independent tools (`ocamlformat`, `odoc` …)

```
❯ ~ echo $PATH | tr ':' "\n" | nl
     1  /Users/ec/Library/System/Dotfiles/zsh/modules/zplug/zplug/bin
     2  /Users/ec/.zsh/modules/zplug/zplug/bin
     3  /Users/ec/.rbenv/shims
     4  /Users/ec/.rbenv/bin
     5  /Users/ec/.nodenv/shims
     6  /Users/ec/.nodenv/bin
     7  ./node_modules/.bin
     8  /Users/ec/.opam/default/bin
     9  /Users/ec/.cargo/bin
    10  /Users/ec/.bin
        ...
```

This worked for a while, and I was happy. Unfortunately, this no longer works, and now I am sad.

If I change to a project,

```
❯ ~ cd ~/Sync/Code/excmd-parser && eval $(opam env --switch=. --set-switch)
```

I then no longer have any of my global tools in my `$PATH`:

```
❯ excmd-parser master* ⟰  echo $PATH | tr ':' "\n" | nl
     1  /Users/ec/Sync/Code/excmd-parser/_opam/bin
     2  /Users/ec/Library/System/Dotfiles/zsh/modules/zplug/zplug/bin
     3  /Users/ec/.zsh/modules/zplug/zplug/bin
     4  /Users/ec/.rbenv/shims
     5  /Users/ec/.rbenv/bin
     6  /Users/ec/.nodenv/shims
     7  /Users/ec/.nodenv/bin
     8  ./node_modules/.bin
     9  /Users/ec/.cargo/bin
    10  /Users/ec/.bin
        ...
```

Note that it *removed* `/Users/ec/.opam/default/bin` before adding `/Users/ec/Sync/Code/excmd-parser/_opam/bin`. Oh noes!

----

I see several ways forward:

1. Ignore me! My use-case is maybe a little weird? I don't know how many people do this … (I just *really* like directory-local switches, coming from Node / npm; and I really *don't* like waiting on the same 100+ packages to compile — in addition to the compiler itself! — for every new little project.);

2. special-case the default switch (i.e. special-case my particular usage pattern — 😘); only remove *non-default* switches' bindirs from the `$PATH`, if present, when switching directories;

3. or spend the limited development resources handle this intelligently: only remove the *current* switch's path when switching away, and only add it *if* it was added by opam (i.e. it's the most recent entry? or some more complicated logic?)

Thanks for reading!

**Comment by rjbou** [comment] 2018-08-24 11:09
> only remove non-default switches' bindirs from the $PATH, if present, when switching directories

We don't want to force user to use _default_ switch as its default one, neither to have it in the `PATH`. Plus, on switch switching, misleading version of binaries can be hidden by the remaining default bin in path.

> only remove the current switch's path when switching away, and only add it if it was added by opam 

In fact,  it is already the case. To update `PATH`, opam looks to current terminal defined  switch (`OPAM_SWITCH_PREFIX`)  and retrieve its last modification (`<opamroot>/theswitch/.opam_switch/environment`). Then it changes the found bin path value, putting it in front of `PATH`, or inplace in case `--inplace-path` option is given. In order to do that, the `PATH` list is split at the first current switch bin path, which is in your case l.8 of the first listing.
A trick to make you happy again is be to add manually default bin path after evaluating a first time `opam env` (it works also with shell hook enabled). You can add in you shell rc file something like
```sh
eval $(opam env)
export PATH=$PATH:$(opam config var bin --switch default)
```

I suppose that you had previously two opam bin path defined, that's why it had the desired behavior.



Thanks for reporting!

**Comment by rjbou** [comment] 2018-09-19 16:15
Closing this issue as it is normal behaviour.
Hope the hint worked.

**Closed by rjbou** 2018-09-19 16:15 UTC

**Comment by ELLIOTTCABLE** [comment] 2019-02-24 03:03
To anybody else who happens to be struggling with this (yes, it's still a problem — appending the extra value once as described at shell-init unfortunately *isn't enough*, as that value will be lost if you ever happen to switch to the default switch and then back to another switch), the workaround I've found is this:

1. Create some default-ish switch (whichever one you want to hold ‘global’ binaries):

   ```sh
   opam switch create global-packages
   ```

2. On each machine, *manually* add a symlink to  to a predictable location:

   ```sh
   ln -s "$HOME/.opam/global-packages/bin" ~/.opam/global-packages-bin-alias
   ```

3. Hardcode the latter, not the former, into your `$PATH` configuration, however that may be relevant. Make sure it's *late* in your path, so project-local switches (when added by `eval "$(opam env)"` or similar) override it.

   ```sh
   export PATH="$PATH:$HOME/opam/global-packages-bin-alias"
   ```

(You can see the impl of this in my personal dotfiles — ELLIOTTCABLE/System@d9b23dac, if you're curious!)

**Comment by rjbou** [comment] 2019-02-25 17:46
Can you share your process? I can't reproduce, appended extra value remains...
```bash
$ export PATH=/usr/local/bin:/usr/bin:/bin

$ opam sw cr foo
$ echo $PATH
/opam/.opam/foo/bin:/usr/local/bin:/usr/bin:/bin

$ opam sw default
$ echo $PATH
/opam/.opam/default/bin:/usr/local/bin:/usr/bin:/bin

$ opam sw foo
$ export PATH=$PATH:`opam config var bin --switch default`
$ echo $PATH
/opam/.opam/foo/bin:/usr/local/bin:/usr/bin:/bin:/opam/.opam/default/bin

$ opam sw default
$ echo $PATH
/opam/.opam/default/bin:/usr/local/bin:/usr/bin:/bin:/opam/.opam/default/bin

$ opam sw foo
$ echo $PATH
/opam/.opam/foo/bin:/usr/local/bin:/usr/bin:/bin:/opam/.opam/default/bin
```

**Comment by ELLIOTTCABLE** [comment] 2019-03-11 20:27
@rjbou … I … cannot reproduce either. That's so odd, because I'm still on `opam 2.0.0`, too, so it can't be an upstream change …

Welp! It appears I've wasted everybody's time! Thanks for looking into it for me; and I guess I can get rid of my workaround 🤣
