### ISSUE TITLE
opam on cygwin fails to install camlp4 with error: Cannot find file dynlink.cmxa

### ISSUE THREAD

**Issue by philtomson** [ocaml/opam#2276] opened 2015-08-05 22:51 UTC
```
$ ocamlc -config
version: 4.02.0
standard_library_default: /home/phil/.opam/4.02.0/lib/ocaml
standard_library: /home/phil/.opam/4.02.0/lib/ocaml
standard_runtime: /home/phil/.opam/4.02.0/bin/ocamlrun
ccomp_type: cc
bytecomp_c_compiler: gcc -fno-defer-pop -Wall -U_WIN32 -D_FILE_OFFSET_BITS=64 -D_REENTRANT
bytecomp_c_libraries: -lm  -lcurses -lpthread
native_c_compiler: gcc -Wall -U_WIN32 -D_FILE_OFFSET_BITS=64 -D_REENTRANT
native_c_libraries: -lm
native_pack_linker: ld -r  -o
ranlib: ranlib
cc_profile: -pg
architecture: amd64
model: default
system: cygwin
asm: as
asm_cfi_supported: true
with_frame_pointers: false
ext_obj: .o
ext_asm: .s
ext_lib: .a
ext_dll: .so
os_type: Cygwin
default_executable_name: camlprog.exe
systhread_supported: true
host: x86_64-unknown-cygwin
target: x86_64-unknown-cygwin
exec_magic_number: Caml1999X011
cmi_magic_number: Caml1999I017
cmo_magic_number: Caml1999O010
cma_magic_number: Caml1999A011
cmx_magic_number: Caml1999Y014
cmxa_magic_number: Caml1999Z013
ast_impl_magic_number: Caml1999M016
ast_intf_magic_number: Caml1999N015
cmxs_magic_number: Caml2007D002
cmt_magic_number: Caml2012T004

$ opam install camlp4
The following actions will be performed:
  ∗  install camlp4 4.02+6

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[camlp4] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] The compilation of camlp4 failed at "make all".
Processing  1/2: [camlp4: rm]
# === ERROR while compiling camlp4.4.02+6 ======================================
# opam-version 1.3.0~dev (dccddae421767d1db65a89d6a6a0eb8fb005d90d)
# os           cygwin
# command      make all
# path         /home/phil/.opam/4.02.0/build/camlp4.4.02+6
# exit-code    2
# env-file     /home/phil/.opam/4.02.0/build/camlp4.4.02+6/camlp4-3436-ffb3fd.env
# stdout-file  /home/phil/.opam/4.02.0/build/camlp4.4.02+6/camlp4-3436-ffb3fd.out
# stderr-file  /home/phil/.opam/4.02.0/build/camlp4.4.02+6/camlp4-3436-ffb3fd.err

...
# ocamlopt dynlink.cmxa -g camlp4/config/Camlp4_import.cmx camlp4/config/Camlp4_config.cmx camlp4/boot/Camlp4.cmx camlp4/boot/camlp4boot.cmx -o camlp4/boot/camlp4boot.native
# \+ ocamlopt dynlink.cmxa -g camlp4/config/Camlp4_import.cmx camlp4/config/Camlp4_config.cmx camlp4/boot/Camlp4.cmx camlp4/boot/camlp4boot.cmx -o camlp4/boot/camlp4boot.native
# File "_none_", line 1:

**# Error: Cannot find file dynlink.cmxa**
# Command exited with code 2.
# Makefile:13: recipe for target 'byte' failed
### stderr
# \+ echo camlp4/Camlp4.cmo camlp4/Camlp4Top.cmo camlp4/camlp4prof.byte camlp4/mkcamlp4.byte camlp4/camlp4.byte camlp4/camlp4fulllib.cma camlp4/camlp4boot.byte camlp4/camlp4boot.cma camlp4/camlp4r.byte camlp4/camlp4r.cma camlp4/camlp4rf.byte camlp4/camlp4rf.cma camlp4/camlp4o.byte camlp4/camlp4o.cma camlp4/camlp4of.byte camlp4/camlp4of.cma camlp4/camlp4oof.byte camlp4/camlp4oof.cma camlp4/camlp4[...]
# make: **\* [byte] Error 10
```

I was able to install ocamlfind with opam which was apparently an earlier issue (not being able to install ocamlfind from opam) with a similar error message.

**Comment by dra27** [comment] 2017-05-21 18:31
Is this still broken?

**Comment by wintersteiger** [comment] 2018-01-06 17:01
It's still broken for me with a freshly installed cygwin64 after `opam init --comp 4.02.3` and `opam install depext`:

```
$ ocamlc -config
version: 4.02.3
standard_library_default: /cygdrive/c/cwinter/cygwin/.opam/4.02.3/lib/ocaml
standard_library: /cygdrive/c/cwinter/cygwin/.opam/4.02.3/lib/ocaml
standard_runtime: /cygdrive/c/cwinter/cygwin/.opam/4.02.3/bin/ocamlrun
ccomp_type: cc
bytecomp_c_compiler: gcc -O -fno-defer-pop -Wall -U_WIN32 -D_FILE_OFFSET_BITS=64 -D_REENTRANT -O
bytecomp_c_libraries: -lm   -lpthread
native_c_compiler: gcc -O -Wall -U_WIN32 -D_FILE_OFFSET_BITS=64 -D_REENTRANT
native_c_libraries: -lm
native_pack_linker: ld -r  -o
ranlib: ranlib
cc_profile: -pg
architecture: amd64
model: default
system: cygwin
asm: as
asm_cfi_supported: true
with_frame_pointers: false
ext_obj: .o
ext_asm: .s
ext_lib: .a
ext_dll: .so
os_type: Cygwin
default_executable_name: camlprog.exe
systhread_supported: true
host: x86_64-unknown-cygwin
target: x86_64-unknown-cygwin
exec_magic_number: Caml1999X011
cmi_magic_number: Caml1999I017
cmo_magic_number: Caml1999O010
cma_magic_number: Caml1999A011
cmx_magic_number: Caml1999Y014
cmxa_magic_number: Caml1999Z013
ast_impl_magic_number: Caml1999M016
ast_intf_magic_number: Caml1999N015
cmxs_magic_number: Caml2007D002
cmt_magic_number: Caml2012T004
```

```
$ opam install camlp4
The following actions will be performed:
  ∗  install ocamlbuild 0                     [required by camlp4]
  ∗  install conf-which 1                     [required by camlp4]
  ∗  install camlp4     4.02+7
===== ∗  3 =====
Do you want to continue ? [Y/n]

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[default] https://opam.ocaml.org/archives/camlp4.4.02+7+opam.tar.gz downloaded

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
∗  installed ocamlbuild.0
∗  installed conf-which.1
[ERROR] The compilation of camlp4 failed at "make all".
Processing  3/3: [camlp4: rm]
#=== ERROR while installing camlp4.4.02+7 =====================================#
# opam-version 1.2.2
# os           cygwin
# command      make all
# path         /cygdrive/c/cwinter/cygwin/.opam/4.02.3/build/camlp4.4.02+7
# compiler     4.02.3
# exit-code    2
# env-file     /cygdrive/c/cwinter/cygwin/.opam/4.02.3/build/camlp4.4.02+7/camlp4-5328-d2d111.env
# stdout-file  /cygdrive/c/cwinter/cygwin/.opam/4.02.3/build/camlp4.4.02+7/camlp4-5328-d2d111.out
# stderr-file  /cygdrive/c/cwinter/cygwin/.opam/4.02.3/build/camlp4.4.02+7/camlp4-5328-d2d111.err
### stdout ###
# [...]
# /cygdrive/c/cwinter/cygwin/.opam/4.02.3/bin/ocamlc.opt -c -g -w Z -I camlp4/import -warn-error A-3 -I camlp4/config -I camlp4 -o camlp4/config/Camlp4_import.cmo camlp4/config/Camlp4_import.ml
# /cygdrive/c/cwinter/cygwin/.opam/4.02.3/bin/ocamlopt.opt -c -g -w Z -I camlp4/import -warn-error A-3 -I camlp4/config -I camlp4 -o camlp4/config/Camlp4_import.cmx camlp4/config/Camlp4_import.ml
# /cygdrive/c/cwinter/cygwin/.opam/4.02.3/bin/ocamlopt.opt -c -g -w Z -I camlp4/import -warn-error A-3 -I camlp4/config -I camlp4 -o camlp4/config/Camlp4_config.cmx camlp4/config/Camlp4_config.ml
# /cygdrive/c/cwinter/cygwin/.opam/4.02.3/bin/ocamlopt.opt -c -g -w a -I camlp4/import -warn-error A-3 -I camlp4/config -I camlp4/boot -o camlp4/boot/Camlp4.cmx camlp4/boot/Camlp4.ml
# /cygdrive/c/cwinter/cygwin/.opam/4.02.3/bin/ocamlopt.opt -c -g -w a -I camlp4/import -warn-error A-3 -I camlp4/config -I camlp4/boot -o camlp4/boot/camlp4boot.cmx camlp4/boot/camlp4boot.ml
# /cygdrive/c/cwinter/cygwin/.opam/4.02.3/bin/ocamlopt.opt dynlink.cmxa -g camlp4/config/Camlp4_import.cmx camlp4/config/Camlp4_config.cmx camlp4/boot/Camlp4.cmx camlp4/boot/camlp4boot.cmx -o camlp4/boot/camlp4boot.native
# + /cygdrive/c/cwinter/cygwin/.opam/4.02.3/bin/ocamlopt.opt dynlink.cmxa -g camlp4/config/Camlp4_import.cmx camlp4/config/Camlp4_config.cmx camlp4/boot/Camlp4.cmx camlp4/boot/camlp4boot.cmx -o camlp4/boot/camlp4boot.native
# File "_none_", line 1:
# Error: Cannot find file dynlink.cmxa
# Command exited with code 2.
### stderr ###
# + echo camlp4/Camlp4.cmo camlp4/Camlp4Top.cmo camlp4/camlp4prof.byte camlp4/mkcamlp4.byte camlp4/camlp4.byte camlp4/camlp4fulllib.cma camlp4/camlp4boot.byte camlp4/camlp4boot.cma camlp4/camlp4r.byte camlp4/camlp4r.cma camlp4/camlp4rf.byte camlp4/camlp4rf.cma camlp4/camlp4o.byte camlp4/camlp4o.cma camlp4/camlp4of.byte camlp4/camlp4of.cma camlp4/camlp4oof.byte camlp4/camlp4oof.cma camlp4/camlp4orf.byte camlp4/camlp4orf.cma camlp4/Camlp4Parsers/Camlp4AstLoader.cmo camlp4/Camlp4Parsers/Camlp4DebugParser.cmo camlp4/Camlp4Parsers/Camlp4GrammarParser.cmo camlp4/Camlp4Parsers/Camlp4ListComprehension.cmo camlp4/Camlp4Parsers/Camlp4MacroParser.cmo camlp4/Camlp4Parsers/Camlp4OCamlOriginalQuotationExpander.cmo camlp4/Camlp4Parsers/Camlp4OCamlParser.cmo camlp4/Camlp4Parsers/Camlp4OCamlParserParser.cmo camlp4/Camlp4Parsers/Camlp4OCamlReloadedParser.cmo camlp4/Camlp4Parsers/Camlp4OCamlRevisedParser.cmo camlp4/Camlp4Parsers/Camlp4OCamlRevisedParserParser.cmo camlp4/Camlp4Parsers/Camlp4OCamlRevisedQuotationExpander.cmo camlp4/Camlp4Parsers/Camlp4QuotationCommon.cmo camlp4/Camlp4Parsers/Camlp4QuotationExpander.cmo camlp4/Camlp4Printers/Camlp4AstDumper.cmo camlp4/Camlp4Printers/Camlp4AutoPrinter.cmo camlp4/Camlp4Printers/Camlp4NullDumper.cmo camlp4/Camlp4Printers/Camlp4OCamlAstDumper.cmo camlp4/Camlp4Printers/Camlp4OCamlPrinter.cmo camlp4/Camlp4Printers/Camlp4OCamlRevisedPrinter.cmo camlp4/Camlp4Filters/Camlp4AstLifter.cmo camlp4/Camlp4Filters/Camlp4ExceptionTracer.cmo camlp4/Camlp4Filters/Camlp4FoldGenerator.cmo camlp4/Camlp4Filters/Camlp4LocationStripper.cmo camlp4/Camlp4Filters/Camlp4MapGenerator.cmo camlp4/Camlp4Filters/Camlp4MetaGenerator.cmo camlp4/Camlp4Filters/Camlp4Profiler.cmo camlp4/Camlp4Filters/Camlp4TrashRemover.cmo
# make: *** [Makefile:13: byte] Error 10



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions failed
  ∗  install camlp4 4.02+7
The following changes have been performed
  ∗  install conf-which 1
  ∗  install ocamlbuild 0

The former state can be restored with:
    opam switch import "~/.opam/4.02.3/backup/state-20180006165551.export"

```

**Comment by dra27** [comment] 2018-01-06 23:43
Did you install the flexdll Cygwin package?

**Comment by philtomson** [comment] 2018-01-06 23:51
I no longer have access to a Windows machine, so can't check if this is still a problem.

**Comment by wintersteiger** [comment] 2018-01-07 00:21
I'm almost sure that was without the flexdll package, but I spent literally the whole day en/disabling packages, compilers, (re)installing opam packages, and rebasing DLL load locations. The cross product of all my efforts always yields at least one fatal error.

I just tried again, starting with deleting my .opam directory, `opam init --comp 4.02.3`, without the flexdll package installed, and I get exactly the same error. After adding the flexdll package I get exactly the same error again, but I don't have time to do another fresh `opam init` before trying camlp4 right now.

**Comment by dra27** [comment] 2018-01-07 07:32
So you did `opam init` and then installed the flexdll package? I'd expect there to be no dynlink.cmxa in ~/.opam/4.02.3 in that case - without flexdll, the ocaml build will not include native dynlink.

I expect there's a metadata update needed on opam-repository.

**Comment by wintersteiger** [comment] 2018-01-07 14:37
Indeed, I just tried and after a fresh `opam init` with flexdll, camlp4 does install correctly. You're right, a metadata update would fix that, so that the error message is easier to understand, or depext installs the system package automatically.

That said, I still get another error that's not the same, but it seems related:

```
$ opam install ulex
The following actions will be performed:
  ∗  install ulex 1.2

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ulex] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] The compilation of ulex failed at "make".
Processing  1/1: [ulex: ocamlfind remove]
#=== ERROR while installing ulex.1.2 ==========================================#
# opam-version 1.2.2
# os           cygwin
# command      make
# path         /cygdrive/c/cwinter/cygwin/.opam/4.02.3/build/ulex.1.2
# compiler     4.02.3
# exit-code    2
# env-file     /cygdrive/c/cwinter/cygwin/.opam/4.02.3/build/ulex.1.2/ulex-6084-5f1023.env
# stdout-file  /cygdrive/c/cwinter/cygwin/.opam/4.02.3/build/ulex.1.2/ulex-6084-5f1023.out
# stderr-file  /cygdrive/c/cwinter/cygwin/.opam/4.02.3/build/ulex.1.2/ulex-6084-5f1023.err
### stdout ###
# ocamlbuild -byte-plugin pa_ulex.cma ulexing.cma
# /cygdrive/c/cwinter/cygwin/.opam/4.02.3/bin/ocamlc.opt unix.cma -I /cygdrive/c/cwinter/cygwin/.opam/4.02.3/lib/ocaml/ocamlbuild /cygdrive/c/cwinter/cygwin/.opam/4.02.3/lib/ocaml/ocamlbuild/ocamlbuildlib.cma myocamlbuild.ml /cygdrive/c/cwinter/cygwin/.opam/4.02.3/lib/ocaml/ocamlbuild/ocamlbuild.cmo -o myocamlbuild.exe
# /cygdrive/c/cwinter/cygwin/.opam/4.02.3/bin/ocamldep.opt -pp camlp4orf -modules pa_ulex.ml > pa_ulex.ml.depends
# /cygdrive/c/cwinter/cygwin/.opam/4.02.3/build/ulex.1.2/_build/myocamlbuild: "fork" failed: Resource temporarily unavailable
### stderr ###
#       1 [main] ocamlrun 16228 child_info_fork::abort: address space needed by 'dllunix.so' (0x400000) is already occupied
# make: *** [Makefile:5: all] Error 100



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions failed
  ∗  install ulex 1.2
No changes have been performed
```

It's not always the ulex package that throws this; when I install other packages in a different order, they also throw the same error. I tried a copious amount of rebase/rebase-trigger/re-installs/reboot-windows yesterday and the best I could get after a manual rebase is a `flexdll error: cannot relocate RELOC_REL32, target is too far: ...` . I can also trigger it thusly:

```$ /cygdrive/c/cwinter/cygwin/.opam/4.02.3/build/ulex.1.2/_build/myocamlbuild
      0 [main] ocamlrun 10476 child_info_fork::abort: address space needed by 'dllunix.so' (0x400000) is already occupied
Failure:
  Error during command "mkdir /cygdrive/c/cwinter/cygwin/_build": Unix.Unix_error(Unix.EAGAIN, "fork", "").
```

Thus that mean I need to guess the magic memory location to load dllunix.so into?

(I assumed our internal project documentation told me to not install the cygwin flexdll package because of that sort of thing, but I think that information is just outdated, it's clearly needed for opam.)

**Comment by wintersteiger** [comment] 2018-01-07 14:42
I might as well add it here: After running `rebase -s ./.opam/4.02.3/lib/ocaml/stublibs/dllunix.so`, `opam install ulex` says this:

```
...
# Fatal error: cannot load shared library dllunix
# Reason: flexdll error: cannot relocate RELOC_REL32, target is too far: 0xfffffffc000872cc  0x872cc
```

**Comment by dra27** [comment] 2018-01-07 16:53
Try

```
rebase -b 0x7cd20000 ./.opam/4.02.3/lib/ocaml/stublibs/dllunix.so
rebase -b 0x7cdc0000 ./.opam/4.02.3/lib/ocaml/stublibs//dllthreads.so
```

**Comment by wintersteiger** [comment] 2018-01-07 17:49
I just tried it without the flexdll package being installed, but having compiled my own copy of flexdll from source and in the end I get exactly the same errors, so the flexdll package is not the problem.

**Comment by wintersteiger** [comment] 2018-01-07 17:51
Yes! Thanks @dra27, after those rebase's ulex finally installed correctly. How did you get those addresses?

**Comment by dra27** [comment] 2018-01-08 21:35
Right, fix has been merged for camlp4 and there's now a PR on opam-repository, so this issue can be closed, I think.

@wintersteiger - if I remember correctly, the base address for dllunix.so was simply what 32-bit Cygwin was using on the day I first encountered this problem. The address for dllthreads.so is then the result of adding the code size of dllunix.so to that base address plus a bit of wiggle room!

The problem is that 64-bit flexlink must ensure that the base address doesn't result in any relocations requiring more than 32-bits. flexlink's "solution" is to specify a fixed base address for all DLLs (so they load inefficiently) however this interacts really badly with 64-bit Cygwin's fork implementation.

I haven't yet had the energy to coordinate the fix, as it also involves the Cygwin ocaml package's maintainer and almost a certainly a patch to the Cygwin rebase utility. I don't think I'm going to have time to address it for 4.07, but hopefully by 4.08 later this year we may at least have a patch set.

**Comment by AltGr** [comment] 2018-01-11 06:12
Wow. I certainly thank @dra27 for solving this :)

**Closed by AltGr** 2018-01-11 06:12 UTC

**Comment by dra27** [comment] 2018-01-11 13:55
I've put a request [on the Cygwin mailing list](https://cygwin.com/ml/cygwin/2018-01/msg00079.html) for its opam package to add dependencies to at least `flexdll` and `libX11-devel` which should help mitigate this issue in future, since opam will naturally compile a "correct" OCaml (`libX11-devel` means that the graphics library will also always be available).

@AltGr - I haven't yet looked at it, but are we able to have depexts on the ocaml-base-compiler package in opam 2.0? What happens here is that if the `flexdll` package is missing, then OCaml's configure disables shared library support and so doesn't install `dynlink.cmxa`. It's always available on Windows, it's just a matter of ensuring that this package is installed.

**Comment by dra27** [comment] 2018-01-11 13:55
@wintersteiger - I've opened an issue to track the Cygwin64 base address is at https://cygwin.com/ml/cygwin/2018-01/msg00079.html

**Comment by dra27** [comment] 2018-01-17 09:23
And opam 1.2.2-2 in Cygwin [should prevent this from happening again](https://cygwin.com/ml/cygwin/2018-01/msg00156.html)
