### ISSUE TITLE
`opam upgrade -a` cannot install a previously unpinned directory

### ISSUE THREAD

**Issue by RalfJung** [ocaml/opam#3613] opened 2018-10-17 06:39 UTC
There is an inconsistency in the behavior of `opam install` and `opam upgrade`: If I call `opam install path/to/something/`, and that directory contains an `opam` file, it gets installed. If I do the same with `opam upgrade -a`, opam complains
```
[WARNING] No pinned packages found at /home/r/Dokumente/Unisachen/iris/stdpp/build-dep
```
My expectation is that `opam upgrade -a $PACKAGE` is like `opam install $PACKAGE && opam upgrade`, just in a single transaction. It would be great if the two could be made more consistent.

**Comment by rjbou** [comment] 2019-01-23 15:21
Upgrade and install command don't have the same behavior. When an upgrade is done, it is not the install operation that is called background, just some features, like installing uninstalled pinned packages if they are given in argument.
Install permits to pin unpinned new packages, in order to install them, it is still in the _install_ scope, like installing pinned package is in _upgrade_ scope.
From my point of view, adding automatic pinning to upgrade is out of scope of _upgrade_ operation.

**Comment by RalfJung** [comment] 2019-01-23 15:33
> From my point of view, adding automatic pinning to upgrade is out of scope of upgrade operation.

Some time ago I asked about a "combined install + upgrade operation", and was told `opam upgrade` to be that one.  Now you are saying it is not.  Yet there is a clear use for such a combined operation: doing first install, then upgrade will sometimes do unnecessary work (if the installed package depends on what is being upgraded, it gets rebuild); doing first upgrade, then install will also sometimes do unnecessary work (install might, through its dependencies, force the installation of other packages at a different version, those other packages then got unnecessarily rebuilt during the previous upgrade step).

It is frequently very frustrating to interact with opam because I have a clear idea of what I want ("just those 3 operations in a single transaction, please") but opam's interface just won't let me do it.  I recently had that again (not even on CI) where doing *anything* forced a re-build of most of the switch (triggered by a system compiler update), but I also wanted it to upgrade coq and uninstall coq-stdpp at the same time -- but found no way to combine upgrade+uninstall into a single transaction.

In this case there's a simple work-around: we are doing `opam pin add -n build-dep/ && opam upgrade -a build-dep/`.  But of course, we only figured that out after we had CI failing, and it took a bit to notice the CI failure because most of the time we have a hot cache and the `upgrade` command works.  Inconsistencies like this make it extremely painful to use opam on CI: it often takes weeks or months to realize that in some corner case, opam does not behave the way you think it should.

**Comment by AltGr** [comment] 2019-01-23 16:32
I am sorry the interface of opam is still sometimes confusing. In fact, `opam install` was extended in 2.0.0 to allow specifying directories or URLs and automatically doing some `opam pin` under the hood before doing the actual `install` operation. It was decided to not propagate this sugar to `opam upgrade`, because it made less sense and would bloat the interface, but indeed we end up with this discrepancy between the two: for your case, you will indeed need to first use `opam pin -n` manually, then `opam upgrade --all`.

Your main complaint here is that the interface is not expressive enough to allow complex operations in one run. It was indeed designed first for the most common use-cases, and designing a convenient, easy to grasp _and expressive_ CLI is extremely difficult. Having to handle reproducibility and corner-cases without user-interaction for automated usage only adds to the equation. I guess, here, that the trouble boils down to your use-case where build times can be very long, while most may not care as much.

The case of "forced rebuilds" due to upstream changes is indeed annoying, but know that you can control them through `opam reinstall --[list-|forget-]pending`. Granted, this is not discoverable easily enough, maybe we should add a message when you happen to have them.

As for compound requests, while they are not available from the interface, there are a few (admittedly inconvenient)  workarounds: you could e.g. pin a dummy package `opam pin --edit dummy -` and use `depends:` and `conflicts:`, or use `opam switch import` with a file in the [expected format](http://opam.ocaml.org/doc/Manual.html#switch-state)

**Comment by AltGr** [comment] 2019-01-23 16:54
Note that we do provide better support for reproducing build environments in opam 2.0.0, through a new workflow: please check out the new [pin-depends](http://opam.ocaml.org/doc/Manual.html#opamfield-pin-depends), any feedback on how it would fit your needs is highly appreciated.

By using this field, you could replace `make build-dep` in `iris-coq` by `opam install --deps .`, and all the dependencies specified in `pin-depends` would get individually pinned. This can be used to fix their versions, as well as ensure specific git branches, etc.

**Comment by RalfJung** [comment] 2019-01-23 17:09
`make build-dep` is not about having git branches as dependencies.  It is our solution for https://github.com/ocaml/opam/issues/3123. I don't think `pin-depends` helps there.

`pin-depends` might help to avoid [this repository](https://gitlab.mpi-sws.org/FP/opam-dev/tree/master/packages/coq-iris) mapping git commits to opam versions.  However, from all I know `pin-depends` does not work transitively, which we require.

**Comment by rjbou** [comment] 2020-08-05 18:20
Closing this one, feel free to reopen if needed. Tanks!

**Closed by rjbou** 2020-08-05 18:20 UTC

**Comment by RalfJung** [comment] 2020-08-05 18:59
I don't think anything changed about the situation I described in the OP -- we are still using the same work-around as above (see [this code](https://gitlab.mpi-sws.org/iris/ci/-/blob/0950ee3e88cf0cfce111aab0f03d2373fcc99fbd/prepare-opam.sh#L90)).

**Comment by RalfJung** [comment] 2020-11-20 09:55
@rjbou could you reopen? The original issue still remains:
```
# there is an opam file in the "builddep" directory
$ ls builddep
coq-iris-examples-builddep.opam
# but `opam upgrade builddep/` does not work
$ opam upgrade builddep/
[WARNING] No pinned packages found at /home/r/Dokumente/Unisachen/iris/coq-users/examples/builddep
Everything as up-to-date as possible (run with --verbose to show unavailable upgrades).

The following packages are not being upgraded because the new versions conflict with other installed packages:
  - coq.8.12.1
  - coq-orc11.dev.2020-11-12.1.2d9dd724
  - coq-stdpp.dev.2020-11-15.0.e88411b5
    ∗ coq-orc11.dev.2020-11-12.1.2d9dd724 is installed and requires coq-stdpp (= dev.2020-11-11.2.6385b547 | = dev)
  - num.1.4
  - ocaml-config.2
However, you may "opam upgrade" these packages explicitly, which will ask permission to downgrade or uninstall the conflicting packages.
Nothing to do.
```
In contrast, `opam install builddep/` works:
```
$ opam install builddep/
coq-iris-examples-builddep is now pinned to file:///home/r/Dokumente/Unisachen/iris/coq-users/examples/builddep (version ~dev)
The following actions will be performed:
  ↗ upgrade coq-stdpp                  dev.2020-10-30.0.402f2d6a to dev.2020-11-11.2.6385b547 [required by coq-iris]
  ∗ install coq-iris                   dev.2020-11-13.1.9c531d57                              [required by coq-iris-heap-lang, coq-iris-string-ident]
  ↗ upgrade coq-orc11                  dev.2020-10-30.0.b186bfe1 to dev.2020-11-12.1.2d9dd724 [uses coq-stdpp]
  ∗ install coq-iris-string-ident      dev                                                    [required by coq-iris-examples-builddep]
  ∗ install coq-iris-heap-lang         dev.2020-11-13.1.9c531d57                              [required by coq-iris-examples-builddep]
  ∗ install coq-iris-examples-builddep ~dev*
===== ∗ 4   ↗ 2 =====
```
The reason I want to use `opam upgrade` is to also add the `-a` flag.

However, a pretty decent work-around exists: run `opam pin add -y -n builddep/` first.

**Comment by rjbou** [comment] 2020-11-20 15:27
I closed it regarding the discussion : we already merged some features in `install` and `upgrade`, but we don't want to make them interchangeable, and as there is a way to do it with 2 commands (and with no error, repinning a package don't fail).
