### ISSUE TITLE
Cannot pin json wheel to a specific version

### ISSUE THREAD

**Issue by ilitzroth** [ocaml/opam#2768] opened 2016-12-06 12:57 UTC
>>> 
$ opam pin add --kind=version json-wheel 1.0.6
json-wheel is now version-pinned to 1.0.6

json-wheel is now unpinned from version 1.0.6
>>>
This is in a fresh switch. json-wheel always immediately unpins itself.
I have the impression it reinstalls itself.

**Comment by AltGr** [comment] 2016-12-09 14:44
I have seen this issue already, and believe it was fixed in opam 2.0, but don't remember the cause. Running with `-v --debug` will probably help.

**Closed by AltGr** 2016-12-09 14:44 UTC
