### ISSUE TITLE
Could not update repository `default` for opam 2.0~beta

### ISSUE THREAD

**Issue by Kakadu** [ocaml/opam#2704] opened 2016-10-05 13:16 UTC
Somthing is wrong but I don't exactly know what....

```
➜  typeutil git:(master) opam --version            
2.0~beta
➜  typeutil git:(master) opam remote               
[NOTE] Use '--all' to see all configured repositories independently of what is selected in the current switch

=-=- Repository configuration for switch 4.03.0 -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
 1 default https://opam.ocaml.org/2.0~dev
➜  typeutil git:(master) opam update default --debug
00:00.005  GSTATE                  LOAD-GLOBAL-STATE
00:00.006  CLIENT                  UPDATE default
00:00.006  RSTATE                  LOAD-REPOSITORY-STATE
00:00.031  RSTATE                  Loaded /home/kakadu/.opam/repo/state.cache in 0.024s
00:00.044  RSTATE                  Cache found
00:00.044  STATE                   LOAD-SWITCH-STATE
00:00.062  STATE                   Detected changed packages (marked for reinstall): {}
00:00.062  STATE                   Switch state loaded in 0.016s

=-=- Updating package repositories =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
00:00.063  PARALLEL                Iterate over 1 task(s) with 3 process(es)
00:00.063  PARALLEL                Starting job 0 (worker 1/3): 0
00:00.063  REPOSITORY              update default (https://opam.ocaml.org/2.0~dev)
00:00.063  CURL                    pull-repo
00:00.178  SYSTEM                  rm /home/kakadu/.opam/repo/default/urls.txt.1.part
00:00.178  SYSTEM                  mkdir /home/kakadu/.opam/log
00:00.179  PARALLEL                Next task in job 0: curl --write-out %{http_code}\n --retry 3 --retry-delay 2 -L -o /home/kakadu/.opam/repo/default/urls.txt.1.part https://opam.ocaml.org/2.0~dev/urls.txt
Processing  1/1: [default: http]
00:02.398  PARALLEL                Collected task for job 0 (ret:0)
00:02.398  SYSTEM                  rm /home/kakadu/.opam/repo/default/urls.txt.1
00:02.400  SYSTEM                  [log-30734-dd682e] (in 0.004s) mv /home/kakadu/.opam/repo/default/urls.txt.1.part /home/kakadu/.opam/repo/default/urls.txt.1
[ERROR] Could not update repository default
00:02.430  PARALLEL                Job 0 finished
00:02.431  FILE(repos-config)      Wrote /home/kakadu/.opam/repo/repos-config in 0.000s
00:02.431  RSTATE                  Writing the cache of repository metadata to ~/.opam/repo/state.cache ...

00:02.447  RSTATE                  ~/.opam/repo/state.cache written in 0.016s
Now run 'opam upgrade' to apply any package updates.
00:02.447  SYSTEM                  rmdir /home/kakadu/.opam/log
00:02.448  SYSTEM                  rmdir /tmp/opam-kakadu-30734
➜  typeutil git:(master) 
```

**Comment by whitequark** [comment] 2016-10-07 04:36
I am hitting the same problem, as well as another person I know. The error message appears to be emitted after the `mv` invocation, but nothing in that invocation is failing, e.g. see my strace log: http://sprunge.us/VajS

**Comment by whitequark** [comment] 2016-10-07 04:49
I can confirm this is fixed in 2.0~alpha5.

**Comment by whitequark** [comment] 2016-10-07 04:53
IMO you should find the root cause of the actual error not being shown and fix that, at least.

**Comment by Kakadu** [comment] 2016-10-07 09:14
Is alpha5 newer than beta? It a little bit counterintuitive for me....

**Comment by whitequark** [comment] 2016-10-07 09:19
It is according to CHANGELOG (and this is ridiculous).

**Comment by AltGr** [comment] 2016-10-10 06:12
there was no released beta yet, just an ill-named version number in some dev versions (that, due to a rebase mistake on my part, sneaked into `opam --version` in the alpha4; but the generated files should be correctly versionned). Where did you see it appear in the changelog, @whitequark ?

**Comment by edwintorok** [comment] 2016-10-10 07:38
Where can I get `alpha5`, I only see `alpha4` in opam, do I have to pin all the `opam-*` packages to git?

**Comment by Kakadu** [comment] 2016-10-10 08:01
Obviously, This commit is alpha5
https://github.com/ocaml/opam/commit/36d3112a05ca132f8c7d7b98c665528f3aff535f

**Comment by whitequark** [comment] 2016-10-10 09:32
@AltGr Ah, I misread `2.0~alpha`, beta does not appear in the changelog.

**Comment by AltGr** [comment] 2016-11-16 08:46
This has been fixed (the whole repo sync thing has been much simplified, actually)

**Closed by AltGr** 2016-11-16 08:46 UTC
