### ISSUE TITLE
svn URLs not supported in opam file in the dev-repo field

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam#2484] opened 2016-03-21 16:42 UTC
dev-repo: "svn://svn.forge.ocamlcore.org/svn/ocamlviz/"
gives

```
    error  2: File format error: at
          ~/src/opam-repository/packages/ocamlviz/ocamlviz.1.01/opam:5:54,
          Unsupported protocol svn
```

**Comment by dbuenzli** [comment] 2016-03-21 16:52
Duplicate of #2409

**Closed** 2016-12-21 17:12 UTC
