### ISSUE TITLE
Ci issue possibly related to new release 2.2.1

### ISSUE THREAD

**Issue by mbarbin** [ocaml/opam#6179] opened 2024-08-22 18:34 UTC
Hello,
Earlier today multiple ci scripts in GitHub actions that usually validates started failing for me inside the setup-ocaml step:

```
      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v3
```

An example taken arbitrarily [here](https://github.com/mbarbin/error-log/actions/runs/10508823255/job/29113565586)

I compared the log of the part
```
> Initialise opam state
Error: The process '/opt/hostedtoolcache/opam/2.2.1/x86_64/opam' failed with exit code 2
```
with another run from just before the 2.2.1 release that succeeded. The diff start at:

Working
```bash
  /opt/hostedtoolcache/opam/2.2.0/x86_64/opam init --auto-setup --bare --enable-shell-hook
  
  User configuration:
    Updating ~/.profile.
  [NOTE] Make sure that ~/.profile is well sourced in your ~/.bashrc.
```

Failing
```bash
  /opt/hostedtoolcache/opam/2.2.1/x86_64/opam init --auto-setup --bare --enable-shell-hook
  /opt/hostedtoolcache/opam/2.2.1/x86_64/opam: 1: checking: not found
  /opt/hostedtoolcache/opam/2.2.1/x86_64/opam: 2: OCaml: not found
  /opt/hostedtoolcache/opam/2.2.1/x86_64/opam: 3: OCaml: not found
  /opt/hostedtoolcache/opam/2.2.1/x86_64/opam: 4: checking: not found
  ...
```

I haven't investigated further at this time and figured I would just let you know in case this rings a bell, and given the timing that really seems to match the submission of https://github.com/ocaml/opam/releases/tag/2.2.1

**Comment by kit-ty-kate** [comment] 2024-08-22 18:35
Duplicate of https://github.com/ocaml/opam/issues/6174. It's already fixed, it should work now if you restart the job. If it doesn't please feel free to update this ticket

**Closed by kit-ty-kate** 2024-08-22 18:35 UTC
