### ISSUE TITLE
`opam install . --deps-only --with-test --with-doc` does not install doc or test packages if the package in . is installed

### ISSUE THREAD

**Issue by cemerick** [ocaml/opam#4938] opened 2021-11-30 16:47 UTC
There's not a lot to say beyond what's in the subject, but here's a reproducible sequence of commands that demonstrate the problem:

```
$ opam switch create scratch 4.12.1 
...
$ opam install oseq
The following actions will be performed:
  ∗ install seq  base  [required by oseq]
  ∗ install dune 2.9.1 [required by oseq]
  ∗ install oseq 0.3
$ git clone https://github.com/c-cube/oseq.git
Cloning into 'oseq'...
$ cd oseq/
$ opam install . --deps-only --with-test --with-doc
Nothing to do. ############################ au contraire, plenty of test deps to install!
$ opam remove oseq
The following actions will be performed:
  ⊘ remove oseq 0.3
$ opam install . --deps-only --with-test --with-doc
The following actions will be performed:
  ∗ install ocaml-migrate-parsetree 2.2.0
  ∗ install ocamlfind               1.9.1
  ∗ install csexp                   1.5.1
  ∗ install cmdliner                1.0.4
  ∗ install result                  1.5
  ∗ install cppo                    1.6.8
  ∗ install ocamlbuild              0.14.0
  ∗ install stdlib-shims            0.3.0
  ∗ install re                      1.10.3
  ∗ install base-bytes              base
  ∗ install dune-configurator       2.9.1
  ∗ install uchar                   0.0.2
  ∗ install topkg                   1.0.4
  ∗ install qcheck-core             0.18
  ∗ install ounit2                  2.2.4
  ∗ install gen                     0.5.3
  ∗ install containers              3.5
  ∗ install uutf                    1.0.2
  ∗ install fmt                     0.8.10
  ∗ install astring                 0.8.5
  ∗ install qcheck-ounit            0.18
  ∗ install tyxml                   4.5.0
  ∗ install logs                    0.7.0
  ∗ install odoc-parser             0.9.0
  ∗ install fpath                   0.7.3
  ∗ install qcheck                  0.18
  ∗ install odoc                    2.0.0
  ∗ install qtest                   2.11.2
===== ∗ 28 =====
Do you want to continue? [Y/n] ^C
```

I would expect the first `opam install . --deps-only --with-test --with-doc` invocation to install the same 28 packages proposed by the second invocation, i.e. test and doc package installation IMO should proceed even if the current package is installed.

Notable that `opam install . --with-test --with-doc` works as expected; in that case, the installed package is pinned to the checkout at `.`, and test and doc dependencies flow in without complaint.

```
# opam config report
# opam-version         2.1.0 
# self-upgrade         no
# system               arch=x86_64 os=linux os-distribution=ubuntu os-version=20.04
# solver               builtin-mccs+glpk
# install-criteria     -removed,-count[avoid-version,changed],-count[version-lag,request],-count[version-lag,changed],-count[missing-depexts,changed],-changed
# upgrade-criteria     -removed,-count[avoid-version,changed],-count[version-lag,solution],-count[missing-depexts,changed],-new
# jobs                 7
# repositories         1 (http) (default repo at 0eacced0)
# pinned               0
# current-switch       scratch
# ocaml:native         true
# ocaml:native-tools   true
# ocaml:native-dynlink true
# ocaml:stubsdir       /home/chas/.opam/4.12.1/lib/ocaml/stublibs:/home/chas/.opam/4.12.1/lib/ocaml
# ocaml:preinstalled   true
# ocaml:compiler       system
# ocaml-system:path    /home/chas/.opam/4.12.1/bin
```

**Comment by rjbou** [comment] 2021-12-01 15:07
Thanks for the report! I'll close it as duplicate of #4507

**Closed by rjbou** 2021-12-01 15:07 UTC
