### ISSUE TITLE
OPAM Windows port

### ISSUE THREAD

**Issue by Baneeishaque** [ocaml/opam#2191] opened 2015-06-13 08:50 UTC
Is there any OPAM port for win64?

**Comment by dra27** [comment] 2015-08-31 11:22
The work I'm doing in https://github.com/dra27/opam/tree/windows supports all four native Windows ports (i.e. the mingw64 and Microsoft C compilers in both 32 and 64 bit versions of each). I'm afraid it's not complete yet, though!

**Comment by XVilka** [comment] 2015-09-12 21:46
Double of the https://github.com/ocaml/opam/issues/246 ?

**Comment by dra27** [comment] 2015-09-13 09:37
@XVilka - more a refinement of #246 :)

**Comment by Chris00** [comment] 2015-11-28 21:57
In case it is useful, I [started a project](https://github.com/Chris00/ocaml-appveyor) to have a native Windows (Win64) build of OCaml to use in Appveyor.  It also compiles OPAM (the `dose 3` tarball symlink has to be worked around) but the resulting `opam` does not work, `opam` returns:
```
Fatal error:
# opam-version    1.3.0~dev3 (ecc8e2da0e46329834837631020bf4d3f7c94a9c)
# os              win32
opam: "create_process" failed on /bin/sh: No such file or directory
Backtrace:
  Raised by primitive operation at file "unix.ml", line 820, characters 2-157
  Called from file "core/opamProcess.ml", line 180, characters 4-118
  Called from file "core/opamProcess.ml", line 260, characters 2-110
  Called from file "core/opamProcess.ml", line 452, characters 10-32
  Called from file "core/opamSystem.ml", line 292, characters 6-124
  Called from file "core/opamSystem.ml", line 330, characters 14-38
  Called from file "solver/opamSolverConfig.ml", line 38, characters 7-41
  Called from file "camlinternalLazy.ml", line 25, characters 17-27
  Re-raised at file "camlinternalLazy.ml", line 32, characters 10-11
  Called from file "solver/opamSolverConfig.ml", line 244, characters 28-48
  Called from file "client/opamArg.ml", line 74, characters 2-1023
  Called from file "client/opamMain.ml", line 1334, characters 4-39
rm: cannot remove 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\opam-appveyor-96/command-96-5a61c5.err': Device or resource busy 
rm: cannot remove 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\opam-appveyor-96/command-96-5a61c5.out': Device or resource busy 
rm: cannot remove 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\opam-appveyor-96/command-96-5a61c5.err': Device or resource busy 
rm: cannot remove 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\opam-appveyor-96/command-96-5a61c5.out': Device or resource busy 
Fatal error: exception # opam-version    1.3.0~dev3 (ecc8e2da0e46329834837631020bf4d3f7c94a9c)
# os              win32
Cannot remove C:\Users\appveyor\AppData\Local\Temp\1\opam-appveyor-96 (error 1).
Raised at file "core/opamSystem.ml", line 29, characters 10-30
Called from file "set.ml", line 305, characters 38-41
Called from file "pervasives.ml", line 482, characters 30-33
Called from file "pervasives.ml", line 487, characters 2-15
Called from file "client/opamMain.ml", line 1563, characters 2-22
Command exited with code 2
```

**Comment by Chris00** [comment] 2015-12-07 23:07
In case it is useful, the [worries about `ocamlfind` not working on pure Windows](https://github.com/ocaml/opam/issues/246#issuecomment-101167671) are unfounded: `ocamlfind` requires Cygwin [to be built](https://github.com/Chris00/ocaml-appveyor/blob/master/build_ocaml.sh#L76) but then happily works on pure Windows (I'll be glad this to be confirmed as there is no way to get rid of Cygwin on AppVeyor machines).  The same goes for `ocamlbuild` (as long as the path to compilers does not contain space, i.e., use the *short version* of the dir for now). As for [other packages](https://github.com/ocaml/opam/issues/246#issuecomment-85546862), the ones using oasis [build](https://ci.appveyor.com/project/Chris00/cppo/build/1.0.17) [fine](https://ci.appveyor.com/project/Chris00/ocamlmod) [on pure](https://ci.appveyor.com/project/Chris00/oasis/build/1.0.61#L213) Windows, even when [using C bindings](https://ci.appveyor.com/project/Chris00/ocaml-mindstorm/build/1.0.122).

**Comment by XVilka** [comment] 2016-02-15 15:00
Any updates on those patches? I see fork wasn't updating since November, 2015.

**Comment by dra27** [comment] 2016-02-15 15:05
I'd been doing some related work on OCaml 4.03 - will be getting back to this fork shortly!

**Comment by Chris00** [comment] 2016-02-15 20:18
:+1:

**Comment by braibant** [comment] 2016-02-17 09:19
@Chris00 out of curiosity, do you know how your appveyor project compares with https://github.com/braibant/ocaml-windows-bootstrap?

**Comment by Chris00** [comment] 2016-02-17 13:59
1. It builds OCaml with MSVC, not mingw — it uses Cygwin for the build but OCaml does not depend on it (the other scripts are CMD or `.ml`).
2. It is specifically designed for testing with AppVeyor (it provides scripts to easily do that — in particular one must properly set environment variables, there are many pitfalls to avoid in AppVeyor).  It probably could be used to generate an installer for OCaml but that will need to be a contribution.
3. It aims to (eventually) use Windows OPAM to install packages (without Cygwin that is).

I only had a cursory look to your work, so correct me if needed.

**Comment by braibant** [comment] 2016-02-18 14:35
Fair enough. I think that @protz use something inspired by my scripts to generate an installer, but I am not quite sure, and I used them to do some CI (but no AppVeyor).

**Comment by protz** [comment] 2016-02-18 19:46
I use your scripts to bootstrap my opam setup... and then I use opam to install whatever packages are needed to re-build opam.

**Comment by aantron** [comment] 2016-05-02 15:44
:+1:

**Comment by XVilka** [comment] 2016-11-30 12:43
I see a lot of work was done in your fork @dra27. I hope it will be merged in the mainline at some point. This will change OCaml adoption in Windows world drastically.

**Comment by dra27** [comment] 2016-11-30 12:47
It will hopefully be being rebased, completed and merged later this year and in early 2017 as I become a little more full time on it!

**Comment by soapdog** [comment] 2017-11-07 14:09
Any news regarding this port?

**Comment by XVilka** [comment] 2018-01-15 07:30
@soapdog this PR was merged, which is certainly a good news regarding Windows port https://github.com/ocaml/opam/pull/3155

**Comment by XVilka** [comment] 2019-07-12 05:39
@dra27 have you considered to check also the [clang-cl](https://clang.llvm.org/docs/MSVCCompatibility.html) port instead or in addition to MSVC one? [Google Chrome](http://blog.llvm.org/2018/03/clang-is-now-used-to-build-chrome-for.html) and [Mozilla Firefox](https://groups.google.com/forum/m/#!topic/mozilla.dev.platform/wwO48xXFx0A) recently switched to it for forming official Windows binaries. It brings also all kinds of [sanitizers](https://github.com/google/sanitizers) support to Windows compiled binaries.

**Comment by dra27** [comment] 2019-07-12 07:25
What problems do you expect that to solve?

**Comment by XVilka** [comment] 2019-07-12 08:10
@dra27 mostly catching bugs in OCaml runtime at Windows with extensive clang tooling.

**Comment by dra27** [comment] 2019-07-12 08:34
So not strictly of benefit to opam, then! There's remarkably little Windows-specific code in the OCaml runtime - the rest of it is already run through Clang's sanitizers in [Inria's CI](https://github.com/ocaml/ocaml/blob/trunk/tools/ci/inria/extra-checks).

**Comment by dra27** [comment] 2020-10-16 11:10
Full upstream support is (finally!) planned for opam 2.2. There is already excellent downstream support at https://fdopen.github.io/opam-repository-mingw/

**Closed by dra27** 2020-10-16 11:10 UTC
Labels: AREA: PORTABILITY
