### ISSUE TITLE
Using `opam install . --deps-only` doesn't actually result in *all* the deps being installed for *all* packages in the current dir

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [ocaml/opam#5676] opened 2023-09-18 22:25 UTC
I've checked out [ocaml/dune](https://github.com/ocaml/dune), and attempted to setup a directory-local switch in which to work on it using `opam switch create .` and the `--deps-only` flag:

```console
# ec@nspawn-us ~/code/dune main* ⇣
$ opam switch create . ocaml-base-compiler.5.1.0 --deps-only --no-install

<><> Installing new switch packages <><><><><><><><><><><><><><><><><><><><><><>
Switch invariant: ["ocaml-base-compiler" {= "5.1.0"}]

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
∗ installed base-bigarray.base
∗ installed base-threads.base
∗ installed base-unix.base
∗ installed ocaml-options-vanilla.1
⬇ retrieved ocaml-base-compiler.5.1.0  (cached)
∗ installed ocaml-base-compiler.5.1.0
∗ installed ocaml-config.3
∗ installed ocaml.5.1.0
∗ installed base-domains.base
∗ installed base-nnp.base
Done.
# Run eval $(opam env) to update the current shell environment
```

Okay, that doesn't seem like it actually installed the dependencies … let's check:

```console
# ec@nspawn-us ~/code/dune main* ⇣
$ opam install . --deps-only --with-test
The following actions will be performed:
  ∗ install seq        base
  ∗ install ocamlfind  1.9.6
  ∗ install base-bytes base
===== ∗ 3 =====
Do you want to continue? [Y/n] y

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
∗ installed seq.base
⬇ retrieved ocamlfind.1.9.6  (cached)
∗ installed ocamlfind.1.9.6
∗ installed base-bytes.base
Done.
```

Huh. It seems to have missed some, when run via `opam switch create` instead of directly via `opam install`? That's odd.

But wait, that still _can't_ be all of the deps — for instance, where's lwt?

Let's try specifically indicating a single `.opam` file from the directory:

```console
# ec@nspawn-us ~/code/dune main* ⇣
$ opam install ./dune-rpc-lwt.opam --deps-only --with-test
The following actions will be performed:
  ∗ install dune              3.10.0
  ∗ install xdg               3.10.0
  ∗ install result            1.5
  ∗ install pp                1.2.0
  ∗ install ordering          3.10.0
  ∗ install csexp             1.5.2
  ∗ install cppo              1.6.9
  ∗ install dyn               3.10.0
  ∗ install dune-configurator 3.10.0
  ∗ install ocplib-endian     1.2
  ∗ install stdune            3.10.0
  ∗ install lwt               5.7.0
  ∗ install dune-rpc          3.10.0
===== ∗ 13 =====
Do you want to continue? [Y/n] n
```

w-what, okay, so it's _clearly_ not installing the dependencies of all of the `*.opam` files in `~/code/dune`. And yet,

```
$ opam install ./ --deps-only --with-test
Nothing to do.
```

wtf. Let's try without `--deps-only`:

```console
# ec@nspawn-us ~/code/dune main* ⇣ 6s
$ opam install ./ --with-test           
xdg is now pinned to git+file:///home/me/code/dune#main (version 3.10.0)
stdune is now pinned to git+file:///home/me/code/dune#main (version 3.10.0)
ordering is now pinned to git+file:///home/me/code/dune#main (version 3.10.0)
ocamlc-loc is now pinned to git+file:///home/me/code/dune#main (version 3.10.0)
dyn is now pinned to git+file:///home/me/code/dune#main (version 3.10.0)
dune is now pinned to git+file:///home/me/code/dune#main (version 3.10.0)
dune-site is now pinned to git+file:///home/me/code/dune#main (version 3.10.0)
dune-rpc is now pinned to git+file:///home/me/code/dune#main (version 3.10.0)
dune-rpc-lwt is now pinned to git+file:///home/me/code/dune#main (version 3.10.0)
dune-private-libs is now pinned to git+file:///home/me/code/dune#main (version 3.10.0)
dune-glob is now pinned to git+file:///home/me/code/dune#main (version 3.10.0)
dune-configurator is now pinned to git+file:///home/me/code/dune#main (version 3.10.0)
dune-build-info is now pinned to git+file:///home/me/code/dune#main (version 3.10.0)
dune-action-plugin is now pinned to git+file:///home/me/code/dune#main (version 3.10.0)
chrome-trace is now pinned to git+file:///home/me/code/dune#main (version 3.10.0)
The following actions will be performed:
  ∗ install dune                3.10.0*
  ∗ install xdg                 3.10.0*
  ∗ install stdlib-shims        0.3.0   [required by ppxlib]
  ∗ install sexplib0            v0.16.0 [required by base]
  ∗ install result              1.5     [required by dune-rpc-lwt]
  ∗ install re                  1.11.0  [required by ppx_expect]
  ∗ install ppx_derivers        1.2.1   [required by ppxlib]
  ∗ install pp                  1.2.0   [required by dyn, dune-private-libs, dune-rpc, stdune]
  ∗ install ordering            3.10.0*
  ∗ install ocaml-compiler-libs v0.12.4 [required by ppxlib]
  ∗ install jane-street-headers v0.16.0 [required by time_now]
  ∗ install dune-build-info     3.10.0*
  ∗ install csexp               1.5.2   [required by dune-rpc-lwt, dune-private-libs, dune-action-plugin, etc.]
  ∗ install cppo                1.6.9   [required by lwt]
  ∗ install chrome-trace        3.10.0*
  ∗ install dyn                 3.10.0*
  ∗ install ppxlib              0.30.0  [required by ppx_expect]
  ∗ install dune-configurator   3.10.0*
  ∗ install ocplib-endian       1.2     [required by lwt]
  ∗ install stdune              3.10.0*
  ∗ install ocamlc-loc          3.10.0*
  ∗ install base                v0.16.3 [required by ppx_expect]
  ∗ install lwt                 5.7.0   [required by dune-rpc-lwt]
  ∗ install dune-rpc            3.10.0*
  ∗ install dune-private-libs   3.10.0*
  ∗ install stdio               v0.16.0 [required by ppx_expect]
  ∗ install ppx_sexp_conv       v0.16.0 [required by ppx_base]
  ∗ install ppx_here            v0.16.0 [required by ppx_expect]
  ∗ install ppx_globalize       v0.16.0 [required by ppx_base]
  ∗ install ppx_enumerate       v0.16.0 [required by ppx_base]
  ∗ install ppx_compare         v0.16.0 [required by ppx_base]
  ∗ install ppx_cold            v0.16.0 [required by ppx_base]
  ∗ install dune-rpc-lwt        3.10.0*
  ∗ install dune-site           3.10.0*
  ∗ install dune-glob           3.10.0*
  ∗ install ppx_optcomp         v0.16.0 [required by time_now]
  ∗ install ppx_hash            v0.16.0 [required by ppx_base]
  ∗ install ppx_assert          v0.16.0 [required by jst-config]
  ∗ install ppx_base            v0.16.0 [required by time_now]
  ∗ install jst-config          v0.16.0 [required by time_now]
  ∗ install time_now            v0.16.0 [required by ppx_inline_test]
  ∗ install ppx_inline_test     v0.16.0 [required by ppx_expect]
  ∗ install ppx_expect          v0.16.0 [required by dune-action-plugin]
  ∗ install dune-action-plugin  3.10.0*
===== ∗ 44 =====
Do you want to continue? [Y/n] n
```

There we go! Finally, that's clearly all the deps needed. But, now, I have a bunch of undesired pins … also, it's going to try and compile the local project(s) themselves and install them, which I do not want.

----

So, three questions:

1. why did the initial `switch create` _not_ install all the packages that the subsequent `install` then did? (i.e. `seq, ocamlfind, base_bytes`)

2. why didn't the subsequent `install` actually install the deps of _all_ of the `*.opam` files in the named directory, as [indicated by the docs](https://github.com/ocaml/opam/blob/2453aa50d0ef0c49eb79815bfb0e522848dbc992/src/client/opamCommands.ml#L1713-L1718)?

3. is there _any_ way for me to install A. all the deps, of B. all of the `*.opam` files, C. in the current directory, D. without actually pinning/installing those packages themselves?

This may be intended behaviour; but at the least, the documentation could be improved — this doesn't feel like the combined, documented behaviour of `opam install <directory_name>` and `opam install --deps-only`. :O

<details>
<summary><code>opam config report</code></summary>

```
# opam config report
# opam-version         2.1.2 
# self-upgrade         no
# system               arch=x86_64 os=linux os-distribution=debian os-version=11
# solver               builtin-mccs+glpk
# install-criteria     -removed,-count[avoid-version,changed],-count[version-lag,request],-count[version-lag,changed],-count[missing-depexts,changed],-changed
# upgrade-criteria     -removed,-count[avoid-version,changed],-count[version-lag,solution],-count[missing-depexts,changed],-new
# jobs                 255
# repositories         2 (http), 5 (local) (default repo at b61304c6)
# pinned               0
# current-switch       /home/me/code/dune
# ocaml:native         true
# ocaml:native-tools   true
# ocaml:native-dynlink true
# ocaml:stubsdir       /home/me/code/dune/_opam/lib/ocaml/stublibs:/home/me/code/dune/_opam/lib/ocaml
# ocaml:preinstalled   false
# ocaml:compiler       5.1.0
```

</details>

**Comment by kit-ty-kate** [comment] 2023-09-19 12:05
I can reproduce the bug with 2.1 but I can't reproduce it with 2.2:
```
$ opam install . --deps-only --with-test
The following actions will be performed:
=== install 34 packages
  ∗ base                v0.16.3 [required by ppx_expect]
  ∗ base-bytes          base    [required by ocplib-endian]
  ∗ cppo                1.6.9   [required by lwt]
  ∗ csexp               1.5.2   [required by dune-rpc-lwt, dune-private-libs, dune-action-plugin, etc.]
  ∗ dune                3.10.0  [required by lwt, ppx_expect, csexp, etc.]
  ∗ dune-configurator   3.10.0  [required by lwt]
  ∗ jane-street-headers v0.16.0 [required by time_now]
  ∗ jst-config          v0.16.0 [required by time_now]
  ∗ lwt                 5.7.0   [required by dune-rpc-lwt]
  ∗ ocaml-compiler-libs v0.12.4 [required by ppxlib]
  ∗ ocamlfind           1.9.6   [required by base-bytes]
  ∗ ocplib-endian       1.2     [required by lwt]
  ∗ pp                  1.2.0   [required by dyn, dune-private-libs, dune-rpc, stdune]
  ∗ ppx_assert          v0.16.0 [required by jst-config]
  ∗ ppx_base            v0.16.0 [required by time_now]
  ∗ ppx_cold            v0.16.0 [required by ppx_base]
  ∗ ppx_compare         v0.16.0 [required by ppx_base]
  ∗ ppx_derivers        1.2.1   [required by ppxlib]
  ∗ ppx_enumerate       v0.16.0 [required by ppx_base]
  ∗ ppx_expect          v0.16.0 [required by dune-action-plugin]
  ∗ ppx_globalize       v0.16.0 [required by ppx_base]
  ∗ ppx_hash            v0.16.0 [required by ppx_base]
  ∗ ppx_here            v0.16.0 [required by ppx_expect]
  ∗ ppx_inline_test     v0.16.0 [required by ppx_expect]
  ∗ ppx_optcomp         v0.16.0 [required by time_now]
  ∗ ppx_sexp_conv       v0.16.0 [required by ppx_base]
  ∗ ppxlib              0.30.0  [required by ppx_expect]
  ∗ re                  1.11.0  [required by ppx_expect]
  ∗ result              1.5     [required by dune-rpc-lwt]
  ∗ seq                 base    [required by re]
  ∗ sexplib0            v0.16.0 [required by base]
  ∗ stdio               v0.16.0 [required by ppx_expect]
  ∗ stdlib-shims        0.3.0   [required by ppxlib]
  ∗ time_now            v0.16.0 [required by ppx_inline_test]
```
My guess is that it was fixed in https://github.com/ocaml/opam/pull/5236 or some of the similar PRs by @AltGr 

You can try the latest 2.2 release using the following command:
```
bash -c "sh <(curl -fsSL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh) --dev"
```

**Closed by kit-ty-kate** 2023-09-19 12:05 UTC
