### ISSUE TITLE
failing `opam pin add` commands doesn't try to uninstall

### ISSUE THREAD

**Issue by samoht** [ocaml/opam#2118] opened 2015-04-17 14:05 UTC
The typical usecase is when you develop a package locally, run `make && make install` and then decide to test the `opam` configuration by doing `opam pin add foo .`. In that case, `ocamlfind` will complain (rightly) that the library is already installed, but it will not try to clean it up.

**Comment by AltGr** [comment] 2015-04-20 03:01
Hm, indeed, that may be annoying ; preemptively running the remove instructions before installing a pinned package seems a bit overkill, though it should be safe in the current setting: we will run them anyway on the next reinstall.
This should be fixed in ocamlfind though: you have exactly the same problem with `make install`, unless you tweak your Makefile to run `ocamlfind remove` on install...

**Comment by samoht** [comment] 2015-04-20 20:22
> though it should be safe in the current setting: we will run them anyway on the next reinstall.

actually not! my feature request is to run the `uninstall` commands whenever the pin command fail.

**Comment by AltGr** [comment] 2015-04-21 00:35
Oh, sorry, I misunderstood -- indeed, I don't see why that shouldn't be the case, it's the normal procedure whenever any installation fails... I'll check.

**Comment by AltGr** [comment] 2016-08-30 12:43
I think this is a problem with the package's script (or ocamlfind) ; also, you shouldn't `opam install` to the opam switch without being ready for this kind of trouble. The main issue was caused by the fact that a failing install (once) in opam could cause many packages to get uninstalled.
Opam is now much safer regarding this, and will fail before removing any packages, and propose an easier way to restore in the worst case; so when this happens you will normally just have to retry.

This seems OK to me, and better than putting workarounds, which might have side-effects, in opam.

Please reopen if you disagree :)

**Closed by AltGr** 2016-08-30 12:43 UTC
Labels: KIND: FEATURE WISH, STATE: WON'T FIX
