### ISSUE TITLE
opam pin --dev is broken

### ISSUE THREAD

**Issue by Drup** [ocaml/opam#2934] opened 2017-05-12 19:31 UTC
This is an old one, I think, but it's still present in opam 2

Somehow, `pin --dev foo` and `pin foo <url in the dev field>` are not equivalent. If I understand the log right, I think the autodetection of vcs is wrong.

```
% opam pin --dev ocp-index
[ocp-index.1.1.5] downloaded from https://github.com/OCamlPro/ocp-index.git
ocp-index is now pinned to https://github.com/OCamlPro/ocp-index.git (version 1.1.5)

The following actions will be performed:
  ↻  recompile ocp-index 1.1.5*
Do you want to continue ? [Y/n] y
[ocp-index.1.1.5] downloaded from https://github.com/OCamlPro/ocp-index.git

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[ERROR] The compilation of ocp-index failed at "./configure --prefix /home/gabriel/.opam/4.03.0".

#=== ERROR while compiling ocp-index.1.1.5 ====================================#
# command      ./configure --prefix /home/gabriel/.opam/4.03.0
# path         /home/gabriel/.opam/4.03.0/.opam-switch/build/ocp-index.1.1.5
# exit-code    127
# env-file     /home/gabriel/.opam/log/ocp-index-2021-6cc03f.env
# output-file  /home/gabriel/.opam/log/ocp-index-2021-6cc03f.out

% opam pin add ocp-index https://github.com/OCamlPro/ocp-index.git            [master]
[ocp-index.1.1.5] synchronised from git+https://github.com/OCamlPro/ocp-index.git
[NOTE] Converting format of /home/gabriel/.opam/4.03.0/.opam-switch/sources/ocp-index/opam from 1.2 to 2.0~beta
ocp-index is now pinned to git+https://github.com/OCamlPro/ocp-index.git (version 1.1.5)

The following actions will be performed:
  ↻  recompile ocp-index 1.1.5*
Do you want to continue ? [Y/n] y
[ocp-index.1.1.5] synchronised from git+https://github.com/OCamlPro/ocp-index.git

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
⊘  removed   ocp-index.1.1.5
∗  installed ocp-index.1.1.5
Done.
```

```
% opam --git-version
9d7b01b90ed28582e062a5a26f7a27d40a5d497c
```

**Comment by AltGr** [comment] 2017-06-15 14:14
This is actually new from `2.0` I think (well `1.3` to be exact).
The reason is that when parsing from the command-line, the `.git` suffix is undestood and magically makes the `git` backend to be chosen. When parsing from the file, though, doing this magic would be incorrect. If we were doing it, `opam pin foo https://foo.bar/toto.git -k http` would only work until the end of the current invocation.

I am not sure how to improve. The rewrite from 1.2 to 2.0 is doing the magic (it seems that was not the case for you though ? https://opam.ocaml.org/2.0/packages/ocp-index/ocp-index.1.1.5/opam is correct...) There is also a lint warning (49: `"The following URLs don't use version control but look like version control URLs"`).

**Comment by AltGr** [comment] 2017-07-04 10:40
Closing, as this is not a bug: it's a problem in the `dev-repo:` field of the package, and there is already a lint check to detect it.

**Closed by AltGr** 2017-07-04 10:40 UTC
Labels: AREA: UI

**Comment by Drup** [comment] 2017-07-04 11:29
To be honest, I'm not sure I'm really satisfied by that answer. First, I got the issue on many ocasion, so either the migration scripts are buggy or there is something else). Second, from a user perspective, I would really expect the file and the CLI to have the exact same API. If there is a -k flag on the CLI, then add a kind flag to disambiguate one way or another.

**Comment by AltGr** [comment] 2017-07-04 12:17
In any case, I can confirm that the general problem is fixed:
```
% opam pin --dev ocp-index --sw /tmp/xx
[ocp-index.1.1.5] synchronised from git+https://github.com/OCamlPro/ocp-index.git
[NOTE] Converting format of /tmp/xx/_opam/.opam-switch/sources/ocp-index/ocp-index.opam from 1.2 to 2.0~beta
ocp-index is now pinned to git+https://github.com/OCamlPro/ocp-index.git (version 1.1.6)
```

**Comment by Drup** [comment] 2017-07-04 13:44
Fair enough, then let's pursue in https://github.com/ocaml/opam/issues/2984 :)
