### ISSUE TITLE
opam, ipv6 and https://opam.ocaml.org

### ISSUE THREAD

**Issue by swsch** [ocaml/opam#1182] opened 2014-02-16 22:53 UTC
While trying the export/import feature of opam to replicate my setup on another box, I found that sometimes packages would not install due to a network problem. Well, wget is your friend:

    stefan@tuxedo archives % wget 'https://opam.ocaml.org/archives/cpdf.1.7+opam.tar.gz'
    --2014-02-16 23:26:20--  https://opam.ocaml.org/archives/cpdf.1.7+opam.tar.gz
    Resolving opam.ocaml.org... 2001:4801:7823:76:bb74:1f8e:ff10:627, 192.237.250.17
    Connecting to opam.ocaml.org|2001:4801:7823:76:bb74:1f8e:ff10:627|:443... failed: Connection refused.
    Connecting to opam.ocaml.org|192.237.250.17|:443... connected.
    HTTP request sent, awaiting response... 200 OK
    Length: 289428 (283K) [application/octet-stream]
    Saving to: ‘cpdf.1.7+opam.tar.gz’
    
    100%[===================================================>] 289,428      413KB/s   in 0.7s   
    
    2014-02-16 23:26:22 (413 KB/s) - ‘cpdf.1.7+opam.tar.gz’ saved [289428/289428]

So I added the IPv4 address to /etc/hosts and all is well for now.

I realise that it's not opam's fault that the repo server does not handle requests to its ipv6 address, but maybe opam could be made to behave like wget and try all addresses returned by the DNS resolver?

**Comment by dnaumov** [comment] 2015-01-12 03:15
The issue is still present and requires adding ipv4 address to hosts file. Could something be done with it? It was quite confusing for me as a newcomer to experience such a problem.

**Comment by AltGr** [comment] 2015-02-03 05:48
Fixed by https://github.com/ocaml/opam.ocaml.org/commit/20c40790c7951a3d5923391ff23cad5031419f7f

As for trying all IP addresses returned, I didn't seem to find an option in curl to do that ; but isn't it considered bad practice ?

**Closed** 2016-08-31 09:19 UTC
Labels: KIND: FEATURE WISH
