### ISSUE TITLE
External solver failed with inconsistent return value on Arch Linux

### ISSUE THREAD

**Issue by angrygoats** [ocaml/opam#2203] opened 2015-06-17 15:18 UTC
Hey everyone. I ran into https://github.com/ocaml/opam/issues/1273 while trying to fix this problem and I'm not exactly sure what to do, who to file a bug with, or anything about the solver in general. I'm just trying to get things working so I can work my way through Real World OCaml. I suspect it is a bad mix of aspcud, clasp, and gringo, but I'm running Arch Linux so homebrew isn't the problem (unlike the other post). 

_CUDF file_
http://s000.tinyupload.com/?file_id=04046394928238958812

_Opam config report_
http://s000.tinyupload.com/?file_id=50862748621275713669

Finally, a paranoid aspcud check on the cudf results in

```
aspcud solver-error28656-1.cudf paranoid
clasp version 3.1.2
Reading from /tmp/gringo.out40xfWt
solving...
```

And that's it.

I would really appreciate any help. Thank you!

**Comment by Drup** [comment] 2015-06-17 16:44
See https://github.com/ocaml/opam/issues/2176

**Comment by angrygoats** [comment] 2015-06-17 17:15
@Drup How do I downgrade just gringo? Is that done through yaourt or opam? Seems that is the suggested solution.

**Comment by Drup** [comment] 2015-06-17 17:34
That's the whole issue. yaourt/pacman doesn't support multiple versions. :/

**Comment by angrygoats** [comment] 2015-06-18 01:06
@Drup Is the internal solver sufficient? Im not even sure what it does.

**Comment by choeger** [comment] 2015-06-18 12:45
I found the solution: Compile clasp using clang instead of gcc. That will work.

**Comment by gfrey** [comment] 2015-06-21 15:45
Thx @choeger for the clang hint (even gringo 4.5.0 is working).

For the record: use `./configure.sh --prefix='/usr' CXX=clang++` in clasp's PKGBUILD.

**Comment by vbmithr** [comment] 2015-06-27 07:43
Cool, I'm updating Arch's clasp package to use clang++ then. Does the other packages need to be compiled with clang also ?

**Comment by vbmithr** [comment] 2015-06-27 08:04
Fixed in AUR4: https://aur4.archlinux.org/packages/clasp

**Comment by gfrey** [comment] 2015-06-27 09:46
I just modified the clasp PKGBUILD so nothing else should need to be changed.

**Comment by vbmithr** [comment] 2015-06-27 09:52
On 27/06/2015 11:46, Gereon Frey wrote:
> I just modified the clasp PKGBUILD so nothing else should need to be
> changed.

Ok, thanks, updated!

-- 
Vincent

**Comment by agravier** [comment] 2015-10-10 22:15
I'm like @angrygoats, trying to set up my dev environment for "real world OCaml", and I face the same error despite
@gfrey's changes to the PKGBUILD of clasp

**Comment by AltGr** [comment] 2015-10-11 15:03
See also the possibility to use solvers other than aspcud:
http://opam.ocaml.org/doc/Install.html#ExternalSolvers

If you can install it easily, packup should work out of the box.

**Comment by agravier** [comment] 2015-10-13 12:34
Thanks @AltGr. My problem solved itself somehow, I suspect that I was actually out of memory.

**Comment by dudelson** [comment] 2017-06-09 23:55
This issue cropped up again, but the solution is the same. It looks like clasp and gringo have (as of a few months ago) been merged into a single package clingo. If clingo is not compiled with clang, opam will fail when it invokes the external solver. I've submitted an [issue](https://bugs.archlinux.org/task/54393) to the arch bugtracker, but for now it is possible to resolve the issue by building clingo from source and adding "-DCMAKE_CXX_COMPILER=clang++" to the cmake command in the PKGBUILD.

Feel free to close this again.

**Comment by AltGr** [comment] 2017-06-14 08:52
@dudelson thanks a lot for the info and solution!

**Comment by xyproto** [comment] 2017-06-23 12:25
@dudelson What are the steps to reproduce the issue on Arch Linux? I'm maintaining `clingo` and `clasp` and need a way to check that it's working if I repackage and compile them with `clang++` instead of with GCC.

**Comment by vbmithr** [comment] 2017-06-23 13:43
For what it is worth, it worked for me. In my case, I did not witness a crash of clasp/gringo while using opam, but they were apparently returning absurd values since the dependency analysis was insane in opam. 

I don't think there is an easy way to assert it if works or not, but I would safely repackage clingo to be compiled by clang++.

Best

**Comment by xyproto** [comment] 2017-06-23 15:26
@vbmithr I'm unable to reproduce the issue on Arch Linux. Do you have the steps?

**Comment by vbmithr** [comment] 2017-06-23 15:38
I can prepare it, I need to extract the command from opam…

**Comment by AltGr** [comment] 2017-06-23 15:54
To reproduce the opam call:
- get the `foo-1.cudf` file from running the problematic opam command with `--cudf foo`, or the one from [the OP](http://s000.tinyupload.com/?file_id=04046394928238958812);
- get `aspcud` installed
- run `aspcud foo-1.cudf /dev/stdout "$CRITERIA"`
- the default value for CRITERIA is `-count(removed),-notuptodate(request),-sum(request,version-lag),-count(down),-notuptodate(changed),-count(changed),-notuptodate(solution),-sum(solution,version-lag)`

**Comment by vbmithr** [comment] 2017-06-23 17:28
Yeah, so please test with http://luminar.eu.org/~vb/test.cudf

`aspcud test.cudf /dev/stdout "$CRITERIA"` where CRITERIA is described above.

**Comment by dudelson** [comment] 2017-06-23 20:07
FWIW I tried to reproduce in a fresh arch install and I couldn't. Not sure how to go about determining what's different about my local environment (where the bug occurred). Please let me know what info about my system I can provide.

**Comment by vbmithr** [comment] 2017-06-24 07:41
Le 23/06/2017 à 22:08, David Udelson a écrit :
> FWIW I tried to reproduce in a fresh arch install and I couldn't. Not
> sure how to go about determining what's different about my local
> environment (where the bug occurred). Please let me know what info about
> my system I can provide.

I never had a crash like you, however, aspcud was returning somehow bad
results that were not optimal at all for opam (similar to when you use
opam without aspcud).

-- 
Vincent

**Comment by bmillwood** [comment] 2017-06-24 11:53
I have had both crashes and bad results. When I run @vbmithr's test command, I get some output that ends in FAIL but an exit code of 0. I wonder if that's what it means by "inconsistent return value"?

Is that what you see?

**Comment by bmillwood** [comment] 2017-06-24 12:34
On further examination, I don't think the exit code is relevant (although I can't completely rule it out).

**Comment by pqwy** [comment] 2017-07-07 02:35
+1 hit the bug, https://github.com/ocaml/opam/issues/2203#issuecomment-307526541 solves it. Symptom is that opam starts spitting out completely erratic solutions.

@xyproto 

Repro:

1) Get http://www.cl.cam.ac.uk/~dk505/pub/error.cudf.
2) Run
    ```
    P='-count(removed),-notuptodate(request),-sum(request,version-lag),-count(down),-notuptodate(changed),-count(changed),-notuptodate(solution),-sum(solution,version-lag)'
    aspcud error.cudf /dev/stdout "$P" | grep UNSATISFIABLE
    ```

Using `clingo-5.2.0-2` from the repo, this prints `UNSATISFIABLE`.

Using clingo compiled from that same `PKGBUILD`, with `-DCMAKE_CXX_COMPILER=clang++` added to cmake params, this prints nothing. And in fact aspcud spits out a solution.

**Comment by xyproto** [comment] 2017-07-07 12:02
@pqwy Thanks, will update the package to use the `clang++` workaround.

**Comment by xyproto** [comment] 2017-07-07 12:31
@pqwy Using `-DCMAKE_CXX_COMPILER=clang++` does not work when compiling for i686, there are several `undefined reference to `__atomic_load_8'` errors.

**Comment by Drup** [comment] 2017-07-07 15:57
@xyproto Then just flag it for x86 only for now. It's better than keeping something that has been broken for more than a month.

At this point, this is a bit tiring. This issue explodes in the face of all the OCaml newcomers that work on arch and makes opam completely unusable. The fix was provided a month ago and is not very invasive. Multiple people can reproduce. Just apply the bandaid as quick as possible and let's worry about unfucking aspcud/clingo later.

**Comment by xyproto** [comment] 2017-07-07 16:00
@Drup The Arch way is to let upstream fix upstream problems. i686 will be dropped in November, but until then, it's a supported architecture, just like x86_64.

**Comment by Drup** [comment] 2017-07-07 16:15
Ok, then remove the last version of the package. It is *BROKEN*. Since the new version of the package, everyone using the OCaml package manager has to recompile clingo by itself because it just doesn't work.

One way or another, the situation has to change, because the current situation is causing issues for the whole OCaml community on Arch.

**Comment by xyproto** [comment] 2017-07-07 16:20
Dropping it to AUR was an option, but I ended up removing the i686 package (temporarily). I like OCaml. The updated package in [community] (will appear shortly) should resolve the issue, since it's built with `clang++`.

**Comment by Drup** [comment] 2017-07-07 16:36
Thanks @xyproto, and sorry for the slightly aggressive tone, the situation was getting a little bit frustrating. :)

Btw, I just noticed that most of the potassco stuff, including clingo, are now [on github](https://github.com/potassco/clingo) instead of sourceforce.

**Comment by pqwy** [comment] 2017-07-07 16:38
Not to trample over one another, who's opening the issue there? 😃

**Comment by xyproto** [comment] 2017-07-07 16:44
@Drup clingo is now built from sources fetched from github, and no worries!

@angrygoats Does it work for you on Arch Linux now?

**Comment by rneswold** [comment] 2017-07-18 18:38
_@Drup wrote_:
> Thanks @xyproto, and sorry for the slightly aggressive tone, the situation was getting a little bit frustrating. :)

No need to apologize. I think a little aggression may encourage a solution to be found. I enjoy using OCaml and OPAM has been a fantastic tool to install and maintain 3rd party modules. The weakest link is the solver: I can't permanently configure OPAM to use a particular solver because there always seems to be a repository state that each can't solve. So I have to override it. When should I stop overriding it? Who knows? Usually when the new solver breaks.

Hopefully 2.0 makes these issues a thing of the past.

**Comment by AltGr** [comment] 2017-09-25 10:41
The specific issue has been solved, and opam no longer uses aspcud by default ☺

**Closed by AltGr** 2017-09-25 10:41 UTC
