### ISSUE TITLE
wrong dependency determination

### ISSUE THREAD

**Issue by agarwal** [ocaml/opam#2960] opened 2017-06-08 18:57 UTC
I have an internal package called `solvuu-jbuild`. I just requested a remove and got this surprising result:
```
$ opam remove solvuu-jbuild
The following actions will be performed:
  ∗  install   base-num          base  
  ⊘  remove    solvuu-jbuild     dev*  
  ...
  ↻  recompile core              v0.9.1       [uses solvuu-jbuild]
  ...
===== ∗  2   ↻  65   ⊘  1 =====
Do you want to continue ? [Y/n] n
```
I'm often perplexed at opam's determination of what needs to be recompiled. Here is an example that is clear and definitely wrong. Obviously Jane Street's `core` does not depend on my internal unreleased package.

**Comment by samoht** [comment] 2017-06-08 19:21
Which solver are you using?

**Comment by yomimono** [comment] 2017-06-08 20:28
I think a recent change with how dependency on `num` or `base-num` is expressed is to blame here -- I had a similarly surprising solution to an operation recently which had nothing to do with the operation itself, it was just a side-effect of being the first invocation of `opam` after an update that implied `base-num` needed to be installed.

**Comment by agarwal** [comment] 2017-06-08 20:51
> Which solver are you using?

I'm on Mac OS and have `aspcud` installed via homebrew. So presumably opam uses it, but I'm not sure how to confirm that.

**Comment by dbuenzli** [comment] 2017-06-08 20:59
`opam config report`

**Comment by agarwal** [comment] 2017-06-09 14:21
```
$ opam config report
# OPAM config report
# opam-version    1.2.2 
# self-upgrade    no
# os              darwin
# external-solver aspcud $in $out $criteria
# criteria        -count(removed),-notuptodate(request),-sum(request,version-lag),-count(down),-notuptodate(changed),-count(changed),-notuptodate(solution),-sum(solution,version-lag)
# jobs            4
# repositories    1* (http)
# pinned          14 (path)
# current-switch  4.03.0
# last-update     2017-06-08 17:55
```

**Comment by avsm** [comment] 2017-06-11 16:39
Something seems to have gone wrong fairly recently in the repository -- see also https://discuss.ocaml.org/t/opam-insists-on-downgrades-because-of-ocamlfind/389/7

**Comment by AltGr** [comment] 2017-06-14 15:42
I just fixed printing reasons for reinstallations (when caused by upstream changes) in opam 2.
The options `opam reinstall --list-pending|--forget-pending` have also been added a while ago to give some visibility into packages internally marked for reinstall (that can happen for pinned packages, or repository packages when their definition changed in a significant way). Recently that was the case of `sexplib`, which caused a lot of reinstalls which weren't properly documented.

Now `core              v0.9.1       [uses solvuu-jbuild]` is quite surprising indeed: that could normally not happen unless there is an edge linking the two in our graph of actions. Using the `--cudf foo` argument would dump the corresponding graph and may help debugging.

One last note, because the solver acts like a black box, the reasons are processed _a posteriori_, using the known relationships between the packages and the requested actions. So this is not related to what solver is used, and can be completely off if you use exotic solver criteria. Remains that plain wrong package relationships are not supposed to be printed. (recompilations aren't computed by the solver, anyway)

**Comment by Drup** [comment] 2017-06-16 20:49
I'm pretty sure this (and the one on discuss) is a fairly obfuscated duplicate of https://github.com/ocaml/opam/issues/2203. A solution is provided at the end.

The clingo Arch package was modified recently and is not compiled with clang by default, I had the exact same syndromes and solved them by applying the above fix.

**Comment by samoht** [comment] 2017-06-19 08:02
@Drup the issue seems to be reported for a different OS thought :-)

```
# os              darwin
```

**Comment by AltGr** [comment] 2017-09-27 13:23
Closing without further info since, I am fairly confident this has been fixed. Thanks for reporting!

**Closed by AltGr** 2017-09-27 13:23 UTC

**Comment by agarwal** [comment] 2018-11-08 19:14
I was reminded of this issue because today I got this:
```
$ opam remove github
The following actions will be performed:
  ∗ install   ocaml-config               1            [required by ocaml]
  ⊘ remove    github                     3.1.0
  ↻ recompile ocaml                      4.06.1       [uses github]
... recompile another 170 packages
```

**Comment by samoht** [comment] 2018-11-09 09:11
I think this is related to https://github.com/ocaml/opam-repository/pull/12832 /cc @dra27

**Comment by dra27** [comment] 2018-11-09 10:02
@agarwal - opam's behaving correctly here. The `ocaml` package has been updated and it has a new dependency called `ocaml-config` - that will (correctly) cause all packages to recompile. See [the Discuss announcement](https://discuss.ocaml.org/t/dont-panic-that-your-opam-switches-recompile-from-today/2816).

As it happens, it has revealed a different bug in the solver, see #3670!

**Comment by agarwal** [comment] 2019-03-19 13:43
@dra27 Thanks for the explanation. It wasn't clear why `github` had to be removed, but I guess saying `"requires ocaml"` is overkill. So okay, this was fine.
