### ISSUE TITLE
Unable to install on Ubuntu on Windows 10 

### ISSUE THREAD

**Issue by abhi18av** [ocaml/opam#3602] opened 2018-10-12 14:24 UTC
Hi OCaml team,

I read here ( https://opam.ocaml.org/doc/Install.html ) that we can use `opam` in the `ubuntu on windows` shell but when I try to install it throws the following error

```sh
abhi18av@LAPTOP-CI3GR8DQ:~$ opam init
[NOTE] Will configure from built-in defaults.
Checking for available remotes: rsync and local, git.
  - you won't be able to use mercurial repositories unless you install the hg command on your system.
  - you won't be able to use darcs repositories unless you install the darcs command on your system.


<><> Fetching repository information ><><><><><><><><><><><><><><><><><><><><><>
[default] Initialised

<><> Required setup - please read <><><><><><><><><><><><><><><><><><><><><><><>

  In normal operation, opam only alters files within ~/.opam.

  However, to best integrate with your system, some environment variables
  should be set. If you allow it to, this initialisation step will update
  your bash configuration by adding the following line to ~/.profile:

    test -r /home/abhi18av/.opam/opam-init/init.sh && . /home/abhi18av/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true

  Otherwise, every time you want to access your opam installation, you will
  need to run:

    eval $(opam env)

  You can always re-run this setup with 'opam init' later.

Do you want opam to modify ~/.profile? [N/y/f]
(default is 'no', use 'f' to choose a different file) y
A hook can be added to opam's init scripts to ensure that the shell remains in sync with the opam environment when they are loaded. Set that
up? [y/N] y

User configuration:
  Updating ~/.profile.
[NOTE] Make sure that ~/.profile is well sourced in your ~/.bashrc.



<><> Creating initial switch (ocaml-base-compiler) ><><><><><><><><><><><><><><>

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ocaml-base-compiler.4.07.1] downloaded from cache at https://opam.ocaml.org/cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
∗ installed base-bigarray.base
∗ installed base-threads.base
∗ installed base-unix.base
[ERROR] The compilation of ocaml-base-compiler failed at "/home/abhi18av/.opam/opam-init/hooks/sandbox.sh build ./configure -prefix
        /home/abhi18av/.opam/default -with-debug-runtime".

#=== ERROR while compiling ocaml-base-compiler.4.07.1 =========================#
# context     2.0.0 | linux/x86_64 |  | https://opam.ocaml.org#8112c106
# path        ~/.opam/default/.opam-switch/build/ocaml-base-compiler.4.07.1
# command     ~/.opam/opam-init/hooks/sandbox.sh build ./configure -prefix /home/abhi18av/.opam/default -with-debug-runtime
# exit-code   1
# env-file    /tmp/opam-xxx-5940/ocaml-base-compiler-5940-f0f09f.env
# output-file /tmp/opam-xxx-5940/ocaml-base-compiler-5940-f0f09f.out
### output ###
# bwrap: Creating new namespace failed: Invalid argument



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build ocaml-base-compiler 4.07.1
└─
┌─ The following changes have been performed (the rest was aborted)
│ ∗ install base-bigarray base
│ ∗ install base-threads  base
│ ∗ install base-unix     base
└─
# Run eval $(opam env) to update the current shell environment
Switch initialisation failed: clean up? ('n' will leave the switch partially installed) [Y/n] n
abhi18av@LAPTOP-CI3GR8DQ:~$
```

Here's my `opam config report` output 

```abhi18av@LAPTOP-CI3GR8DQ:~$ opam config report
# opam config report
# opam-version      2.0.0
# self-upgrade      no
# system            arch=x86_64 os=linux os-distribution=ubuntu os-version=18.04
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              7
# repositories      1 (http) (default repo at 8112c106)
# pinned            0
# current-switch    default
abhi18av@LAPTOP-CI3GR8DQ:~$
```

**Comment by avsm** [comment] 2018-10-12 14:31
please delete the `~/.opam` directory and try again with `opam init --disable-sandboxing`

**Comment by mseri** [comment] 2018-10-12 15:02
This is a duplicate of https://github.com/ocaml/opam/issues/3505

**Comment by abhi18av** [comment] 2018-10-12 15:28
@avsm thanks 👍 

However, after successfully installing `utop` and other libraries I ran into the following error 

```
abhi18av@LAPTOP-CI3GR8DQ:~$ utop
Fatal error: cannot load shared library dlllwt_unix_stubs
Reason: dlllwt_unix_stubs.so: cannot open shared object file: No such file or directory

```

Is this an `ubuntu-on-windows` problem ?

**Comment by dra27** [comment] 2021-07-13 16:15
This looks like a possible issue with the environment, but I'm going to close it for now in the hope that you worked around it! Please re-open if it's still an issue.

**Closed by dra27** 2021-07-13 16:15 UTC
