### ISSUE TITLE
opam install coqide ERROR

### ISSUE THREAD

**Issue by jiawenliu** [ocaml/opam#3968] opened 2019-08-26 22:06 UTC
>   If your issue concerns a package not building, please report to
>   https://github.com/ocaml/opam-repository/issues or to the package maintainer
>   unless you are confident it is an issue in the opam tool itself.

```
<include here the output of `opam config report`, if applicable>
```
```
pam install coqide
The following actions will be performed:
  ∗ install num    1.2   [required by coq]
  ∗ install coq    8.9.1 [required by coqide]
  ∗ install coqide 8.9.1
===== ∗ 3 =====
Do you want to continue? [Y/n] y

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
[coq.8.9.1] found in cache
[coqide.8.9.1] found in cache
[num.1.2] found in cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
[ERROR] The installation of num failed at "make findlib-install".

#=== ERROR while installing num.1.2 ===========================================#
# context     2.0.5 | macos/x86_64 | ocaml-system.4.07.1 | https://opam.ocaml.org#c8e375c5
# path        ~/opam-coq.8.8.1/default/.opam-switch/build/num.1.2
# command     ~/opam-coq.8.8.1/opam-init/hooks/sandbox.sh install make findlib-install
# exit-code   2
# env-file    ~/opam-coq.8.8.1/log/num-72741-335865.env
# output-file ~/opam-coq.8.8.1/log/num-72741-335865.out
### output ###
# [ERROR] It appears that the num library was previously installed to your system
#         compiler's lib directory, probably by a faulty opam package.
#         You will need to remove arith_flags.*, arith_status.*, big_int.*,
#         int_misc.*, nat.*, num.*, ratio.*, nums.*, libnums.* and
#         stublibs/dllnums.* from /usr/local/lib/ocaml.
# make: *** [findlib-install] Error 1



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
┌─ The following actions failed
│ ∗ install num 1.2
└─ 
╶─ No changes have been performed
```
_rjbou_: edit format

**Comment by dra27** [comment] 2019-08-27 07:48
Duplicate of https://github.com/ocaml/opam-repository/issues/14646

**Comment by dra27** [comment] 2019-08-27 07:50
I believe running `brew remove ocaml-num` should fix the problem by allowing you to install opam-repository's `num` package instead.

Please try to pay attention to the message on the issue tracker: "If your issue concerns a package not building, please report to https://github.com/ocaml/opam-repository/issues" :wink:

**Comment by JiawenUB** [comment] 2019-09-17 18:31
> brew remove ocaml-num

it show that:

 Refusing to uninstall /usr/local/Cellar/ocaml-num/1.2_1
because it is required by coq, which is currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies ocaml-num

**Comment by rjbou** [comment] 2019-10-08 18:10
Duplicate, closing.
Thanks!

**Closed by rjbou** 2019-10-08 18:10 UTC

**Comment by xiuxiu0907** [comment] 2020-10-13 19:11
I got the same problem when I tried `opam install coq-metacoq` and it was solved by
```
ocamlfind remove num
ocamlfind remove num-top
```
