### ISSUE TITLE
opam install cudf > debug failed  => address space needed by 'dllunix.so' (0x400000) is already occupied

### ISSUE THREAD

**Issue by CarpeDiemKopi** [ocaml/opam#3953] opened 2019-08-11 21:20 UTC
windows 10
CygWin64 

```
Charleen@ROY /cygdrive/d/development/ocaml/home/Charleen/.opam/ocaml-4.08.1
$ opam install cudf > debug

Charleen@ROY /cygdrive/d/development/ocaml/home/Charleen/.opam/ocaml-4.08.1
$ opam install cudf --debug
00:00.015  GSTATE                 LOAD-GLOBAL-STATE @ /home/Charleen/.opam
00:00.038  RSTATE                 LOAD-REPOSITORY-STATE @ /home/Charleen/.opam
00:00.223  RSTATE                 Loaded /home/Charleen/.opam/repo/state.cache in 0.183s
00:00.284  RSTATE                 Cache found
00:00.284  STATE                  LOAD-SWITCH-STATE @ /cygdrive/d/development/ocaml/home/Charleen/.opam/ocaml-4.08.1
00:00.383  STATE                  Detected changed packages (marked for reinstall): {}
00:00.395  STATE                  Switch state loaded in 0.111s
00:00.575  FILE(switch-state)     Wrote /cygdrive/d/development/ocaml/home/Charleen/.opam/ocaml-4.08.1/_opam/.opam-switch/backup/state-20190811211320.export in 0.179s
00:00.755  CLIENT                 INSTALL cudf
00:01.573  GSTATE                 Failed to evaluate global variable sys-ocaml-version: "ocamlc": command not found.
00:01.749  CLIENT                 Orphans: (changes: { cudf.0.6.3, cudf.0.7, cudf.0.8, cudf.0.9 }, transitive: false) -> full {}, versions {}
00:02.427  SOLVER                 resolve request=install:(cudf) remove:() upgrade:()
00:03.922  SOLVER                 Load cudf universe (depopts:false, build:true, post:true)
00:03.983  FILTER                 ERR: value_bool: "/cygdrive/d/development/ocaml/home/Charleen/.opam/ocaml-4.08.1/_opam/doc"
00:03.983  FILTER                 ERR: value_bool: "/cygdrive/d/development/ocaml/home/Charleen/.opam/ocaml-4.08.1/_opam/doc"
00:04.014  FILTER                 ERR: value_bool: "/cygdrive/d/development/ocaml/home/Charleen/.opam/ocaml-4.08.1/_opam/doc"
00:04.014  FILTER                 ERR: value_bool: "/cygdrive/d/development/ocaml/home/Charleen/.opam/ocaml-4.08.1/_opam/doc"
00:04.015  FILTER                 ERR: value_bool: "/cygdrive/d/development/ocaml/home/Charleen/.opam/ocaml-4.08.1/_opam/doc"
00:04.015  FILTER                 ERR: value_bool: "/cygdrive/d/development/ocaml/home/Charleen/.opam/ocaml-4.08.1/_opam/doc"
00:04.029  FILTER                 ERR: value_bool: "/cygdrive/d/development/ocaml/home/Charleen/.opam/ocaml-4.08.1/_opam/doc"
00:04.092  CUDF                   resolve request=install:(cudf) remove:() upgrade:()
00:04.092  SOLVER                 Calling solver builtin-mccs+glpk with criteria -removed,-count[version-lag,request],-count[version-lag,changed],-changed
00:04.379  CUDF                   Solver call done in 0.287
00:04.417  SOLVER                 Load cudf universe (depopts:true, build:false, post:false)
00:04.520  FILTER                 ERR: value_bool: "/cygdrive/d/development/ocaml/home/Charleen/.opam/ocaml-4.08.1/_opam/doc"
00:04.520  FILTER                 ERR: value_bool: "/cygdrive/d/development/ocaml/home/Charleen/.opam/ocaml-4.08.1/_opam/doc"
00:04.546  FILTER                 ERR: value_bool: "/cygdrive/d/development/ocaml/home/Charleen/.opam/ocaml-4.08.1/_opam/doc"
00:04.546  FILTER                 ERR: value_bool: "/cygdrive/d/development/ocaml/home/Charleen/.opam/ocaml-4.08.1/_opam/doc"
00:04.546  FILTER                 ERR: value_bool: "/cygdrive/d/development/ocaml/home/Charleen/.opam/ocaml-4.08.1/_opam/doc"
00:04.546  FILTER                 ERR: value_bool: "/cygdrive/d/development/ocaml/home/Charleen/.opam/ocaml-4.08.1/_opam/doc"
00:04.562  FILTER                 ERR: value_bool: "/cygdrive/d/development/ocaml/home/Charleen/.opam/ocaml-4.08.1/_opam/doc"
00:04.631  SOLVER                 Load cudf universe (depopts:true, build:true, post:false)
00:04.709  FILTER                 ERR: value_bool: "/cygdrive/d/development/ocaml/home/Charleen/.opam/ocaml-4.08.1/_opam/doc"
00:04.709  FILTER                 ERR: value_bool: "/cygdrive/d/development/ocaml/home/Charleen/.opam/ocaml-4.08.1/_opam/doc"
00:04.732  FILTER                 ERR: value_bool: "/cygdrive/d/development/ocaml/home/Charleen/.opam/ocaml-4.08.1/_opam/doc"
00:04.732  FILTER                 ERR: value_bool: "/cygdrive/d/development/ocaml/home/Charleen/.opam/ocaml-4.08.1/_opam/doc"
00:04.732  FILTER                 ERR: value_bool: "/cygdrive/d/development/ocaml/home/Charleen/.opam/ocaml-4.08.1/_opam/doc"
00:04.732  FILTER                 ERR: value_bool: "/cygdrive/d/development/ocaml/home/Charleen/.opam/ocaml-4.08.1/_opam/doc"
00:04.743  FILTER                 ERR: value_bool: "/cygdrive/d/development/ocaml/home/Charleen/.opam/ocaml-4.08.1/_opam/doc"
00:04.808  CUDF                   graph_of_actions root_actions={  - ∗ extlib (= 12),  - ∗ dune (= 40),  - ∗ cudf (= 4),  - ∗ cppo (= 21) }
00:04.826  SOLUTION               apply
The following actions will be performed:
  ∗ install dune   1.11.0 [required by cppo]
  ∗ install cppo   1.6.6  [required by extlib]
  ∗ install extlib 1.7.6  [required by cudf]
  ∗ install cudf   0.9
===== ∗ 4 =====
Do you want to continue? [Y/n] Y
00:14.505  SOLUTION               parallel_apply

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
00:14.505  PARALLEL               Iterate over 12 task(s) with 7 process(es)
00:14.505  PARALLEL               Starting job 591019265 (worker -/7 -/1 1/3): ⬇ cppo.1.6.6
00:14.506  SOLUTION               Fetching sources for cppo.1.6.6
00:14.506  ACTION                 download_package: cppo.1.6.6
00:14.506  SYSTEM                 rmdir /cygdrive/d/development/ocaml/home/Charleen/.opam/ocaml-4.08.1/_opam/.opam-switch/sources/cppo.1.6.6
00:15.563  FILENAME               cleandir /cygdrive/d/development/ocaml/home/Charleen/.opam/ocaml-4.08.1/_opam/.opam-switch/sources/cppo.1.6.6
00:15.564  SYSTEM                 mkdir /cygdrive/d/development/ocaml/home/Charleen/.opam/ocaml-4.08.1/_opam/.opam-switch/sources/cppo.1.6.6
00:15.565  SYSTEM                 mkdir /tmp/opam-5602-ccabea
00:15.804  PARALLEL               Next task in job 591019265: /usr/bin/tar xfj /home/Charleen/.opam/download-cache/sha256/e7/e7272996a7789175b87bb998efd079794a8db6625aae990d73f7b4484a07b8a0 -C /tmp/opam-5602-ccabea
Processing  1/12:
00:15.951  PARALLEL               Starting job 362414859 (worker -/7 -/1 2/3): ⬇ cudf.0.9
00:15.952  SOLUTION               Fetching sources for cudf.0.9
00:15.952  ACTION                 download_package: cudf.0.9
00:15.953  SYSTEM                 rmdir /cygdrive/d/development/ocaml/home/Charleen/.opam/ocaml-4.08.1/_opam/.opam-switch/sources/cudf.0.9
00:16.213  FILENAME               cleandir /cygdrive/d/development/ocaml/home/Charleen/.opam/ocaml-4.08.1/_opam/.opam-switch/sources/cudf.0.9
00:16.214  SYSTEM                 mkdir /cygdrive/d/development/ocaml/home/Charleen/.opam/ocaml-4.08.1/_opam/.opam-switch/sources/cudf.0.9
00:16.215  SYSTEM                 mkdir /tmp/opam-5602-7afd23
00:16.461  PARALLEL               Next task in job 362414859: /usr/bin/tar xfz /home/Charleen/.opam/download-cache/md5/a4/a4c0e652e56e74c7b388a43f9258d119 -C /tmp/opam-5602-7afd23
Processing  2/12:
00:16.624  PARALLEL               Starting job 140570751 (worker -/7 -/1 3/3): ⬇ dune.1.11.0
00:16.625  SOLUTION               Fetching sources for dune.1.11.0
00:16.625  ACTION                 download_package: dune.1.11.0
00:16.626  SYSTEM                 rmdir /cygdrive/d/development/ocaml/home/Charleen/.opam/ocaml-4.08.1/_opam/.opam-switch/sources/dune.1.11.0
00:20.123  FILENAME               cleandir /cygdrive/d/development/ocaml/home/Charleen/.opam/ocaml-4.08.1/_opam/.opam-switch/sources/dune.1.11.0
00:20.124  SYSTEM                 mkdir /cygdrive/d/development/ocaml/home/Charleen/.opam/ocaml-4.08.1/_opam/.opam-switch/sources/dune.1.11.0
00:20.125  SYSTEM                 mkdir /tmp/opam-5602-1872ec
00:20.344  PARALLEL               Next task in job 140570751: /usr/bin/tar xfj /home/Charleen/.opam/download-cache/sha256/bc/bcfdf55d981d7e621a696cac34a3af26340d41c045404617df6f5dbfd5165486 -C /tmp/opam-5602-1872ec
Processing  3/12:
00:20.703  PARALLEL               Collected task for job 591019265 (ret:0)
00:21.360  SYSTEM                 rmdir /tmp/opam-5602-ccabea
⬇ retrieved cppo.1.6.6  (cached)
00:21.504  PARALLEL               Job 591019265 finished
00:21.504  PARALLEL               Starting job 853483854 (worker -/7 -/1 3/3): ⬇ extlib.1.7.6
00:21.505  SOLUTION               Fetching sources for extlib.1.7.6
00:21.505  ACTION                 download_package: extlib.1.7.6
00:21.506  SYSTEM                 rmdir /cygdrive/d/development/ocaml/home/Charleen/.opam/ocaml-4.08.1/_opam/.opam-switch/sources/extlib.1.7.6
00:21.707  FILENAME               cleandir /cygdrive/d/development/ocaml/home/Charleen/.opam/ocaml-4.08.1/_opam/.opam-switch/sources/extlib.1.7.6
00:21.708  SYSTEM                 mkdir /cygdrive/d/development/ocaml/home/Charleen/.opam/ocaml-4.08.1/_opam/.opam-switch/sources/extlib.1.7.6
00:21.709  SYSTEM                 mkdir /tmp/opam-5602-d2d111
00:21.977  PARALLEL               Next task in job 853483854: /usr/bin/tar xfz /home/Charleen/.opam/download-cache/md5/b9/b976093ef23b7d60fc1c8f0380c4f76a -C /tmp/opam-5602-d2d111
Processing  4/12:
00:22.148  PARALLEL               Collected task for job 362414859 (ret:0)
00:22.834  SYSTEM                 rmdir /tmp/opam-5602-7afd23
⬇ retrieved cudf.0.9  (cached)
00:23.123  PARALLEL               Job 362414859 finished
00:23.124  PARALLEL               Collected task for job 853483854 (ret:0)
00:23.708  SYSTEM                 rmdir /tmp/opam-5602-d2d111
⬇ retrieved extlib.1.7.6  (cached)
00:23.844  PARALLEL               Job 853483854 finished
00:26.650  PARALLEL               Collected task for job 140570751 (ret:0)
00:34.911  SYSTEM                 rmdir /tmp/opam-5602-1872ec
⬇ retrieved dune.1.11.0  (cached)
00:37.963  PARALLEL               Job 140570751 finished
00:37.963  PARALLEL               Starting job 467548448 (worker 1/7 -/1 -/3): λ dune.1.11.0
00:37.964  SYSTEM                 rmdir /cygdrive/d/development/ocaml/home/Charleen/.opam/ocaml-4.08.1/_opam/.opam-switch/build/dune.1.11.0
00:49.199  ACTION                 prepare_package_source: dune.1.11.0 at /cygdrive/d/development/ocaml/home/Charleen/.opam/ocaml-4.08.1/_opam/.opam-switch/build/dune.1.11.0
00:49.200  SYSTEM                 mkdir /tmp/opam-5602-335865
01:36.616  PARALLEL               Next task in job 467548448: /cygdrive/d/development/ocaml/home/Charleen/.opam/ocaml-4.08.1/_opam/bin/ocaml bootstrap.ml
Processing  5/12: [dune: ocaml bootstrap.ml]
01:49.024  PARALLEL               Collected task for job 467548448 (ret:0)
01:49.045  PARALLEL               Next task in job 467548448: /cygdrive/d/development/ocaml/home/Charleen/.opam/ocaml-4.08.1/_opam/.opam-switch/build/dune.1.11.0/./boot.exe --release -j 7
Processing  5/12: [dune: ./boot.exe 7]
01:50.179  PARALLEL               Collected task for job 467548448 (ret:1)
[ERROR] The compilation of dune failed at "./boot.exe --release -j 7".
01:50.180  PARALLEL               Job 467548448 finished
01:50.180  PARALLEL               Starting job 623076556 (worker -/7 1/1 -/3): ∗ dune.1.11.0
01:50.180  PARALLEL               Job 623076556 finished
01:50.180  PARALLEL               Starting job 761505320 (worker 1/7 -/1 -/3): λ cppo.1.6.6
01:50.180  PARALLEL               Job 761505320 finished
01:50.180  PARALLEL               Starting job 126412880 (worker -/7 1/1 -/3): ∗ cppo.1.6.6
01:50.180  PARALLEL               Job 126412880 finished
01:50.180  PARALLEL               Starting job 63583249 (worker 1/7 -/1 -/3): λ extlib.1.7.6
01:50.180  PARALLEL               Job 63583249 finished
01:50.180  PARALLEL               Starting job 257535829 (worker -/7 1/1 -/3): ∗ extlib.1.7.6
01:50.180  PARALLEL               Job 257535829 finished
01:50.180  PARALLEL               Starting job 921239500 (worker 1/7 -/1 -/3): λ cudf.0.9
01:50.180  PARALLEL               Job 921239500 finished
01:50.180  PARALLEL               Starting job 111259904 (worker -/7 1/1 -/3): ∗ cudf.0.9
01:50.180  PARALLEL               Job 111259904 finished

#=== ERROR while compiling dune.1.11.0 ========================================#
# context     2.1.0~beta | cygwin/x86_64 | ocaml-base-compiler.4.08.1 | https://opam.ocaml.org#1b41dede
# path        /cygdrive/d/development/ocaml/home/Charleen/.opam/ocaml-4.08.1/_opam/.opam-switch/build/dune.1.11.0
# command     /cygdrive/d/development/ocaml/home/Charleen/.opam/ocaml-4.08.1/_opam/.opam-switch/build/dune.1.11.0/./boot.exe --release -j 7
# exit-code   1
# env-file    ~/.opam/log/dune-5602-ad6566.env
# output-file ~/.opam/log/dune-5602-ad6566.out
### output ###
#       1 [main] ocamlrun 5676 child_info_fork::abort: address space needed by 'dllunix.so' (0x400000) is already occupied
# Error: fork: : Resource temporarily unavailable



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions were aborted
│ ∗ install cppo   1.6.6
│ ∗ install cudf   0.9
│ ∗ install extlib 1.7.6
└─
┌─ The following actions failed
│ λ build dune 1.11.0
└─
╶─ No changes have been performed
01:50.188  SYSTEM                 rm /cygdrive/d/development/ocaml/home/Charleen/.opam/ocaml-4.08.1/_opam/.opam-switch/backup/state-20190811211320.export
01:50.188  FILENAME               cleandir /tmp/opam-5602-335865/default
01:50.188  SYSTEM                 rmdir /tmp/opam-5602-335865/default
02:16.211  SYSTEM                 mkdir /tmp/opam-5602-335865/default
02:16.212  SYSTEM                 rmdir /tmp/opam-5602-335865/default
02:16.303  SYSTEM                 rmdir /tmp/opam-5602-335865

```

**Comment by dra27** [comment] 2019-08-20 07:40
Duplicate of #3785 - for now, you need to use Cygwin32

**Closed** 2019-10-07 10:59 UTC
