### ISSUE TITLE
opam lock conflicts with dune 2

### ISSUE THREAD

**Issue by jberdine** [ocaml/opam#4033] opened 2019-11-27 12:52 UTC
Perhaps I have missed something, but it seems that the latest released version of opam is 2.0.5, and it does not include the `opam lock` command (based on `git diff 2.0.5..master -- src/client/opamCommands.ml`). So executing `opam lock` tries to install the `opam-lock` plugin package. That package requires `jbuilder`, though does not have such a dependency. So it seems that the current situation is that it is not possible to install `opam-lock.0.2` and `dune.2.0` together. Is there a workaround? Should the `opam-lock` package be updated to be installable until a new version of opam is released?

**Comment by kit-ty-kate** [comment] 2019-12-04 15:27
`opam lock` is not part of `opam`, it's only a plugin. Could you move this issue to the right repository: https://github.com/AltGr/opam-lock

**Comment by jberdine** [comment] 2019-12-04 15:32
Perhaps I'm confused, but the opam-lock repo is frozen and the README indicates that the opam repo should be used instead. Also, opam master includes the `opam lock` command, see https://github.com/ocaml/opam/blob/master/src/client/opamCommands.ml#L3166 .

**Comment by kit-ty-kate** [comment] 2019-12-04 15:59
Oh I wasn't aware of this sorry. It has been imported in master in https://github.com/ocaml/opam/pull/3746. It will be part of opam 2.1 but no sooner.

In the meantime, it seems that the problem is that the `opam-lock` package forgot to include jbuilder in its specification. And since `jbuilder` and `opam.2.0.0` are co-installable since https://github.com/ocaml/opam-repository/pull/15427, this should be resolved once https://github.com/ocaml/opam-repository/pull/15448 is merged.

**Comment by jberdine** [comment] 2019-12-04 16:50
Ok, thanks! And I guess you mean `jbuilder` and `dune.2.0.0` are co-installable?

**Comment by kit-ty-kate** [comment] 2019-12-04 16:52
huh yes sorry that was what I meant

**Closed** 2019-12-04 16:53 UTC
