### ISSUE TITLE
opam 1.2.0_1 on Mac OS X: Illegal instruction: 4

### ISSUE THREAD

**Issue by hnfmr** [ocaml/opam#1853] opened 2014-11-04 14:53 UTC
Hi, I am not sure if this is a Homebrew problem or opam related problem.

I installed the latest opam 1.2.0_1 through "brew". When I run "opam", I always get:

Illegal instruction: 4

Can anyone help me? Thanks.

**Comment by sdegutis** [comment] 2015-01-26 00:52
I also had this error:

> Illegal instruction: 4

Trying `brew reinstall --build-from-source opam` now (lololololol)

**Comment by sdegutis** [comment] 2015-01-26 01:02
That worked .........

**Comment by avsm** [comment] 2015-01-29 08:23
@AltGr was this fixed in Homebrew?  I think it's still an issue

**Comment by AltGr** [comment] 2015-01-29 08:46
Ah, sorry, thought it was.

**Comment by avsm** [comment] 2015-01-31 15:59
@AltGr this one seems to be hitting quite a few people -- putting a configure fix in 1.2.1 would be good.

**Comment by mikemcquaid** [comment] 2015-02-01 10:20
> @AltGr this one seems to be hitting quite a few people -- putting a configure fix in 1.2.1 would be good.

Yeh, that'd be great. We'll need 1-2 options that allow Homebrew to disable ASM like SSE4 whether it's enabled by `--march=native` or just inlined.

**Comment by amirmc** [comment] 2015-02-01 10:27
Off-topic. :+1: for your talk yesterday :)

**Comment by mikemcquaid** [comment] 2015-02-01 10:49
Thanks @amirmc!

**Comment by AltGr** [comment] 2015-02-02 03:18
According to dbuenzli, it's related to the OCaml package, or didn't I understand correctly ?
So the needed fix may be around  https://github.com/Homebrew/homebrew/blob/master/Library/Formula/objective-caml.rb#L19 (still a bit new to this whole ecosystem). I'm not sure how to workaround this from OPAM's `./configure` without preventing the optimizations on newer system that build from source in the general case (e.g. not brew's bottling) ?

**Comment by mikemcquaid** [comment] 2015-02-02 08:10
Homebrew is already passing `-march=core2duo` as CFLAGS in the Homebrew script and this works for most other software. `gmp.rb` requires a "--disable-assembly" flag so I guess `ocaml` needs something similar?

**Comment by dbuenzli** [comment] 2015-02-02 13:05
The relevant `configure` options are documented [here](https://github.com/ocaml/ocaml/blob/trunk/INSTALL#L51-52) and [here](https://github.com/ocaml/ocaml/blob/trunk/INSTALL#L98-L104) with a few examples [here](https://github.com/ocaml/ocaml/blob/trunk/INSTALL#L143-L158). 

[Here's](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/objective-caml.rb#L22-L25) what's passed to the formula should then simply something like an `Env.CFLAGS` be passed along to the `-cc` option and `-aspp` option in that file ?

**Comment by mikemcquaid** [comment] 2015-02-02 13:12
@dbuenzli Yeh, sounds like it.

**Comment by AltGr** [comment] 2015-02-03 01:57
@dbuenzli , @mikemcquaid : thanks a lot for helping in this.

**Comment by mikemcquaid** [comment] 2015-02-03 08:34
I've merged https://github.com/Homebrew/homebrew/pull/36482 which will hopefully fix this. Can anyone who could reproduce this issue please `brew update; brew reinstall ocaml; brew test ocaml` and see if you can reproduce the error? Thanks!

**Comment by AltGr** [comment] 2015-02-04 01:11
Comment at https://github.com/Homebrew/homebrew/pull/36482#issuecomment-72697986 seems to indicate it's fixed :)

**Comment by avsm** [comment] 2015-02-13 09:52
No regression for me here (it worked on my fancy new Mac laptop previously though, of course)

**Closed** 2015-02-18 07:56 UTC
Labels: portability

**Comment by AltGr** [comment] 2015-03-13 04:29
Hum: we have that in Travis now -- https://travis-ci.org/ocaml/opam/jobs/54192391
Probably because we rely on the XQuartz-2.7.6.dmg image without updating ?
