### ISSUE TITLE
[WARNING] var was deprecated in version 2.1 of the opam CLI. Use opam var instead or set OPAMCLI environment variable to 2.0.

### ISSUE THREAD

**Issue by fblanqui** [ocaml/opam#6191] opened 2024-09-04 14:42 UTC
>   If your issue concerns a package not building, please report to
>   https://github.com/ocaml/opam-repository/issues or to the package maintainer
>   unless you are confident it is an issue in the opam tool itself.
>   If your issue concerns failures with the opam.ocaml.org website, please report to
>   https://github.com/ocaml/infrastructure/issues

```
<include here the output of `opam config report`, if applicable>
16:36 ~ opam config report
# opam config report
# opam-version         2.2.1
# self-upgrade         no
# system               arch=x86_64 os=linux os-distribution=ubuntu os-version=24.04
# solver               builtin-mccs+glpk
# install-criteria     -removed,-count[avoid-version,changed],-count[version-lag,request],-count[version-lag,changed],-count[missing-depexts,changed],-changed
# upgrade-criteria     -removed,-count[avoid-version,changed],-count[version-lag,solution],-count[missing-depexts,changed],-new
# jobs                 31
# repositories         2 (http), 1 (version-controlled) (default repo at 8187cd8d3681d53f5042b5da316fa3f5e005a247)
# pinned               1 (version)
# current-switch       5.1.1
# invariant            ocaml-base-compiler = 5.1.1 | ocaml-system = 5.1.1
# compiler-packages    ocaml-base-compiler.5.1.1, ocaml-options-vanilla.1
# ocaml:native         true
# ocaml:native-tools   true
# ocaml:native-dynlink true
# ocaml:stubsdir       /home/blanqui/.opam/5.1.1/lib/ocaml/stublibs:/home/blanqui/.opam/5.1.1/lib/ocaml
# ocaml:preinstalled   false
# ocaml:compiler       5.1.1
```
Hi. I get the following warnings when I run opam user-setup install:
```
16:38 ~ opam user-setup install
[WARNING] var was deprecated in version 2.1 of the opam CLI. Use opam var instead or set OPAMCLI environment variable to 2.0.
[WARNING] var was deprecated in version 2.1 of the opam CLI. Use opam var instead or set OPAMCLI environment variable to 2.0.
[WARNING] var was deprecated in version 2.1 of the opam CLI. Use opam var instead or set OPAMCLI environment variable to 2.0.
[WARNING] var was deprecated in version 2.1 of the opam CLI. Use opam var instead or set OPAMCLI environment variable to 2.0.
[WARNING] var was deprecated in version 2.1 of the opam CLI. Use opam var instead or set OPAMCLI environment variable to 2.0.
[WARNING] var was deprecated in version 2.1 of the opam CLI. Use opam var instead or set OPAMCLI environment variable to 2.0.
[WARNING] var was deprecated in version 2.1 of the opam CLI. Use opam var instead or set OPAMCLI environment variable to 2.0.
[WARNING] var was deprecated in version 2.1 of the opam CLI. Use opam var instead or set OPAMCLI environment variable to 2.0.
[WARNING] var was deprecated in version 2.1 of the opam CLI. Use opam var instead or set OPAMCLI environment variable to 2.0.
[WARNING] var was deprecated in version 2.1 of the opam CLI. Use opam var instead or set OPAMCLI environment variable to 2.0.
ocamltop > base > .ocamlinit: up to date
emacs > .emacs: already exists, not installing base template
emacs > base > .emacs: up to date
emacs > base > .emacs.d/opam-user-setup.el: up to date
emacs > tuareg > .emacs.d/opam-user-setup.el: updating configuration
```

**Comment by kit-ty-kate** [comment] 2024-09-04 14:45
Duplicate of https://github.com/ocaml-opam/opam-user-setup/issues/55

**Closed by kit-ty-kate** 2024-09-04 14:45 UTC
